import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import OpenAI from "npm:openai@4";
import {
  AI_DATA_FIDELITY_RULES,
  AI_EVIDENCE_AND_SEVERITY_RULES,
  AI_FOLLOW_UP_EVIDENCE_RULES,
  AI_IMAGE_CONTEXT_RULES,
  appendSourcesFooter,
  buildFunctionalQuestionsPromptBlock,
  buildPhysioEquipmentContext,
  formatRagContext,
  languageInstruction,
  type RagChunk,
} from "./response-rules.ts";

const openai = new OpenAI({ apiKey: Deno.env.get("OPENAI_API_KEY") });

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

type HistoryMessage = { role: "user" | "assistant"; content: string };

type RequestBody = {
  mode?:
    | "triage"
    | "general_chat"
    | "clinical_screen"
    | "consult"
    | "reminders"
    | "physio_report"
    | "physio_chat"
    | "multi_part_summary";
  message?: string;
  bodyArea?: string;
  onsetType?: string;
  painLevel?: number;
  hadTrauma?: string;
  description?: string;
  symptomContext?: string;
  conversationHistory?: HistoryMessage[];
  language?: "es" | "en";
  /** Public URL of an injury photo in the consult-photos bucket */
  imageUrl?: string | null;
  /** Patient-facing informe already generated by the "consult" mode (physio_report mode only) */
  patientSummary?: string;
  /** Patient is in the Fisioterapia flow (entered a physio invite code) */
  fisioterapiaFlow?: boolean;
  linkedPhysioName?: string | null;
  linkedClinicName?: string | null;
};

type TextContentPart = { type: "text"; text: string };
type ImageContentPart = {
  type: "image_url";
  image_url: { url: string; detail: "high" | "low" | "auto" };
};
type UserContent = string | Array<TextContentPart | ImageContentPart>;

function isAllowedConsultImageUrl(url: string): boolean {
  try {
    const u = new URL(url);
    const supabaseUrl = Deno.env.get("SUPABASE_URL") ?? "";
    if (!supabaseUrl) return false;
    const base = new URL(supabaseUrl);
    return (
      u.origin === base.origin &&
      u.pathname.includes("/storage/v1/object/public/consult-photos/")
    );
  } catch {
    return false;
  }
}

function sanitizeImageUrl(imageUrl?: string | null): string | null {
  if (!imageUrl || typeof imageUrl !== "string") return null;
  const trimmed = imageUrl.trim();
  return isAllowedConsultImageUrl(trimmed) ? trimmed : null;
}

function buildUserContent(text: string, imageUrl?: string | null): UserContent {
  const safe = sanitizeImageUrl(imageUrl);
  if (!safe) return text;
  return [
    { type: "text", text },
    { type: "image_url", image_url: { url: safe, detail: "high" } },
  ];
}

function withImageRules(prompt: string, hasImage: boolean): string {
  if (!hasImage) return prompt;
  return `${prompt}\n\n${AI_IMAGE_CONTEXT_RULES}`;
}

function withLanguage(prompt: string, language: "es" | "en"): string {
  return `${prompt}\n\n${languageInstruction(language)}`;
}

function linkedPhysioLabel(
  name?: string | null,
  clinic?: string | null
): string {
  const n = name?.trim();
  const c = clinic?.trim();
  if (n && c) return `${n} (${c})`;
  if (n) return n;
  if (c) return `tu fisioterapeuta de ${c}`;
  return "tu fisioterapeuta";
}

/**
 * Extra system rules when the patient is in /fisioterapia after redeeming a code.
 * Helps Physio answer "why am I here?" / "what should I do?" with the right frame.
 */
function withFisioterapiaFlow(
  prompt: string,
  body: RequestBody,
  language: "es" | "en"
): string {
  if (!body.fisioterapiaFlow) return prompt;
  const who = linkedPhysioLabel(body.linkedPhysioName, body.linkedClinicName);
  const block =
    language === "en"
      ? `PHYSIOTHERAPY TAB — REPORT FLOW ONLY (CRITICAL — NEVER IGNORE):
This patient redeemed an invite code from physiotherapist **${who}**.

PURPOSE OF THIS CHAT (the ONLY purpose):
- Collect the complaint + questionnaire answers needed to generate a clinical report for **${who}**.
- That report goes to **${who}**'s dashboard before the appointment. You are NOT chatting with ${who}; you are an AI preparing their report.

STRICT RULES:
- Do NOT invite free-form chatting or "ask me anything" in this tab.
- Do NOT say the patient can talk "directly" with **${who}** (or any physiotherapist) inside Kinora — neither this tab nor Consulta is a live chat with the clinician.
- If they ask where to ask doubts / general questions / anything not needed for the report: tell them clearly to use the **Consulta** tab for free questions with the AI. This Fisioterapia chat is only to finish the case so the report for **${who}** can be prepared.
- If they ask about the process/code/why they're here: explain briefly that this is for the pre-visit report for **${who}**, then steer them back to describing the complaint if the report is not done yet.
- Keep answering clinical questions that help complete or clarify the report case. For unrelated chat, redirect to Consulta.`
      : `PESTAÑA FISIOTERAPIA — SOLO INFORME PARA EL FISIO (CRÍTICO — NO IGNORAR NUNCA):
El paciente ha introducido el código de su fisioterapeuta **${who}**.

ÚNICO OBJETIVO DE ESTE CHAT:
- Recoger la molestia + cuestionario necesarios para generar un **informe clínico** para **${who}**.
- Ese informe va al panel de **${who}** antes de la cita. Tú NO eres ${who}; eres la IA que prepara su informe.

REGLAS ESTRICTAS:
- NO invites a chatear libremente ni digas "puedes preguntarme lo que quieras aquí".
- NUNCA digas que puede hablar "directamente" con **${who}** (ni con ningún fisioterapeuta) dentro de Kinora: ni esta pestaña ni Consulta son un chat en vivo con el profesional.
- Si pregunta dónde resolver dudas / preguntas generales / cosas que no hacen falta para el informe: dile con claridad que use la pestaña **Consulta** para hablar libremente con la IA. Este chat de Fisioterapia es SOLO para completar el caso y preparar el informe de **${who}**.
- Si pregunta por el proceso/código/por qué está aquí: explica en breve que es para el informe previo a la cita de **${who}**, y vuelve a orientar a describir la molestia si el informe aún no está listo.
- Sí puedes responder preguntas clínicas que ayuden a completar o aclarar el caso del informe. Para charla o dudas generales, redirige a Consulta.`;
  return `${prompt}\n\n${block}`;
}

/** Regular Consulta tab: no physio-linked report flow. */
function withConsultaGeneralRules(
  prompt: string,
  body: RequestBody,
  language: "es" | "en"
): string {
  if (body.fisioterapiaFlow) return prompt;
  const block =
    language === "en"
      ? `GENERAL CONSULTA TAB (not the Fisioterapia code flow):
- Do NOT say a clinical report was or will be sent to their physiotherapist or appears on any physio dashboard.
- This tab is informational AI chat only; physio-linked reports exist ONLY in the separate Fisioterapia tab after they enter their physio's invite code.
- The section **¿Necesitas contactar con nuestro fisioterapeuta?** is optional guidance to seek in-person care if needed — it does NOT mean Kinora sent anything to a linked physiotherapist.`
      : `PESTAÑA CONSULTA GENERAL (NO es el flujo Fisioterapia con código):
- NO digas que se ha generado, se enviará o verá un informe clínico en el panel de ningún fisioterapeuta.
- Aquí solo hay orientación informativa con la IA; el informe para el fisio vinculado existe SOLO en la pestaña Fisioterapia tras introducir el código.
- La sección **¿Necesitas contactar con nuestro fisioterapeuta?** es orientación para valoración presencial si la necesitan — NO significa que Kinora haya enviado nada a un fisio vinculado.`;
  return `${prompt}\n\n${block}`;
}

function withPatientConsultContext(
  prompt: string,
  body: RequestBody,
  language: "es" | "en"
): string {
  return withConsultaGeneralRules(
    withFisioterapiaFlow(prompt, body, language),
    body,
    language
  );
}

function buildAthleteContext(profile: Record<string, unknown> | null): string {
  if (!profile) return "";
  const lines = [
    profile.display_name ? `Nombre: ${profile.display_name}` : "",
    profile.age ? `Edad: ${profile.age} años` : "",
    profile.sex ? `Sexo: ${profile.sex}` : "",
    profile.height_cm ? `Altura: ${profile.height_cm} cm` : "",
    profile.weight_kg ? `Peso: ${profile.weight_kg} kg` : "",
    profile.dominant_hand ? `Mano dominante: ${profile.dominant_hand}` : "",
    profile.dominant_foot ? `Pie dominante: ${profile.dominant_foot}` : "",
    profile.primary_sport ? `Deporte habitual: ${profile.primary_sport}` : "",
    profile.sport_position ? `Posición: ${profile.sport_position}` : "",
    profile.competitive_level ? `Nivel competitivo: ${profile.competitive_level}` : "",
    profile.sessions_per_week != null
      ? `Sesiones de entrenamiento por semana: ${profile.sessions_per_week}`
      : "",
    profile.hours_per_week != null
      ? `Horas de entrenamiento por semana: ${profile.hours_per_week}`
      : "",
    profile.current_season ? `Temporada actual: ${profile.current_season}` : "",
    Array.isArray(profile.performance_goals) && profile.performance_goals.length
      ? `Objetivos: ${profile.performance_goals.join(", ")}`
      : "",
  ].filter(Boolean);
  if (!lines.length) return "";
  return [
    "Perfil del paciente (ÚSALO para riesgo, prevalencia, carga y diferenciales; NO lo uses como mecanismo/causa de la lesión salvo que el relato o el cuestionario lo confirmen):",
    ...lines,
  ].join("\n");
}

async function embedAndMatch(
  supabase: ReturnType<typeof createClient>,
  queryText: string,
  matchCount: number
): Promise<RagChunk[]> {
  if (queryText.trim().length <= 10) return [];
  const embeddingRes = await openai.embeddings.create({
    model: "text-embedding-3-small",
    input: queryText.slice(0, 8000),
  });
  const queryEmbedding = embeddingRes.data[0].embedding;
  const { data: chunks } = await supabase.rpc("match_document_chunks", {
    query_embedding: queryEmbedding,
    match_count: matchCount,
    match_threshold: 0.3,
  });
  return (chunks ?? []) as RagChunk[];
}

async function fetchRagContext(
  supabase: ReturnType<typeof createClient>,
  queryText: string,
  bodyArea = ""
): Promise<{ context: string; sources: string[] }> {
  const primary = await embedAndMatch(supabase, queryText, 6);
  const functionalQuery = [
    bodyArea,
    "Functional Assessment Special Tests Clinical Tests valoración funcional movement tests",
  ]
    .filter(Boolean)
    .join(" ");
  const functional = await embedAndMatch(supabase, functionalQuery, 4);

  const byId = new Map<string, RagChunk>();
  for (const c of [...primary, ...functional]) {
    const key = `${c.source_name ?? ""}::${(c.content ?? "").slice(0, 80)}`;
    if (!byId.has(key)) byId.set(key, c);
  }
  return formatRagContext([...byId.values()]);
}

const TRIAGE_SYSTEM_PROMPT = `Eres Physio, asistente de Kinora. Clasificas cada mensaje del usuario (inicial o de seguimiento).

Devuelve SOLO JSON válido con esta forma:
{
  "action": "questionnaire" | "respond",
  "bodyPart": "shoulder" | "elbow" | "wrist_hand" | "finger" | "neck" | "back" | "hip" | "knee" | "ankle_foot" | null,
  "intent": "general" | "symptom_other" | null,
  "answer": "string o null"
}

REGLAS DE CLASIFICACIÓN:

1) action = "questionnaire" SI el usuario describe un PROBLEMA PERSONAL ACTUAL (dolor, molestia, lesión, limitación, hinchazón, traumatismo, rigidez) en CUALQUIER zona musculoesquelética.
   - Incluye: hombro, codo, muñeca/mano, dedo(s), cuello/cervical, espalda, cadera, rodilla, pierna baja/tobillo/pie.
   - Incluye mensajes de seguimiento como "también me duele el codo" o "ahora me molesta el cuello".
   - bodyPart debe ser la zona principal de ESTE mensaje (shoulder, elbow, wrist_hand, finger, neck, back, hip, knee, ankle_foot).
   - Usa "finger" cuando el problema es específico de uno o varios dedos; "wrist_hand" para muñeca/mano en general; "neck" para cuello/cervical; "back" para espalda/lumbar/dorsal.
   - CRÍTICO — NO confundas rodilla con pierna bajo la rodilla:
     * "me duele la pierna, justo debajo de la rodilla" / "debajo de la rodilla" / "below the knee" / "espinilla" / "shin" / "pantorrilla" / "gemelo" / "pierna" (sin decir que duele la articulación de la rodilla) → bodyPart = "ankle_foot" (pierna baja / tibia / tobillo-pie). NUNCA "knee".
     * "me duele la rodilla" / "menisco" / "ligamento cruzado" / "rótula" → bodyPart = "knee".
     * Si menciona "rodilla" solo como referencia de ubicación ("debajo de la rodilla"), NO es knee.
   - CRÍTICO — pie / planta NO es "pierna":
     * "me duele la planta del pie" / "fascitis" / "talón" / "me duele el pie" → bodyPart = "ankle_foot" (el cuestionario se adapta al PIE). No trates el relato como dolor de pantorrilla/espinilla.
   - intent = null, answer = null
   - NUNCA saltes el cuestionario para dar ya un informe clínico: primero se recogen datos.

2) action = "respond" con intent = "general" si pregunta por ejercicios, movilidad, estiramientos, prevención, información educativa, rutinas, ergonomía, o dudas generales — AUNQUE mencione una zona corporal.
   - Ejemplos: "ejercicios de movilidad para hombro", "cómo estirar la muñeca", "qué es la epicondilitis"

2b) action = "respond" con intent = "general" si el usuario NO describe un problema actual sino que pregunta CÓMO usar la consulta, qué debe hacer, pide aclaraciones, o pregunta por el fisioterapeuta / el código / el informe / por qué le han enviado aquí.
   - Ejemplos: "hola qué hago", "¿te digo lo que me duele o cómo funciona esto?", "cómo funciona", "por dónde empiezo", "no sé qué contarte", "me ha enviado mi fisio", "¿mi fisio verá esto?", "para qué es el código"
   - LEE el mensaje completo: si pregunta por el proceso, RESPONDE explicando. Si hay contexto de Fisioterapia en el system prompt: deja CLARO que este chat es SOLO para preparar el informe del fisio vinculado; para dudas generales debe ir a la pestaña Consulta; NUNCA digas que Consulta es hablar directamente con el fisioterapeuta. NO abras cuestionario.
   - Aunque diga "duele" de forma hipotética ("¿te digo lo que me duele?") NO es síntoma actual → respond, NO questionnaire.

3) action = "respond" con intent = "general" — answer: respuesta útil en español (6-14 frases), empática, práctica, sin informe clínico largo. Indica que no es diagnóstico. Si procede, invita a describir molestias concretas para una valoración más detallada.

4) action = "respond" con intent = "symptom_other" SOLO si describe síntomas personales ACTUALES pero NO se puede asignar una zona concreta (muy vago) o varias zonas a la vez sin zona principal clara.
   - bodyPart = null, answer = null (el cliente abrirá cuestionario genérico)

NO uses "questionnaire" para peticiones de ejercicios, consejos generales o preguntas hipotéticas.
NO uses clinical screen / respuesta larga de lesiones sin cuestionario cuando hay un problema personal en una zona.`;

const GENERAL_CHAT_PROMPT = `Eres Physio, asistente de fisioterapia y medicina deportiva de Kinora.

El usuario hace una consulta general (ejercicios, movilidad, prevención, información) o pregunta cómo funciona la consulta / qué debe hacer.

LEE SIEMPRE el mensaje del usuario y responde a lo que pregunta. No ignores su pregunta ni saltes directo a un cuestionario.

Si pregunta cómo funciona o qué debe hacer (ej. "hola qué hago", "¿te digo lo que me duele o cómo funciona esto?"):
- Explícale con claridad: puede contarte qué le molesta, en qué zona del cuerpo, desde cuándo y qué la empeora
- Indica que le harás algunas preguntas para orientarle mejor
- La orientación no sustituye una valoración presencial ni es un diagnóstico
- Invítale a escribir su molestia cuando quiera

Responde en español:
- Empático, claro y práctico (normalmente 6-14 frases; más si hace falta para una mini-rutina)
- NO emitas diagnóstico definitivo
- Puedes sugerir ejercicios o consejos generales con precauciones
- Si no hay una lesión descrita, no inventes síntomas ni mecanismos
- Cierra invitando a contarte molestias concretas si quiere una orientación más personalizada`;

const MULTI_PART_SUMMARY_PROMPT = `Eres Physio, asistente de Kinora. El paciente ha completado cuestionarios de VARIAS zonas corporales y ya recibió la orientación de cada una por separado.

Tu trabajo: redactar un **informe final unificado** (en el idioma del paciente) que reúna todas las zonas afectadas y valore si están relacionadas.

FORMATO OBLIGATORIO (usa negrita con **…** en los títulos):
**Resumen final de tu consulta**
- 2-4 frases: qué zonas se evaluaron y el cuadro global (sin inventar datos nuevos).

Luego, por CADA zona evaluada (en el mismo orden que te las pasan):
**[Nombre de la zona]**
- Hallazgos / posibles estructuras o lesiones orientativas (breve)
- Qué hacer ahora / recomendaciones clave (breve)
- Si aplica: cuándo consultar presencialmente

Al final (OBLIGATORIO — no omitas estas secciones):
**¿Están relacionadas las molestias?**
- Di claramente una de estas tres conclusiones: **relacionadas**, **posiblemente relacionadas**, o **independientes**.
- Explica **por qué** (mecanismo compartido, dolor referido, compensación / cadena cinética, o coincidencia temporal) basándote SOLO en las orientaciones por zona; no fuerces una relación.

**Hipótesis orientativas**
- 2-5 bullets de lo que podría explicar el cuadro (o que no hay vínculo claro). No es un diagnóstico médico.

**Qué debes hacer ahora (global)**
- Lista corta priorizada (reposo relativo, pruebas, fisio, imagen, urgencias si procede)

REGLAS:
- Basa TODO en los textos de orientación ya generados por zona que te pasan; no inventes mecanismos ni síntomas nuevos.
- Habla como **Physio** (nunca digas «la IA»).
- Lenguaje sencillo para el paciente; no es diagnóstico médico.
- Sé conciso: orientativo 350-700 palabras en total.
- Destaca en negrita nombres de lesiones/cuadros y destinos clave (**fisioterapeuta**, **urgencias**, etc.).`;

const REMINDERS_SYSTEM_PROMPT = `Eres Physio de Kinora. Generas recordatorios locales inteligentes para un paciente con una molestia musculoesquelética.

Devuelve SOLO JSON válido:
{
  "reminders": [
    { "title": string, "body": string, "dayOffset": number, "hour": number }
  ]
}

Reglas:
- Exactamente 5 a 7 recordatorios.
- dayOffset: 0 a 10 (días desde hoy).
- hour: 8 a 20.
- Personaliza título y cuerpo a la zona lesionada, dolor y contexto.
- Tono empático, claro, accionable; sin diagnóstico ni alarmismo.
- Incluye movilidad suave, gestión de carga, chequeo de síntomas y seguimiento.
- Si language=en responde en inglés; si language=es en español.
- No inventes diagnósticos concretos; habla de molestia/zona.`;

const CLINICAL_SCREEN_PROMPT = `Eres un asistente de fisioterapia y medicina deportiva para Kinora. Orientas al usuario en español con claridad, empatía y detalle moderado (aprox. 450-800 palabras).

IMPORTANTE: NO emites diagnósticos definitivos.

${AI_EVIDENCE_AND_SEVERITY_RULES}

Integra la descripción del paciente, el cuestionario (si hay) y el PERFIL del paciente (edad, sexo, antropometría, deporte, carga) para orientar riesgo y diferenciales. No inventes datos que no estén en el contexto.
El deporte habitual del perfil NO implica por sí solo el mecanismo de la lesión.

${AI_DATA_FIDELITY_RULES}`;

const INITIAL_SYSTEM_PROMPT = `Eres un asistente de fisioterapia y medicina deportiva para Kinora. Orientas al usuario en español con claridad, empatía y detalle moderado (aprox. 450-850 palabras).

IMPORTANTE: NO emites diagnósticos definitivos. Usas las variables clínicas para estimar estructuras afectadas, posibles lesiones (con confianza alta/media/baja), gravedad y el siguiente paso adecuado.

En el resumen (2-4 frases): zona, mecanismo, evolución, intensidad, limitación. Si hay banderas rojas o PRIORIDAD ALTA, destácalo al inicio.

CRÍTICO — DIFERENCIACIÓN KINORA: si el caso NO es urgente, la respuesta está incompleta sin la sección **Pruebas funcionales**. Incluye 3–6 pruebas concretas de la zona (del banco/protocolo inyectado) y pide: «Haz estas pruebas y responde aquí qué pasa en cada una». Escribe cada prueba como instrucción cotidiana de movimiento (p. ej. elevar el brazo por encima de la cabeza y ver si duele). NUNCA uses «Test de…» ni nombres clínicos (Neer, Hawkins, Spurling, etc.).

${AI_EVIDENCE_AND_SEVERITY_RULES}

REGLAS:
- Usa todo el contexto clínico del cuestionario
- Lenguaje sencillo, tono cercano

${AI_DATA_FIDELITY_RULES}`;

const FOLLOW_UP_SYSTEM_PROMPT = `Eres un asistente de fisioterapia para Kinora. Estás en una conversación de SEGUIMIENTO: el paciente ya recibió una valoración inicial estructurada.

REGLAS ESTRICTAS PARA ESTE MENSAJE:
- Es el MISMO caso. Usa el historial. NUNCA reinicies como si fuera una consulta nueva ni repitas todo el cuestionario o toda la batería de tests sin interpretar lo que ya respondió.
- Si el bloque "Contexto de la conversación" indica ELECCIÓN ENTRE ZONAS / BETWEEN-ZONES: respóndelo al pie de la letra. NO digas que ya empezaste un cuestionario nuevo. NO ignores la pregunta del paciente. Ayúdale a elegir entre pruebas funcionales ahora o el siguiente cuestionario.
- Si el paciente responde a tests funcionales (p. ej. "pude hacer los 3, pero me duele otra cosa / duele en otro sitio"): INTERPRETA eso primero. Baja hipótesis locales no reproducidas; abre alternativas (otra estructura local o causa a distancia, p. ej. cuello → codo). Haz 1–3 preguntas concretas de aclaración; no vuelvas a pedir "haz otra vez todos los tests" ni un informe completo.
- Integra TODA la historia (mecanismo, neurológicos, agravantes, antecedentes) con las pruebas: las pruebas confirman/descartan, no borran hallazgos previos. Si hay neurológicos claros, no priorices solo musculotendinoso.
- Tras interpretar: reordena hipótesis de mayor a menor probabilidad y di qué evidencia sube/baja cada una.
- Responde SOLO a la pregunta concreta del paciente en este turno
- NO repitas el informe completo ni vuelvas a usar todas las secciones de la primera respuesta
- NO reescribas el "Resumen de tu consulta" salvo que lo pidan explícitamente
- Sé directo, empático y específico (normalmente 4-12 frases; más si interpreta respuestas a tests funcionales)
- Evalúa causas locales Y posibles orígenes referidos cuando encaje (cuello/hombro/lumbar, etc.)
- Si hay perfil del paciente en el contexto, úsalo para matizar riesgo/carga/diferenciales (sin reinventar el mecanismo)
- Si preguntan qué hacer, adónde ir o si preocuparse: responde con pasos claros (urgencias / médico / fisioterapeuta / autocuidado) y cuándo
- Puedes usar un encabezado **Qué debes hacer ahora** si la pregunta es sobre acciones concretas
- No uses formato de informe completo con todas las secciones salvo que el paciente pida reevaluación completa
- Si concluyes qué lesión o cuadro puede tener el paciente, escribe ese nombre en negrita (p. ej. **síndrome del pronador**). Solo el nombre, no la frase entera.
- Destaca también en negrita adónde debe acudir o qué prueba: **fisioterapeuta**, **médico**, **urgencias**, **ecografía**, etc.

${AI_FOLLOW_UP_EVIDENCE_RULES}`;

const PHYSIO_CHAT_SYSTEM_PROMPT = `Eres el asistente clínico de Kinora para FISIOTERAPEUTAS (no para pacientes).

DESTINATARIO: profesional sanitario. Usa lenguaje técnico y nomenclatura clínica estándar.
- Nombrar maniobras y tests con su nombre propio (Neer, Hawkins-Kennedy, Jobe/Empty can, Spurling, ULTT, Lachman, McMurray, FABER, FADIR, Thompson, Ottawa, Windlass, etc.).
- Hablar de hipótesis diagnósticas, sensibilidad/especificidad cuando aporte, red flags y criterio de imagen (RX/US/RM).
- NO uses el tono ni el formato del informe para pacientes (nada de “Pruebas funcionales” en lenguaje cotidiano).
- FORMATO: NUNCA uses encabezados Markdown con # / ## / ###. Para títulos de sección usa solo negrita con **así** (p. ej. **Hipótesis diagnósticas**). El resto del texto en párrafos y listas normales.
- MATERIAL DE LA CONSULTA: si el mensaje de usuario incluye el bloque de material disponible, ÚSALO. Prioriza lo que el fisio puede hacer en su consulta. Si recomiendas algo que no tiene (imagen, aparato, técnica), dilo claramente y sugiere dónde/cómo derivar (centro de imagen, otro profesional, etc.).
- Sé conciso, estructurado y útil en consulta. Si falta información clínica, pide los datos que faltan.
- No emitas diagnóstico definitivo; orienta el razonamiento clínico.
- MANIOBRAS CON NOMBRE ESTÁNDAR: cuando listes pruebas/maniobras, usa el nombre clínico canónico en la misma línea numerada (p. ej. "1. **Test de Lachman**: …", "2. **Hawkins-Kennedy**: …", "3. **Pivot Shift**: …"). No inventes nombres raros; preferir: Lachman, cajón anterior, Pivot Shift, McMurray, Neer, Hawkins-Kennedy, Jobe/Empty can, Spurling, Thompson, FABER, FADIR, Phalen, Trendelenburg, Speed, Apprehension.

FIDELIDAD AL MENSAJE DEL FISIOTERAPEUTA (CRÍTICO — incumplir esto es un error grave):
- NO inventes ni asumas síntomas, temporalidad, mecanismo, intensidad, cronicidad ni hallazgos que el fisioterapeuta NO haya dicho explícitamente.
- Ejemplos PROHIBIDOS si no los dijo: “dolor agudo”, “dolor crónico”, “tras traumatismo”, “por sobreuso”, “inflamación”, “inestabilidad”, “irradiación”, “noche/sueño”, etc.
- Si solo dice “evaluar un paciente de hombro” (o equivalente), trata el caso como evaluación genérica de hombro: describe el enfoque sistemático (anamnesis → exploración → tests especiales → imagen si procede) SIN presuponer el tipo de dolor ni el diagnóstico.
- Cuando cites el caso en la respuesta, usa SOLO las palabras/hechos del fisio (p. ej. “paciente de hombro”), no reformules añadiendo cualificadores clínicos inventados.
- Si necesitas temporalidad, mecanismo o síntomas para afinar, PREGÚNTALOS; no los rellenes tú.`;

const PHYSIO_REPORT_SYSTEM_PROMPT = `Eres un asistente clínico de Kinora que redacta un informe PRE-VISITA para un fisioterapeuta, a partir del cuestionario que ya completó su paciente con la IA.

DESTINATARIO: un profesional sanitario (fisioterapeuta), no el paciente. Usa lenguaje técnico/clínico (nombres de estructuras, maniobras, hipótesis diagnósticas). NO simplifiques el texto como si fuera para el paciente.

TERMINOLOGÍA TÉCNICA (CRÍTICO):
- En **Resultados de las pruebas funcionales ya realizadas** y en **Pruebas/maniobras a realizar en la cita**, usa SIEMPRE los nombres clínicos reales de las maniobras (p. ej. Neer, Hawkins-Kennedy, Jobe/Empty can, Speed, Yergason, Spurling, ULTT, Phalen, Tinel, Cozen, Mill, Lachman, Pivot shift, McMurray, Thessaly, FABER, FADIR, Trendelenburg, Thompson, Ottawa ankle/foot, Windlass, Matles, etc.).
- El paciente recibió las pruebas en lenguaje cotidiano (“elevar el brazo por encima de la cabeza”, “apoyar el pie…”, “girar la cabeza…”). TRADÚCELAS al nombre técnico equivalente cuando sea razonable, y entre paréntesis puedes citar brevemente lo que se le pidió al paciente.
  Ejemplo: “**Neer / elevación activa dolorosa** (paciente: elevar el brazo por encima de la cabeza) — positivo / negativo / no realizado”.
- En **Pruebas/maniobras a realizar en la cita**, prioriza maniobras con nombre técnico estándar; no digas solo “hacer que levante el brazo”.
- Hipótesis y estructuras: usa nomenclatura clínica habitual (p. ej. tendinopatía del supraespinoso, radiculopatía C7, esguince ATFL, fascitis plantar, síndrome del túnel cubital).

IMPORTANTE: no contradigas el informe que ya recibió el paciente (te lo paso como "Informe ya entregado al paciente"); constrúyelo, amplíalo y añade la lectura clínica que le falta a un texto pensado para el paciente. Si detectas una discrepancia relevante, señálala explícitamente como "punto a verificar en consulta" en vez de simplemente cambiar la conclusión.

NO inventes datos que no estén en el cuestionario, la descripción del paciente o el perfil. Si falta información clínicamente relevante, dilo explícitamente en "Puntos de alerta" o pide que se confirme en consulta.

Devuelve el informe en este orden de secciones, usando encabezados en negrita exactamente así:

**Resumen para el fisioterapeuta** — 2-4 frases: zona, mecanismo, evolución, intensidad, limitación funcional y nivel de prioridad (alta/media/baja).

**Datos del paciente** — edad, sexo, deporte/actividad y otros datos del perfil relevantes para el caso (si están disponibles).

**Historia y mecanismo** — cómo y cuándo empezó, traumatismo o sobreuso, evolución, agravantes/aliviantes, tratamientos previos si se mencionan.

**Resultados de las pruebas funcionales ya realizadas** — lista cada prueba con su nombre clínico (y entre paréntesis la instrucción cotidiana que vio el paciente, si aplica), el resultado (SÍ/NO u otro) y qué sugiere.

**Hipótesis diagnósticas (por probabilidad)** — lista ordenada de mayor a menor probabilidad, con el razonamiento clínico y el nivel de confianza (alta/media/baja) de cada una.

**Pruebas/maniobras a realizar en la cita** — tests clínicos concretos con nombre técnico que el fisioterapeuta debería hacer para confirmar o descartar cada hipótesis.

**Pruebas de imagen si procede** — solo si está clínicamente indicado dado el cuadro (radiografía, ecografía, RM); si no procede, dilo brevemente.

**Puntos de alerta** — banderas rojas, discrepancias con el informe del paciente, o información que falta y conviene confirmar en la cita.

Sé denso y clínico pero claro; evita relleno. Extensión orientativa: 350-650 palabras.`;

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: CORS });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...CORS, "Content-Type": "application/json" },
      });
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...CORS, "Content-Type": "application/json" },
      });
    }

    const body = (await req.json()) as RequestBody;
    const mode = body.mode ?? "consult";
    const language = body.language === "en" ? "en" : "es";

    const { data: profile } = await supabase
      .from("profiles")
      .select(
        "display_name, age, sex, height_cm, weight_kg, dominant_hand, dominant_foot, primary_sport, sport_position, competitive_level, sessions_per_week, hours_per_week, current_season, performance_goals, clinic_name, clinic_equipment, clinic_equipment_notes"
      )
      .eq("id", user.id)
      .maybeSingle();

    const athleteContext = buildAthleteContext(profile);
    const physioEquipmentContext = buildPhysioEquipmentContext(profile);

    if (mode === "triage") {
      const message = body.message?.trim() ?? "";
      const imageUrl = sanitizeImageUrl(body.imageUrl);
      if (!message && !imageUrl) {
        return new Response(JSON.stringify({ error: "message required" }), {
          status: 400,
          headers: { ...CORS, "Content-Type": "application/json" },
        });
      }

      const triageText = imageUrl
        ? `${message || "(El paciente adjuntó una foto de la lesión sin texto.)"}\n\nHay una foto adjunta: úsala para ayudar a identificar la zona corporal si el texto es ambiguo.`
        : message;

      const completion = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        response_format: { type: "json_object" },
        messages: [
          {
            role: "system",
            content: withPatientConsultContext(
              withLanguage(
                withImageRules(TRIAGE_SYSTEM_PROMPT, Boolean(imageUrl)),
                language
              ),
              body,
              language
            ),
          },
          { role: "user", content: buildUserContent(triageText, imageUrl) },
        ],
        temperature: 0.2,
        max_tokens: 600,
      });

      const raw = completion.choices[0].message.content ?? "{}";
      let parsed: Record<string, unknown>;
      try {
        parsed = JSON.parse(raw);
      } catch {
        parsed = { action: "respond", intent: "general" };
      }

      return new Response(JSON.stringify(parsed), {
        headers: { ...CORS, "Content-Type": "application/json" },
      });
    }

    if (mode === "general_chat") {
      const message = body.message?.trim() ?? "";
      const imageUrl = sanitizeImageUrl(body.imageUrl);
      const { context } = await fetchRagContext(supabase, message);
      const userMessage = [
        `Consulta del usuario:\n${message || "(Foto de la lesión adjunta)"}`,
        imageUrl
          ? "El paciente adjuntó una foto: descríbela solo si aporta y responde en consecuencia."
          : "",
        athleteContext ? athleteContext : "",
        context
          ? `Información de referencia:\n${context}`
          : "(Responde con conocimientos generales de fisioterapia.)",
      ]
        .filter(Boolean)
        .join("\n\n");

      const completion = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [
          {
            role: "system",
            content: withPatientConsultContext(
              withLanguage(
                withImageRules(GENERAL_CHAT_PROMPT, Boolean(imageUrl)),
                language
              ),
              body,
              language
            ),
          },
          { role: "user", content: buildUserContent(userMessage, imageUrl) },
        ],
        temperature: 0.5,
        max_tokens: 800,
      });

      const answer = completion.choices[0].message.content ?? "";
      return new Response(JSON.stringify({ answer }), {
        headers: { ...CORS, "Content-Type": "application/json" },
      });
    }

    if (mode === "reminders") {
      const bodyArea = body.bodyArea ?? "";
      const description = body.description ?? "";
      const painLevel = body.painLevel ?? 0;
      const symptomContext = body.symptomContext ?? "";

      const userMessage = [
        `language=${language}`,
        `Zona / body area: ${bodyArea}`,
        `Dolor / pain: ${painLevel}/10`,
        description ? `Descripción: ${description}` : "",
        symptomContext ? `Contexto clínico:\n${symptomContext}` : "",
        athleteContext ? athleteContext : "",
      ]
        .filter(Boolean)
        .join("\n\n");

      const completion = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        response_format: { type: "json_object" },
        messages: [
          {
            role: "system",
            content: withLanguage(REMINDERS_SYSTEM_PROMPT, language),
          },
          { role: "user", content: userMessage },
        ],
        temperature: 0.4,
        max_tokens: 900,
      });

      const raw = completion.choices[0].message.content ?? "{}";
      let parsed: Record<string, unknown>;
      try {
        parsed = JSON.parse(raw);
      } catch {
        parsed = { reminders: [] };
      }

      return new Response(JSON.stringify(parsed), {
        headers: { ...CORS, "Content-Type": "application/json" },
      });
    }

    if (mode === "multi_part_summary") {
      const message = body.message?.trim() ?? "";
      const bodyArea = body.bodyArea ?? "Varias zonas";
      if (!message) {
        return new Response(JSON.stringify({ error: "message required" }), {
          status: 400,
          headers: { ...CORS, "Content-Type": "application/json" },
        });
      }

      const { context, sources } = await fetchRagContext(
        supabase,
        `${bodyArea}\n${message}`,
        bodyArea
      );
      const userMessage = [
        `Zonas evaluadas: ${bodyArea}`,
        `Orientaciones ya entregadas por zona (úsalas como única base de hechos):\n${message}`,
        athleteContext ? athleteContext : "",
        context
          ? `Información de referencia:\n${context}`
          : "",
      ]
        .filter(Boolean)
        .join("\n\n");

      const completion = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [
          {
            role: "system",
            content: withLanguage(MULTI_PART_SUMMARY_PROMPT, language),
          },
          { role: "user", content: userMessage },
        ],
        temperature: 0.3,
        max_tokens: 1600,
      });

      const answer = appendSourcesFooter(
        completion.choices[0].message.content ?? "",
        sources,
        language
      );
      return new Response(JSON.stringify({ answer, sourcesUsed: sources.length }), {
        headers: { ...CORS, "Content-Type": "application/json" },
      });
    }

    if (mode === "clinical_screen") {
      const message = body.message?.trim() ?? "";
      const imageUrl = sanitizeImageUrl(body.imageUrl);
      const bodyArea = body.bodyArea ?? "Consulta general";
      const { context, sources } = await fetchRagContext(
        supabase,
        `${bodyArea}\n${message}`,
        bodyArea
      );
      const userMessage = [
        `Zona afectada: ${bodyArea}`,
        `Descripción del paciente:\n${message || "(Foto de la lesión adjunta)"}`,
        imageUrl
          ? "Hay una foto de la lesión adjunta: incorpórala a la orientación según las reglas de foto."
          : "",
        athleteContext ? athleteContext : "",
        context
          ? `Información relevante de los documentos:\n${context}`
          : "(Responde con conocimientos generales de fisioterapia.)",
        buildFunctionalQuestionsPromptBlock(bodyArea),
      ]
        .filter(Boolean)
        .join("\n\n");

      const completion = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [
          {
            role: "system",
            content: withPatientConsultContext(
              withLanguage(
                withImageRules(CLINICAL_SCREEN_PROMPT, Boolean(imageUrl)),
                language
              ),
              body,
              language
            ),
          },
          { role: "user", content: buildUserContent(userMessage, imageUrl) },
        ],
        temperature: 0.3,
        max_tokens: 1600,
      });

      const answer = appendSourcesFooter(
        completion.choices[0].message.content ?? "",
        sources,
        language
      );
      return new Response(JSON.stringify({ answer, sourcesUsed: sources.length }), {
        headers: { ...CORS, "Content-Type": "application/json" },
      });
    }

    if (mode === "physio_chat") {
      const message = body.message?.trim() ?? "";
      const imageUrl = sanitizeImageUrl(body.imageUrl);
      if (!message && !imageUrl) {
        return new Response(JSON.stringify({ error: "message required" }), {
          status: 400,
          headers: { ...CORS, "Content-Type": "application/json" },
        });
      }

      const history: HistoryMessage[] = (body.conversationHistory ?? []).slice(-12);
      const { context, sources } = await fetchRagContext(supabase, message);

      const userMessage = [
        `Pregunta del fisioterapeuta:\n${message || "(Imagen clínica adjunta)"}`,
        imageUrl
          ? "El fisioterapeuta adjuntó una imagen: descríbela solo si aporta y responde en consecuencia."
          : "",
        physioEquipmentContext ? physioEquipmentContext : "",
        context
          ? `Información relevante de los documentos:\n${context}`
          : "(Responde con conocimientos clínicos de fisioterapia y medicina deportiva.)",
      ]
        .filter(Boolean)
        .join("\n\n");

      const completion = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [
          {
            role: "system",
            content: withLanguage(
              withImageRules(PHYSIO_CHAT_SYSTEM_PROMPT, Boolean(imageUrl)),
              language
            ),
          },
          ...history,
          { role: "user", content: buildUserContent(userMessage, imageUrl) },
        ],
        temperature: 0.2,
        max_tokens: 1400,
      });

      const answer = appendSourcesFooter(
        completion.choices[0].message.content ?? "",
        sources,
        language
      );
      return new Response(JSON.stringify({ answer, sourcesUsed: sources.length }), {
        headers: { ...CORS, "Content-Type": "application/json" },
      });
    }

    if (mode === "physio_report") {
      const {
        bodyArea = "",
        onsetType = "",
        painLevel = 0,
        hadTrauma = "No",
        description = "",
        symptomContext = "",
        patientSummary = "",
      } = body;

      const questionnaireText = [
        `Zona afectada: ${bodyArea}`,
        `Cómo empezó: ${onsetType}`,
        `Nivel de dolor: ${painLevel}/10`,
        `Traumatismo: ${hadTrauma}`,
        description ? `Información adicional: ${description}` : "",
        symptomContext ? `Detalles del caso (cuestionario / pruebas funcionales):\n${symptomContext}` : "",
      ]
        .filter(Boolean)
        .join("\n");

      const { context, sources } = await fetchRagContext(
        supabase,
        questionnaireText,
        bodyArea
      );

      const userMessage = [
        `Zona afectada: ${bodyArea}`,
        `Cuestionario recogido por la IA:\n${questionnaireText}`,
        athleteContext ? athleteContext : "",
        patientSummary
          ? `Informe ya entregado al paciente (base de partida, no lo contradigas sin justificarlo):\n${patientSummary}`
          : "",
        context
          ? `Información relevante de los documentos:\n${context}`
          : "(Responde con conocimientos generales de fisioterapia y medicina deportiva.)",
        buildFunctionalQuestionsPromptBlock(bodyArea),
      ]
        .filter(Boolean)
        .join("\n\n");

      const completion = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [
          {
            role: "system",
            content: withLanguage(PHYSIO_REPORT_SYSTEM_PROMPT, language),
          },
          { role: "user", content: userMessage },
        ],
        temperature: 0.3,
        max_tokens: 1700,
      });

      const answer = appendSourcesFooter(
        completion.choices[0].message.content ?? "",
        sources,
        language
      );
      return new Response(JSON.stringify({ answer, sourcesUsed: sources.length }), {
        headers: { ...CORS, "Content-Type": "application/json" },
      });
    }

    const {
      bodyArea = "",
      onsetType = "",
      painLevel = 0,
      hadTrauma = "No",
      description = "",
      symptomContext,
      conversationHistory,
    } = body;
    const imageUrl = sanitizeImageUrl(body.imageUrl);

    const isFollowUp = bodyArea === "seguimiento";

    const queryText = isFollowUp
      ? onsetType
      : [
          `Zona afectada: ${bodyArea}`,
          `Cómo empezó: ${onsetType}`,
          `Nivel de dolor: ${painLevel}/10`,
          `Traumatismo: ${hadTrauma}`,
          description ? `Información adicional: ${description}` : "",
          symptomContext ? `Detalles del caso:\n${symptomContext}` : "",
        ]
          .filter(Boolean)
          .join("\n");

    const { context, sources } = await fetchRagContext(
      supabase,
      queryText,
      isFollowUp ? "" : bodyArea
    );
    const systemPrompt = withPatientConsultContext(
      withLanguage(
        withImageRules(
          isFollowUp ? FOLLOW_UP_SYSTEM_PROMPT : INITIAL_SYSTEM_PROMPT,
          Boolean(imageUrl)
        ),
        language
      ),
      body,
      language
    );
    const history: HistoryMessage[] = conversationHistory ?? [];

    const userMessage = isFollowUp
      ? [
          athleteContext ? athleteContext : "",
          context ? `Información de referencia:\n${context}` : "",
          symptomContext
            ? `Contexto de la conversación (OBLIGATORIO respetar):\n${symptomContext}`
            : "",
          description && description !== onsetType
            ? `Detalle adicional: ${description}`
            : "",
          `Pregunta del paciente: ${onsetType || "(Foto de la lesión adjunta)"}`,
          imageUrl
            ? "Hay una foto adjunta en este mensaje: úsala para precisar la orientación."
            : "",
        ]
          .filter(Boolean)
          .join("\n\n")
      : [
          `Síntomas actuales:\n${queryText}`,
          imageUrl
            ? "Hay una foto de la lesión adjunta: incorpórala al razonamiento clínico según las reglas de foto (hallazgos visibles + relato + cuestionario)."
            : "",
          athleteContext ? athleteContext : "",
          context
            ? `Información relevante de los documentos:\n${context}`
            : "(No se encontró información específica en documentos. Responde con tus conocimientos generales de fisioterapia.)",
          buildFunctionalQuestionsPromptBlock(bodyArea),
        ]
          .filter(Boolean)
          .join("\n\n");

    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: systemPrompt },
        ...history,
        { role: "user", content: buildUserContent(userMessage, imageUrl) },
      ],
      temperature: isFollowUp ? 0.4 : 0.3,
      max_tokens: isFollowUp ? 900 : 1700,
    });

    const answer = appendSourcesFooter(
      completion.choices[0].message.content ?? "",
      sources,
      language
    );

    return new Response(JSON.stringify({ answer, sourcesUsed: sources.length }), {
      headers: { ...CORS, "Content-Type": "application/json" },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Internal server error";
    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: { ...CORS, "Content-Type": "application/json" },
    });
  }
});
