/**
 * Clinical validation battery for Kinora reasoning.
 * Difficulty: easy | intermediate | expert
 * Use for offline evals / golden cases. Expand toward ~100 scenarios.
 */

export type ValidationDifficulty = "easy" | "intermediate" | "expert";

export type ClinicalValidationCase = {
  id: string;
  difficulty: ValidationDifficulty;
  title: string;
  patientSays: string[];
  /** Wrong “obvious” diagnosis the model must avoid prioritizing */
  trapDiagnosis: string;
  /** Correct / priority orientation */
  trueOrientation: string;
  /** Must appear among top hypotheses or trigger correct action */
  mustConsider: string[];
  /** Immediate escalation if true */
  urgentReferral?: boolean;
  notes?: string;
};

export const CLINICAL_VALIDATION_BATTERY: ClinicalValidationCase[] = [
  // —— Intermediate / trap cases (from clinical notes) ——
  {
    id: "trap-01-c7-vs-epicondylitis",
    difficulty: "expert",
    title: "Radiculopatía C7 que parece epicondilitis",
    patientSays: [
      "Dolor en la cara lateral del codo",
      "Empeora al coger peso",
      "Hormigueo en dedo medio",
      "Dolor cervical",
      "Debilidad al extender el codo",
    ],
    trapDiagnosis: "Epicondilitis lateral",
    trueOrientation: "Radiculopatía C7 / origen cervical",
    mustConsider: ["C7", "cervical", "radiculopatía", "nervio"],
  },
  {
    id: "trap-02-hip-oa-as-knee",
    difficulty: "expert",
    title: "Coxartrosis que parece lesión de rodilla",
    patientSays: [
      "Dolor en la rodilla",
      "Radiografía de rodilla normal",
      "Cojera",
      "Dificultad para ponerse calcetines",
      "Rotación interna de cadera muy limitada",
    ],
    trapDiagnosis: "Lesión local de rodilla / menisco",
    trueOrientation: "Coxartrosis / origen cadera",
    mustConsider: ["cadera", "coxartrosis", "rotación interna"],
  },
  {
    id: "trap-03-femoral-neck-stress-fx",
    difficulty: "expert",
    title: "Fractura de estrés cuello femoral vs tendinitis psoas",
    patientSays: [
      "Corredor",
      "Dolor inguinal progresivo",
      "Dolor nocturno",
      "Empeora corriendo",
      "Salto monopodal imposible",
    ],
    trapDiagnosis: "Tendinitis del psoas",
    trueOrientation: "Fractura de estrés del cuello femoral",
    mustConsider: ["fractura de estrés", "cuello femoral", "imagen"],
    urgentReferral: true,
  },
  {
    id: "trap-04-avn-femoral-head",
    difficulty: "expert",
    title: "Necrosis avascular vs tendinopatía de cadera",
    patientSays: [
      "Dolor profundo de cadera",
      "Sin traumatismo",
      "Dolor nocturno",
      "Rotación interna muy dolorosa",
      "Fuerza conservada",
    ],
    trapDiagnosis: "Tendinopatía de cadera",
    trueOrientation: "Necrosis avascular de cabeza femoral",
    mustConsider: ["necrosis", "avascular", "cabeza femoral"],
  },
  {
    id: "trap-05-radial-tunnel-vs-tennis-elbow",
    difficulty: "expert",
    title: "Túnel radial vs epicondilitis",
    patientSays: [
      "Dolor lateral del codo",
      "No duele exactamente el epicóndilo",
      "Dolor más distal",
      "Debilidad al extender dedos",
      "No mejora con reposo",
    ],
    trapDiagnosis: "Epicondilitis lateral",
    trueOrientation: "Síndrome del túnel radial / compresión nervio radial",
    mustConsider: ["túnel radial", "nervio radial"],
  },
  {
    id: "trap-06-pin-syndrome",
    difficulty: "expert",
    title: "Neuropatía interóseo posterior (PIN)",
    patientSays: [
      "No hay dolor importante",
      "Incapacidad para extender dedos",
      "Muñeca ligeramente caída",
      "Sensibilidad normal",
    ],
    trapDiagnosis: "Lesión musculotendinosa inespecífica",
    trueOrientation: "Síndrome del interóseo posterior (PIN)",
    mustConsider: ["interóseo posterior", "PIN", "nervio radial"],
  },
  {
    id: "trap-07-tos-vs-rotator-cuff",
    difficulty: "expert",
    title: "Desfiladero torácico vs manguito",
    patientSays: [
      "Dolor de hombro",
      "Hormigueo en todo el brazo",
      "Empeora llevando mochila",
      "Empeora con brazos elevados",
      "Mano fría",
    ],
    trapDiagnosis: "Tendinopatía del manguito rotador",
    trueOrientation: "Síndrome del desfiladero torácico (TOS)",
    mustConsider: ["desfiladero", "TOS", "torácico"],
  },
  {
    id: "trap-08-slap-vs-cuff",
    difficulty: "intermediate",
    title: "SLAP vs manguito en lanzador",
    patientSays: [
      "Lanzador",
      "Chasquidos",
      "Dolor profundo",
      "Sensación de bloqueo",
      "Fuerza casi normal",
    ],
    trapDiagnosis: "Rotura/tendinopatía manguito",
    trueOrientation: "Lesión SLAP / labrum",
    mustConsider: ["SLAP", "labrum"],
  },
  {
    id: "trap-09-occult-scaphoid",
    difficulty: "intermediate",
    title: "Fractura de escafoides oculta",
    patientSays: [
      "Caída",
      "Radiografía normal",
      "Dolor en el valle de la base del pulgar",
      "Dolor al pellizcar",
      "Dolor axial del pulgar",
    ],
    trapDiagnosis: "Esguince de muñeca leve",
    trueOrientation: "Fractura de escafoides (posible oculta)",
    mustConsider: ["escafoides", "inmovilización", "imagen"],
  },
  {
    id: "trap-10-tarsal-tunnel-vs-plantar-fascia",
    difficulty: "expert",
    title: "Túnel tarsiano vs fascitis",
    patientSays: [
      "Ardor plantar",
      "Hormigueo",
      "Empeora por la noche",
      "Dolor medial del tobillo",
      "Tinel positivo",
    ],
    trapDiagnosis: "Fascitis plantar",
    trueOrientation: "Síndrome del túnel tarsiano / nervio tibial",
    mustConsider: ["túnel tarsiano", "tibial", "neuropatía"],
  },
  {
    id: "trap-11-s1-vs-plantar-fascia",
    difficulty: "expert",
    title: "Radiculopatía S1 vs fascitis",
    patientSays: [
      "Dolor plantar",
      "Hormigueo",
      "Dolor lumbar",
      "Debilidad de gemelo",
      "Reflejo aquíleo disminuido",
    ],
    trapDiagnosis: "Fascitis plantar",
    trueOrientation: "Radiculopatía S1",
    mustConsider: ["S1", "lumbar", "radiculopatía"],
  },
  {
    id: "trap-12-partial-achilles-tear",
    difficulty: "intermediate",
    title: "Rotura parcial de Aquiles vs tendinitis",
    patientSays: [
      "Chasquido",
      "Puede caminar",
      "Incapaz de elevación unilateral de talón",
      "Thompson dudoso",
      "Dolor localizado",
    ],
    trapDiagnosis: "Tendinitis de Aquiles",
    trueOrientation: "Rotura parcial del tendón de Aquiles",
    mustConsider: ["rotura", "Aquiles", "ecografía"],
  },
  {
    id: "trap-13-l4-vs-meniscus",
    difficulty: "expert",
    title: "Radiculopatía L4 vs menisco",
    patientSays: [
      "Dolor de rodilla",
      "Hormigueo cara medial",
      "Dolor lumbar",
      "Reflejo rotuliano disminuido",
    ],
    trapDiagnosis: "Lesión meniscal",
    trueOrientation: "Radiculopatía L4",
    mustConsider: ["L4", "lumbar", "radiculopatía"],
  },
  {
    id: "trap-14-pec-major-rupture",
    difficulty: "intermediate",
    title: "Rotura pectoral vs lesión de hombro",
    patientSays: [
      "Press banca",
      "Hematoma axilar",
      "Debilidad de aducción",
      "Hombro móvil",
    ],
    trapDiagnosis: "Lesión del manguito / hombro",
    trueOrientation: "Rotura del pectoral mayor",
    mustConsider: ["pectoral", "aducción", "hematoma"],
  },
  {
    id: "trap-15-mi-left-shoulder",
    difficulty: "expert",
    title: "IAM con dolor de hombro izquierdo",
    patientSays: [
      "Dolor hombro izquierdo",
      "No aumenta con movimiento",
      "Sudor frío",
      "Náuseas",
      "Dolor opresivo en el pecho",
    ],
    trapDiagnosis: "Lesión musculoesquelética de hombro",
    trueOrientation: "Sospecha de infarto / causa cardíaca",
    mustConsider: ["urgencias", "infarto", "cardíaco"],
    urgentReferral: true,
  },

  // —— Expert referred-pain / pattern bank (expand toward ~100) ——
  {
    id: "exp-knee-from-hip",
    difficulty: "expert",
    title: "Dolor de rodilla de origen cadera",
    patientSays: ["Me duele la rodilla", "También me cuesta cruzar la pierna", "Cojeo un poco"],
    trapDiagnosis: "Patología aislada de rodilla",
    trueOrientation: "Origen cadera / referido",
    mustConsider: ["cadera"],
  },
  {
    id: "exp-shoulder-from-neck",
    difficulty: "expert",
    title: "Dolor de hombro de origen cervical",
    patientSays: ["Me duele el hombro", "Hormigueo en el brazo", "Al girar la cabeza empeora"],
    trapDiagnosis: "Manguito rotador aislado",
    trueOrientation: "Origen cervical / radiculopatía",
    mustConsider: ["cuello", "cervical"],
  },
  {
    id: "exp-si-vs-lumbar",
    difficulty: "expert",
    title: "Dolor lumbar de origen sacroilíaco",
    patientSays: ["Dolor lumbar bajo", "Empeora al estar mucho rato sentado o al girarme en la cama", "Dolor hacia la nalga"],
    trapDiagnosis: "Lumbalgia mecánica inespecífica solo discogénica",
    trueOrientation: "Disfunción / dolor sacroilíaco",
    mustConsider: ["sacroilíaca"],
  },
  {
    id: "exp-piriformis",
    difficulty: "expert",
    title: "Dolor glúteo por piriforme / ciático proximal",
    patientSays: ["Dolor en el glúteo", "Hormigueo hacia la pierna", "Empeora sentado"],
    trapDiagnosis: "Solo contractura glútea banal",
    trueOrientation: "Compromiso ciático proximal / piriforme (orientativo)",
    mustConsider: ["ciático", "piriforme", "glúteo"],
  },
  {
    id: "exp-dvt-calf",
    difficulty: "expert",
    title: "TVP vs lesión muscular de pantorrilla",
    patientSays: [
      "Pantorrilla hinchada y caliente",
      "Dolor progresivo",
      "Sin chasquido claro al correr",
      "Viaje largo reciente",
    ],
    trapDiagnosis: "Rotura de gemelo / soleo",
    trueOrientation: "Sospecha de TVP — derivación urgente",
    mustConsider: ["TVP", "urgencias", "trombosis"],
    urgentReferral: true,
  },
  {
    id: "exp-cecs-vs-mtss",
    difficulty: "expert",
    title: "CECS vs periostitis tibial",
    patientSays: [
      "Dolor en la espinilla al correr",
      "Aparece siempre a la misma distancia",
      "Cede al parar",
      "Sensación de tensión/hinchazón muscular",
    ],
    trapDiagnosis: "Solo periostitis / shin splints",
    trueOrientation: "Síndrome compartimental crónico de esfuerzo (CECS) en DD",
    mustConsider: ["compartimental", "CECS"],
  },
  {
    id: "exp-vascular-claudication",
    difficulty: "expert",
    title: "Claudicación vascular vs ciática",
    patientSays: [
      "Dolor en piernas al caminar",
      "Para al detenerse",
      "Mejora en reposo de pie (no necesariamente al sentarse/flexionar)",
      "Factores de riesgo vascular",
    ],
    trapDiagnosis: "Ciática / estenosis solo neurogénica",
    trueOrientation: "Claudicación vascular en diagnóstico diferencial",
    mustConsider: ["vascular", "claudicación"],
  },
  {
    id: "exp-cervical-myelopathy",
    difficulty: "expert",
    title: "Mielopatía cervical incipiente",
    patientSays: [
      "Torpeza en las manos",
      "Inestabilidad al caminar",
      "Hormigueo bilateral",
      "Dolor de cuello",
    ],
    trapDiagnosis: "Cervicalgia mecánica simple",
    trueOrientation: "Sospecha de mielopatía — valoración urgente/especializada",
    mustConsider: ["mielopatía", "médula", "urgencia"],
    urgentReferral: true,
  },
  {
    id: "exp-inflammatory-vs-mechanical-lbp",
    difficulty: "expert",
    title: "Lumbalgia inflamatoria vs mecánica",
    patientSays: [
      "Dolor lumbar joven",
      "Rigidez matutina >45 min",
      "Mejora con actividad",
      "Empeora en reposo nocturno",
    ],
    trapDiagnosis: "Solo lumbalgia mecánica inespecífica",
    trueOrientation: "Patrón inflamatorio — cribado / derivación médica",
    mustConsider: ["inflamatorio", "espondilo", "médico"],
  },
  {
    id: "exp-diaphragm-scapular",
    difficulty: "expert",
    title: "Dolor escapular por irritación diafragmática / visceral",
    patientSays: [
      "Dolor bajo el omóplato",
      "Sin relación clara con movimiento del hombro",
      "Asociado a digestión o respiración profunda",
    ],
    trapDiagnosis: "Solo tendinopatía escapular / manguito",
    trueOrientation: "Dolor referido visceral / diafragmático en DD",
    mustConsider: ["referido", "visceral", "diafragma"],
  },
  {
    id: "exp-ulnar-vs-medial-epicondylitis",
    difficulty: "expert",
    title: "Neuropatía cubital vs epicondilitis medial",
    patientSays: [
      "Dolor medial de codo",
      "Hormigueo 4º-5º dedo",
      "Empeora apoyando el codo",
      "Debilidad de pinza",
    ],
    trapDiagnosis: "Solo epicondilitis medial",
    trueOrientation: "Neuropatía / irritación del nervio cubital",
    mustConsider: ["cubital", "nervio", "hormigueo"],
  },
  {
    id: "exp-stress-fx-normal-xray",
    difficulty: "expert",
    title: "Fractura por estrés con RX inicial normal",
    patientSays: [
      "Aumento brusco de carga en carrera",
      "Dolor óseo localizado progresivo",
      "Radiografía inicial normal",
      "Dolor al saltar a una pierna",
    ],
    trapDiagnosis: "Tendinopatía / periostitis banal",
    trueOrientation: "Fractura por estrés — no descartar por RX normal",
    mustConsider: ["fractura", "estrés", "imagen"],
    urgentReferral: true,
  },

  // —— Easy classic local presentations ——
  {
    id: "easy-01-lateral-ankle-sprain",
    difficulty: "easy",
    title: "Esguince lateral de tobillo",
    patientSays: ["Torcí el tobillo hacia dentro", "Hinchazón lateral", "Duele al apoyar"],
    trapDiagnosis: "Fractura necesariamente",
    trueOrientation: "Esguince lateral de tobillo (ligamentos laterales)",
    mustConsider: ["esguince", "ligamento", "lateral"],
  },
  {
    id: "easy-02-plantar-fasciitis",
    difficulty: "easy",
    title: "Fascitis plantar típica",
    patientSays: ["Dolor en talón al levantarme", "Mejora al caminar un poco", "Sin hormigueo", "Sin dolor lumbar"],
    trapDiagnosis: "Radiculopatía S1",
    trueOrientation: "Fascitis / fasciopatía plantar",
    mustConsider: ["fascia", "plantar", "talón"],
  },
  {
    id: "easy-03-lateral-epicondylitis",
    difficulty: "easy",
    title: "Epicondilitis lateral típica",
    patientSays: ["Dolor exactamente en el epicóndilo", "Empeora al agarrar", "Sin hormigueo", "Cuello bien"],
    trapDiagnosis: "Radiculopatía C7",
    trueOrientation: "Epicondilitis / tendinopatía extensores",
    mustConsider: ["epicóndilo", "extensores"],
  },
  {
    id: "easy-04-rotator-cuff-tendinopathy",
    difficulty: "easy",
    title: "Tendinopatía manguito típica",
    patientSays: ["Dolor al elevar el brazo", "Empeora de lado", "Sin hormigueo", "Cuello sin síntomas"],
    trapDiagnosis: "TOS / IAM",
    trueOrientation: "Tendinopatía del manguito rotador",
    mustConsider: ["manguito", "hombro"],
  },
  {
    id: "easy-05-patellar-tendinopathy",
    difficulty: "easy",
    title: "Tendinopatía rotuliana",
    patientSays: ["Dolor bajo la rótula", "Salto y aterrizaje", "Sin bloqueo", "Sin dolor lumbar"],
    trapDiagnosis: "Menisco / radiculopatía",
    trueOrientation: "Tendinopatía rotuliana / jumper's knee",
    mustConsider: ["tendón", "rótula"],
  },
  {
    id: "easy-06-acl-acute",
    difficulty: "easy",
    title: "LCA agudo típico",
    patientSays: ["Giro en fútbol", "Chasquido", "Hinchazón rápida", "Inestabilidad"],
    trapDiagnosis: "Solo contusión",
    trueOrientation: "Sospecha de lesión de LCA",
    mustConsider: ["LCA", "ligamento", "inestabilidad"],
  },
  {
    id: "easy-07-meniscus-typical",
    difficulty: "easy",
    title: "Menisco típico",
    patientSays: ["Dolor en línea articular", "Bloqueo ocasional", "Empeora al agacharme", "Sin síntomas lumbares"],
    trapDiagnosis: "Radiculopatía L4",
    trueOrientation: "Lesión meniscal orientativa",
    mustConsider: ["menisco", "bloqueo"],
  },
  {
    id: "easy-08-achilles-tendinopathy",
    difficulty: "easy",
    title: "Tendinopatía de Aquiles",
    patientSays: ["Dolor matutino en Aquiles", "Corredor", "Puede hacer elevación de talón", "Sin chasquido"],
    trapDiagnosis: "Rotura de Aquiles",
    trueOrientation: "Tendinopatía aquilea",
    mustConsider: ["Aquiles", "tendinopatía"],
  },
  {
    id: "easy-09-cervical-mechanical",
    difficulty: "easy",
    title: "Cervicalgia mecánica",
    patientSays: ["Cuello rígido al despertar", "Sin irradiación", "Sin torpeza de manos", "Sin inestabilidad al andar"],
    trapDiagnosis: "Mielopatía",
    trueOrientation: "Cervicalgia mecánica",
    mustConsider: ["cervical", "mecánica"],
  },
  {
    id: "easy-10-mechanical-lbp",
    difficulty: "easy",
    title: "Lumbalgia mecánica",
    patientSays: ["Me dolió al levantar peso", "Mejora en reposo relativo", "Sin fiebre", "Sin pérdida de fuerza ni esfínteres"],
    trapDiagnosis: "Causa inflamatoria / cauda equina",
    trueOrientation: "Lumbalgia mecánica",
    mustConsider: ["lumbar", "mecánica"],
  },
  {
    id: "easy-11-gtps",
    difficulty: "easy",
    title: "Dolor trocantéreo",
    patientSays: ["Dolor lateral de cadera", "Duele al dormir de ese lado", "Sin dolor inguinal profundo"],
    trapDiagnosis: "Necrosis avascular",
    trueOrientation: "Síndrome doloroso trocantéreo / glúteo medio",
    mustConsider: ["trocánter", "glúteo"],
  },
  {
    id: "easy-12-itf-band",
    difficulty: "easy",
    title: "Síndrome de la cintilla iliotibial",
    patientSays: ["Dolor lateral de rodilla al correr", "Aparece tras kilómetros", "Sin hinchazón"],
    trapDiagnosis: "Menisco lateral necesariamente",
    trueOrientation: "Cintilla iliotibial / ITBS",
    mustConsider: ["cintilla", "iliotibial"],
  },
  {
    id: "easy-13-dequervain",
    difficulty: "easy",
    title: "De Quervain",
    patientSays: ["Dolor base del pulgar", "Empeora al coger al bebé", "Sin caída reciente"],
    trapDiagnosis: "Fractura de escafoides",
    trueOrientation: "Tenosinovitis de De Quervain",
    mustConsider: ["De Quervain", "pulgar"],
  },
  {
    id: "easy-14-carpal-tunnel",
    difficulty: "easy",
    title: "Túnel carpiano típico",
    patientSays: ["Hormigueo 1-3 dedos", "Peor de noche", "Sacudo la mano"],
    trapDiagnosis: "Cervical exclusivamente",
    trueOrientation: "Síndrome del túnel carpiano",
    mustConsider: ["túnel carpiano", "mediano"],
  },
  {
    id: "easy-15-hamstring-strain",
    difficulty: "easy",
    title: "Distensión isquiotibial",
    patientSays: ["Sprint", "Tirón posterior de muslo", "Dolor al flexionar rodilla contra resistencia"],
    trapDiagnosis: "Ciática necesariamente",
    trueOrientation: "Lesión muscular isquiotibial",
    mustConsider: ["isquiotibial", "muscular"],
  },
  {
    id: "easy-16-adductor-strain",
    difficulty: "easy",
    title: "Lesión aductores",
    patientSays: ["Cambio de dirección", "Dolor en ingle al juntar piernas", "Sin dolor óseo nocturno"],
    trapDiagnosis: "Fractura de estrés cuello femoral",
    trueOrientation: "Lesión / tendinopatía de aductores",
    mustConsider: ["aductor", "ingle"],
  },
  {
    id: "easy-17-calf-strain",
    difficulty: "easy",
    title: "Rotura fibrilar de gemelo",
    patientSays: ["Chasquido en pantorrilla al empujar", "Hematoma", "Sin viaje largo", "Sin calor difuso marcado"],
    trapDiagnosis: "TVP",
    trueOrientation: "Lesión muscular de gemelo / soleo",
    mustConsider: ["gemelo", "muscular"],
  },
  {
    id: "easy-18-impingement-shoulder",
    difficulty: "easy",
    title: "Pinzamiento subacromial típico",
    patientSays: ["Arco doloroso 60-120º", "Trabajo overhead", "Sin síntomas vasculares ni cervicales"],
    trapDiagnosis: "TOS",
    trueOrientation: "Síndrome de pinzamiento / tendinopatía",
    mustConsider: ["pinzamiento", "subacromial"],
  },
  {
    id: "easy-19-pfps",
    difficulty: "easy",
    title: "Dolor patelofemoral",
    patientSays: ["Dolor delante de la rodilla", "Bajar escaleras", "Sentado mucho rato", "Sin bloqueo"],
    trapDiagnosis: "Menisco",
    trueOrientation: "Síndrome patelofemoral",
    mustConsider: ["patelofemoral", "rótula"],
  },
  {
    id: "easy-20-whiplash",
    difficulty: "easy",
    title: "Latigazo cervical",
    patientSays: ["Accidente de coche", "Cuello dolorido al día siguiente", "Sin déficit neurológico claro"],
    trapDiagnosis: "Mielopatía",
    trueOrientation: "Esguince / latigazo cervical",
    mustConsider: ["cervical", "latigazo"],
  },
  {
    id: "easy-21-shin-splints",
    difficulty: "easy",
    title: "Periostitis tibial típica",
    patientSays: ["Dolor difuso borde tibial", "Principiante en running", "Dolor al tacto largo del borde", "Sin tensión compartimental clara"],
    trapDiagnosis: "CECS necesariamente",
    trueOrientation: "Síndrome de estrés tibial medial / periostitis",
    mustConsider: ["tibial", "periostitis"],
  },
  {
    id: "easy-22-bursitis-olecranon",
    difficulty: "easy",
    title: "Bursitis olecraneana",
    patientSays: ["Hinchazón en punta del codo", "Apoyo repetido", "Movilidad casi completa"],
    trapDiagnosis: "Fractura de olécranon necesariamente",
    trueOrientation: "Bursitis del olécranon",
    mustConsider: ["bursa", "olécranon"],
  },
  {
    id: "easy-23-trigger-finger",
    difficulty: "easy",
    title: "Dedo en resorte",
    patientSays: ["Dedo se engancha al flexionar", "Chasquido al extender", "Nódulo en palma"],
    trapDiagnosis: "Fractura",
    trueOrientation: "Dedo en resorte / tenosinovitis estenosante",
    mustConsider: ["resorte", "tenosinovitis"],
  },
  {
    id: "easy-24-costochondritis",
    difficulty: "easy",
    title: "Costocondritis (no cardíaco)",
    patientSays: ["Dolor pecho reproducible a la palpación", "Joven", "Sin sudor frío ni náuseas", "Empeora con respiración profunda local"],
    trapDiagnosis: "IAM",
    trueOrientation: "Costocondritis / dolor musculoesquelético torácico",
    mustConsider: ["costocondritis", "reproducible"],
    notes: "Si hay síntomas vegetativos → no usar este caso; derivar",
  },
  {
    id: "easy-25-medial-epicondylitis",
    difficulty: "easy",
    title: "Epicondilitis medial típica",
    patientSays: ["Dolor en epicóndilo medial", "Golf / agarre", "Sin hormigueo cubital"],
    trapDiagnosis: "Neuropatía cubital",
    trueOrientation: "Epicondilitis medial",
    mustConsider: ["epicóndilo medial", "flexores"],
  },
  {
    id: "easy-26-ac-joint",
    difficulty: "easy",
    title: "Articulación acromioclavicular",
    patientSays: ["Dolor encima del hombro", "Press banca", "Dolor al cruzar el brazo"],
    trapDiagnosis: "Manguito necesariamente",
    trueOrientation: "Artropatía / esguince AC",
    mustConsider: ["acromioclavicular", "AC"],
  },
  {
    id: "easy-27-osgood",
    difficulty: "easy",
    title: "Osgood-Schlatter adolescente",
    patientSays: ["Adolescente", "Dolor tuberosidad tibial", "Deporte de salto"],
    trapDiagnosis: "LCA",
    trueOrientation: "Osgood-Schlatter / apofisitis",
    mustConsider: ["Osgood", "tuberosidad"],
  },
  {
    id: "easy-28-sever",
    difficulty: "easy",
    title: "Sever infantil",
    patientSays: ["Niño", "Dolor talón tras deporte", "Sin hormigueo"],
    trapDiagnosis: "Fascitis adulta típica",
    trueOrientation: "Enfermedad de Sever / apofisitis calcánea",
    mustConsider: ["Sever", "calcáneo"],
  },
  {
    id: "easy-29-lumbar-disc-sciatica",
    difficulty: "easy",
    title: "Ciática típica L5-S1",
    patientSays: ["Dolor lumbar", "Irradia a pierna", "Hormigueo", "Empeora al sentarme"],
    trapDiagnosis: "Solo contractura glútea",
    trueOrientation: "Radiculopatía / ciática",
    mustConsider: ["ciática", "radiculopatía", "lumbar"],
  },
  {
    id: "easy-30-wrist-sprain",
    difficulty: "easy",
    title: "Esguince de muñeca sin signos de escafoides",
    patientSays: ["Caída leve", "Dolor dorsal difuso", "Sin dolor en tabaquera", "Sin dolor axial del pulgar"],
    trapDiagnosis: "Escafoides necesariamente",
    trueOrientation: "Esguince de muñeca (bajo sospecha ósea)",
    mustConsider: ["esguince", "muñeca"],
  },

  // —— Intermediate ——
  {
    id: "int-01-acl-vs-meniscus",
    difficulty: "intermediate",
    title: "LCA + menisco posible",
    patientSays: ["Giro", "Chasquido", "Hinchazón", "Ahora a veces bloquea"],
    trapDiagnosis: "Solo contusión",
    trueOrientation: "LCA ± menisco en DD",
    mustConsider: ["LCA", "menisco"],
  },
  {
    id: "int-02-high-ankle-sprain",
    difficulty: "intermediate",
    title: "Esguince sindesmosis",
    patientSays: ["Rotación externa forzada", "Dolor arriba de la mortaja", "Dolor al comprimir tibio-peroné"],
    trapDiagnosis: "Esguince lateral simple",
    trueOrientation: "Lesión de sindesmosis / tobillo alto",
    mustConsider: ["sindesmosis", "alto"],
  },
  {
    id: "int-03-hip-labrum",
    difficulty: "intermediate",
    title: "Labrum / FAI sospechoso",
    patientSays: ["Dolor inguinal profundo", "Chasquido", "Empeora sentado", "Joven activo"],
    trapDiagnosis: "Solo aductor",
    trueOrientation: "Pinzamiento / labrum de cadera en DD",
    mustConsider: ["labrum", "pinzamiento", "cadera"],
  },
  {
    id: "int-04-bankart-instability",
    difficulty: "intermediate",
    title: "Inestabilidad glenohumeral",
    patientSays: ["Luxación previa", "Miedo al lanzar", "Sensación de que se sale"],
    trapDiagnosis: "Solo tendinopatía",
    trueOrientation: "Inestabilidad glenohumeral / Bankart en DD",
    mustConsider: ["inestabilidad", "luxación"],
  },
  {
    id: "int-05-tfcc",
    difficulty: "intermediate",
    title: "TFCC",
    patientSays: ["Dolor cubital de muñeca", "Carga en extensión", "Chasquido cubital"],
    trapDiagnosis: "Solo esguince inespecífico",
    trueOrientation: "Lesión TFCC orientativa",
    mustConsider: ["TFCC", "cubital"],
  },
  {
    id: "int-06-peroneal-tendon",
    difficulty: "intermediate",
    title: "Tendones peroneos",
    patientSays: ["Dolor retro-maleolar lateral", "Sensación de inestabilidad", "Tras esguinces de repetición"],
    trapDiagnosis: "Solo esguince agudo nuevo",
    trueOrientation: "Tendinopatía / inestabilidad peronea",
    mustConsider: ["peroneo"],
  },
  {
    id: "int-07-proximal-hamstring",
    difficulty: "intermediate",
    title: "Isquiotibial proximal",
    patientSays: ["Dolor en isquion", "Sprint o split", "Duele al sentarme"],
    trapDiagnosis: "Solo ciática",
    trueOrientation: "Tendinopatía / lesión isquiotibial proximal",
    mustConsider: ["isquion", "isquiotibial"],
  },
  {
    id: "int-08-gluteus-medius-tear",
    difficulty: "intermediate",
    title: "Glúteo medio vs bursitis",
    patientSays: ["Dolor trocantéreo", "Debilidad al abducir", "Trendelenburg"],
    trapDiagnosis: "Solo bursitis",
    trueOrientation: "Tendinopatía / rotura parcial glúteo medio en DD",
    mustConsider: ["glúteo medio", "abducción"],
  },
  {
    id: "int-09-mcl",
    difficulty: "intermediate",
    title: "LCM",
    patientSays: ["Valgo forzado", "Dolor cara medial rodilla", "Sin bloqueo"],
    trapDiagnosis: "Menisco medial necesariamente",
    trueOrientation: "Lesión del LCM",
    mustConsider: ["LCM", "medial"],
  },
  {
    id: "int-10-lcl-plc",
    difficulty: "intermediate",
    title: "Lateral / esquina posterolateral",
    patientSays: ["Varo + hiperextensión", "Inestabilidad lateral", "Dolor posterolateral"],
    trapDiagnosis: "Solo menisco lateral",
    trueOrientation: "LCL / esquina posterolateral en DD",
    mustConsider: ["LCL", "posterolateral"],
  },
  {
    id: "int-11-jones-fracture",
    difficulty: "intermediate",
    title: "Fractura 5º metatarsiano",
    patientSays: ["Dolor base 5º metatarsiano", "Tras inversión", "Apoyo doloroso localizado óseo"],
    trapDiagnosis: "Solo esguince",
    trueOrientation: "Fractura de 5º metatarsiano / Jones en DD",
    mustConsider: ["metatarsiano", "fractura"],
  },
  {
    id: "int-12-navicular-stress",
    difficulty: "intermediate",
    title: "Estrés del navicular",
    patientSays: ["Corredor", "Dolor dorso-medial mediopié", "Progresivo", "RX puede ser normal"],
    trapDiagnosis: "Esguince de mediopié banal",
    trueOrientation: "Fractura de estrés del navicular",
    mustConsider: ["navicular", "estrés"],
    urgentReferral: true,
  },
  {
    id: "int-13-lisfranc",
    difficulty: "intermediate",
    title: "Lisfranc",
    patientSays: ["Caída sobre pie en punta", "Hematoma plantar", "Dolor mediopié al cargar"],
    trapDiagnosis: "Esguince banal de pie",
    trueOrientation: "Lesión de Lisfranc — derivación / imagen",
    mustConsider: ["Lisfranc", "mediopié"],
    urgentReferral: true,
  },
  {
    id: "int-14-quad-tendon",
    difficulty: "intermediate",
    title: "Tendón cuadricipital",
    patientSays: ["Caída al intentar extender rodilla", "Hueco supra-rotuliano", "No puede extender activa"],
    trapDiagnosis: "Contusión de cuádriceps",
    trueOrientation: "Rotura de tendón cuadricipital",
    mustConsider: ["cuádriceps", "tendón", "extensión"],
    urgentReferral: true,
  },
  {
    id: "int-15-patellar-tendon-rupture",
    difficulty: "intermediate",
    title: "Rotura tendón rotuliano",
    patientSays: ["Chasquido infra-rotuliano", "Rótula alta", "No puede extender"],
    trapDiagnosis: "Tendinopatía",
    trueOrientation: "Rotura del tendón rotuliano",
    mustConsider: ["tendón rotuliano", "rotura"],
    urgentReferral: true,
  },
  {
    id: "int-16-biceps-proximal",
    difficulty: "intermediate",
    title: "Cabeza larga del bíceps / Popeye",
    patientSays: ["Tirón al levantar", "Bulto en brazo", "Dolor anterior de hombro"],
    trapDiagnosis: "Manguito necesariamente",
    trueOrientation: "Rotura proximal de bíceps / cabeza larga",
    mustConsider: ["bíceps", "Popeye"],
  },
  {
    id: "int-17-distal-biceps",
    difficulty: "intermediate",
    title: "Bíceps distal",
    patientSays: ["Curl con peso", "Chasquido en codo", "Debilidad de supinación", "Hematoma antebrazo"],
    trapDiagnosis: "Epicondilitis",
    trueOrientation: "Rotura distal de bíceps",
    mustConsider: ["bíceps distal", "supinación"],
    urgentReferral: true,
  },
  {
    id: "int-18-pronator-syndrome",
    difficulty: "intermediate",
    title: "Síndrome del pronador",
    patientSays: ["Dolor antebrazo proximal", "Hormigueo estilo mediano", "Empeora con pronación repetida"],
    trapDiagnosis: "Solo túnel carpiano",
    trueOrientation: "Síndrome del pronador / mediano proximal en DD",
    mustConsider: ["pronador", "mediano"],
  },
  {
    id: "int-19-cubital-tunnel",
    difficulty: "intermediate",
    title: "Túnel cubital",
    patientSays: ["Hormigueo 4-5", "Empeora con flexión prolongada de codo", "Debilidad intrínseca"],
    trapDiagnosis: "Epicondilitis medial",
    trueOrientation: "Síndrome del túnel cubital",
    mustConsider: ["túnel cubital", "cubital"],
  },
  {
    id: "int-20-frozen-shoulder",
    difficulty: "intermediate",
    title: "Hombro congelado",
    patientSays: ["Pérdida global de movilidad", "Dolor nocturno", "Diabetes", "Sin trauma claro"],
    trapDiagnosis: "Solo manguito",
    trueOrientation: "Capsulitis adhesiva / hombro congelado",
    mustConsider: ["congelado", "capsulitis"],
  },
  {
    id: "int-21-spondylolysis",
    difficulty: "intermediate",
    title: "Espondilólisis en joven deportista",
    patientSays: ["Adolescente", "Extensión lumbar dolorosa", "Gimnasia / fútbol", "Dolor unilateral"],
    trapDiagnosis: "Solo contractura",
    trueOrientation: "Espondilólisis / estrés del istmo en DD",
    mustConsider: ["espondilólisis", "istmo"],
  },
  {
    id: "int-22-cauda-equina",
    difficulty: "intermediate",
    title: "Cola de caballo (red flag)",
    patientSays: ["Lumbociática bilateral", "Anestesia en silla de montar", "Retención urinaria"],
    trapDiagnosis: "Ciática banal",
    trueOrientation: "Sospecha de cola de caballo — URGENCIAS",
    mustConsider: ["cola de caballo", "urgencias"],
    urgentReferral: true,
  },
  {
    id: "int-23-infection-red-flag",
    difficulty: "intermediate",
    title: "Infección / discitis sospecha",
    patientSays: ["Dolor lumbar", "Fiebre", "Antecedente de cirugía reciente", "No mejora con reposo"],
    trapDiagnosis: "Lumbalgia mecánica",
    trueOrientation: "Red flag infecciosa — derivación urgente",
    mustConsider: ["infección", "fiebre", "urgencias"],
    urgentReferral: true,
  },
  {
    id: "int-24-tumor-red-flag",
    difficulty: "intermediate",
    title: "Red flag oncológica",
    patientSays: ["Dolor nocturno constante", "Pérdida de peso", "Antecedente de cáncer", "Dolor no mecánico"],
    trapDiagnosis: "Contractura",
    trueOrientation: "Red flag — valoración médica urgente",
    mustConsider: ["cáncer", "red flag", "médico"],
    urgentReferral: true,
  },
  {
    id: "int-25-compartment-acute",
    difficulty: "intermediate",
    title: "Síndrome compartimental agudo",
    patientSays: ["Tras fractura / contusión grave", "Dolor desproporcionado", "Tensión del compartimento", "Parestesias"],
    trapDiagnosis: "Contusión muscular",
    trueOrientation: "Compartimental agudo — URGENCIAS",
    mustConsider: ["compartimental", "urgencias"],
    urgentReferral: true,
  },
  {
    id: "int-26-ottawa-ankle",
    difficulty: "intermediate",
    title: "Criterios Ottawa — imagen",
    patientSays: ["Esguince", "No puede dar 4 pasos", "Dolor óseo en maléolo"],
    trapDiagnosis: "Esguince sin imagen siempre",
    trueOrientation: "Indicación de radiografía / valoración",
    mustConsider: ["radiografía", "Ottawa", "óseo"],
  },
  {
    id: "int-27-shoulder-fracture",
    difficulty: "intermediate",
    title: "Fractura proximal de húmero sospecha",
    patientSays: ["Caída en anciano", "Impotencia funcional marcada", "Hematoma", "Dolor óseo"],
    trapDiagnosis: "Solo manguito",
    trueOrientation: "Fractura proximal de húmero en DD",
    mustConsider: ["fractura", "húmero", "imagen"],
    urgentReferral: true,
  },
  {
    id: "int-28-hip-fracture",
    difficulty: "intermediate",
    title: "Fractura de cadera anciano",
    patientSays: ["Caída", "Anciano", "No puede apoyar", "Pierna acortada/rotada"],
    trapDiagnosis: "Contusión",
    trueOrientation: "Fractura de cadera — URGENCIAS",
    mustConsider: ["fractura", "cadera", "urgencias"],
    urgentReferral: true,
  },
  {
    id: "int-29-concussion-neck",
    difficulty: "intermediate",
    title: "Conmoción + cervical post-impacto",
    patientSays: ["Golpe en la cabeza en deporte", "Mareo", "Cuello dolorido", "Confusión breve"],
    trapDiagnosis: "Solo cervicalgia",
    trueOrientation: "Conmoción cerebral en DD — protocolo médico",
    mustConsider: ["conmoción", "médico"],
    urgentReferral: true,
  },
  {
    id: "int-30-rib-stress",
    difficulty: "intermediate",
    title: "Fractura costal de estrés (remero)",
    patientSays: ["Remo / tenis", "Dolor costal localizado", "Empeora con tos y rotación"],
    trapDiagnosis: "Solo contractura intercostal",
    trueOrientation: "Fractura costal de estrés en DD",
    mustConsider: ["costal", "estrés"],
  },
  {
    id: "int-31-mtss-vs-stress-fx-tibia",
    difficulty: "intermediate",
    title: "Estrés tibial vs periostitis",
    patientSays: ["Dolor focal tibia", "Progresivo", "Dolor nocturno", "Salto doloroso"],
    trapDiagnosis: "Solo periostitis",
    trueOrientation: "Fractura de estrés tibial en DD",
    mustConsider: ["estrés", "tibial", "fractura"],
  },
  {
    id: "int-32-posterior-tibial",
    difficulty: "intermediate",
    title: "Disfunción tibial posterior",
    patientSays: ["Dolor medial de tobillo", "Pie que se aplana", "Debilidad al invertir"],
    trapDiagnosis: "Fascitis únicamente",
    trueOrientation: "Disfunción del tibial posterior",
    mustConsider: ["tibial posterior"],
  },
  {
    id: "int-33-sesamoiditis",
    difficulty: "intermediate",
    title: "Sesamoiditis / estrés sesamoideo",
    patientSays: ["Dolor bajo 1er metatarsiano", "Bailarina / corredor", "Dolor al despegue"],
    trapDiagnosis: "Fascitis",
    trueOrientation: "Sesamoiditis / estrés sesamoideo",
    mustConsider: ["sesamoideo"],
  },
  {
    id: "int-34-snapping-hip",
    difficulty: "intermediate",
    title: "Cadera en resorte",
    patientSays: ["Chasquido lateral o anterior de cadera", "Bailarina", "Sin dolor óseo nocturno"],
    trapDiagnosis: "Necrosis avascular",
    trueOrientation: "Snapping hip / cadera en resorte",
    mustConsider: ["resorte", "snapping"],
  },
  {
    id: "int-35-iliopsoas-tendinopathy",
    difficulty: "intermediate",
    title: "Tendinopatía psoas (sin red flags óseas)",
    patientSays: ["Dolor inguinal al flexionar", "Sin dolor nocturno", "Salto monopodal posible", "No corredor de alto volumen reciente"],
    trapDiagnosis: "Fractura cuello femoral necesariamente",
    trueOrientation: "Tendinopatía del iliopsoas (baja sospecha ósea)",
    mustConsider: ["psoas", "iliopsoas"],
  },
];

export function validationBatteryStats() {
  const by: Record<ValidationDifficulty, number> = {
    easy: 0,
    intermediate: 0,
    expert: 0,
  };
  for (const c of CLINICAL_VALIDATION_BATTERY) by[c.difficulty] += 1;
  return {
    total: CLINICAL_VALIDATION_BATTERY.length,
    byDifficulty: by,
    target: 100,
    remaining: Math.max(0, 100 - CLINICAL_VALIDATION_BATTERY.length),
  };
}
