#!/usr/bin/env python3
"""Kinora Ankle AI Orientation PDF (Part 10). Output: knowledge/Kinora_Ankle_AI_Orientation.pdf"""
from __future__ import annotations
import sys
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
from _kinora_pdf_common import (  # noqa: E402
    RA, RB, RC, add_record, add_section, build_styles, esc, make_footer,
)
from reportlab.lib.units import inch
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer

OUTPUT_PATH = SCRIPT_DIR.parent / "knowledge" / "Kinora_Ankle_AI_Orientation.pdf"
REF = f"{RA} {RB} {RC}"


def bone(id_, name, landmarks, artic, musc, lig, blood, inn, oss, bio, clin, img):
    return (name, {
        "ID": id_, "Bone": name, "Landmarks": landmarks, "Articulations": artic,
        "Muscle Attachments": musc, "Ligament Attachments": lig, "Blood Supply": blood,
        "Innervation": inn, "Ossification": oss, "Biomechanics": bio,
        "Clinical Importance": clin, "Imaging": img, "References": REF,
    })


BONES = [
    bone("ANK-BONE-01", "Talus",
         "Head, neck, body; trochlea; lateral/medial/posterior processes; sulcus tali; sinus tarsi contribution",
         "Tibia/fibula (talocrural); calcaneus (subtalar); navicular (talonavicular)",
         "No direct muscle attachments — unique among tarsals; ligamentous only",
         "ATFL, PTFL, CFL (via calcaneus link), deltoid components, interosseous talocalcaneal, spring ligament supports head",
         "Posterior tibial, anterior tibial, fibular anastomoses — vulnerable watershed at neck (AVN risk)",
         "Deep peroneal, tibial articular branches",
         "Primary center in utero; ossifies early; accessory os trigonum common posterior",
         "Keystone of ankle mortise and STJ; transmits tibial load to calcaneus/forefoot; 3D motion hinge",
         "Osteochondral lesions (OLT); talar neck fracture AVN risk (Hawkins); os trigonum posterior impingement; lateral process snowboarder's fracture",
         "XR AP/mortise/lateral; CT fracture mapping; MRI cartilage/AVN/OCD"),
    bone("ANK-BONE-02", "Calcaneus",
         "Tuberosity, sustentaculum tali, anterior process, facets (ant/mid/post), calcaneal sulcus, peroneal trochlea",
         "Talus (STJ); cuboid (calcaneocuboid)",
         "Achilles to tuberosity; abductor hallucis/FDB/ADM origins; quadratus plantae; extensor digitorum brevis (dorsal)",
         "CFL, spring (sustentaculum), long/short plantar, interosseous talocalcaneal, lateral/medial talocalcaneal",
         "Posterior tibial, fibular, medial/lateral plantar branches; rich periosteal supply",
         "Medial/lateral plantar, sural, tibial articular",
         "Ossifies mid-fetal life; apophysis (Sever disease site) fuses adolescence",
         "Accepts majority of talar load; lever for Achilles; STJ facets guide inversion/eversion",
         "Calcaneal fracture (Bohler/Gissane angles); plantar fasciopathy origin; Sever apophysitis; Haglund deformity",
         "XR lateral/axial Harris; CT trauma; MRI fasciopathy/Haglund"),
    bone("ANK-BONE-03", "Distal Tibia",
         "Medial malleolus, plafond (pilon), Chaput tubercle (AITFL), Tillaux region (adolescents), posterior malleolus (Volkmann)",
         "Talus (plafond/medial malleolus); fibula (syndesmosis)",
         "None major at plafond; TP/FDL/FHL tendons posterior; TA anterior",
         "Deltoid to medial malleolus; AITFL/PITFL/interosseous syndesmosis; ankle capsule",
         "Anterior/posterior tibial, malleolar anastomoses",
         "Saphenous (medial), deep peroneal articular, tibial",
         "Distal tibial physis — Tillaux/triplane fracture patterns in adolescents",
         "Forms medial/superior mortise; plafond cartilage critical; length/rotation affect talar congruence",
         "Pilon fracture; medial malleolus fracture; syndesmotic avulsions; ankle OA after malunion",
         "XR AP/mortise/lateral; CT articular; MRI ligaments"),
    bone("ANK-BONE-04", "Distal Fibula",
         "Lateral malleolus, malleolar fossa, Wagstaffe tubercle (AITFL)",
         "Talus laterally; tibia via syndesmosis",
         "Peroneus longus/brevis posterior; FHL nearby",
         "ATFL, CFL, PTFL; AITFL/PITFL; superior peroneal retinaculum",
         "Fibular artery malleolar branches; peroneal perforators",
         "Superficial/deep peroneal, sural articular",
         "Distal fibular physis — common pediatric ankle fracture site",
         "Lateral mortise wall; length restores lateral talar constraint (Weber/Lauge-Hansen)",
         "Weber A/B/C fractures; Maisonneuve association; ligament avulsions",
         "Full-length tib-fib if Maisonneuve suspected; mortise view clear space"),
    bone("ANK-BONE-05", "Navicular",
         "Tuberosity (TP insertion), articular facets for talus and cuneiforms",
         "Talus, three cuneiforms, occasionally cuboid",
         "Tibialis posterior primary; spring ligament complex support",
         "Spring (plantar calcaneonavicular), dorsal talonavicular, cuneonavicular ligaments",
         "Dorsalis pedis branches; medial plantar",
         "Deep peroneal, medial plantar",
         "Ossifies ~age 3; accessory navicular (os tibiale externum) common medial",
         "Keystone medial longitudinal arch; TP inserts — PTTD critical",
         "Navicular stress fracture (high-risk); accessory navicular syndrome; Kohler disease (pediatric osteochondrosis)",
         "XR AP/oblique/lateral; MRI stress; CT nonunion"),
    bone("ANK-BONE-06", "Cuboid",
         "Peroneal groove (PL tendon); calcaneal and metatarsal facets",
         "Calcaneus, lateral cuneiform, MT4-5, occasionally navicular",
         "Peroneus longus groove; FHB origins nearby; EDB",
         "Long/short plantar, calcaneocuboid, cuboideonavicular, TMT ligaments",
         "Lateral tarsal / arcuate artery branches",
         "Lateral plantar, sural, deep peroneal",
         "Ossifies ~age 9 prenatal/early — primary center early childhood",
         "Lateral column stability; PL mechanical advantage under cuboid",
         "Cuboid syndrome (subluxation concept); fracture; PL tendinopathy at groove",
         "XR oblique; MRI/US PL; clinical cuboid whip assessment"),
    bone("ANK-BONE-07", "Medial Cuneiform",
         "Largest cuneiform; PL and TA insertions; 1st TMT base",
         "Navicular, intermediate cuneiform, 1st MT, occasionally 2nd MT",
         "Tibialis anterior, peroneus longus, partially FHB",
         "Lisfranc complex medial; intercuneiform; cuneonavicular",
         "Dorsal/plantar arterial network",
         "Deep peroneal, medial plantar",
         "Ossifies ~age 2",
         "Medial column; 1st ray stability; TA/PL force couple at medial cuneiform",
         "Lisfranc injury medial; 1st TMT OA; bunion surgery osteotomies involve region",
         "Weight-bearing XR; CT Lisfranc"),
    bone("ANK-BONE-08", "Intermediate Cuneiform",
         "Smallest cuneiform; recessed — keystone of transverse arch",
         "Navicular, medial/lateral cuneiforms, 2nd MT",
         "Minimal direct; interossei nearby",
         "Lisfranc ligament attaches from medial cuneiform to 2nd MT base — critical",
         "Dorsal arterial network",
         "Deep peroneal, plantar nerves",
         "Ossifies ~age 3",
         "Recessed position locks 2nd MT — Lisfranc stability cornerstone",
         "Lisfranc ligament injury — subtle diastasis 1st-2nd MT",
         "WB XR with comparison; CT/MRI Lisfranc"),
    bone("ANK-BONE-09", "Lateral Cuneiform",
         "Articulates cuboid and 3rd MT",
         "Navicular, intermediate cuneiform, cuboid, 3rd MT",
         "FHB / adductor related plantar; interossei",
         "Intercuneiform, TMT, cuboideocuneiform ligaments",
         "Arcuate / lateral tarsal branches",
         "Deep peroneal, lateral plantar",
         "Ossifies ~age 1",
         "Lateral midfoot column; TMT stability",
         "Lisfranc lateral column; midfoot sprain/OA",
         "WB XR midfoot series; CT"),
]


def joint(id_, name, typ, cap, surf, ligs, blood, inn, arthro, osteo, dof, stab, bio, tests, pain, path, rehab):
    return (name, {
        "ID": id_, "Joint": name, "Type": typ, "Capsule": cap, "Articular Surfaces": surf,
        "Ligaments": ligs, "Blood Supply": blood, "Innervation": inn,
        "Arthrokinematics": arthro, "Osteokinematics": osteo, "Degrees of Freedom": dof,
        "Stability": stab, "Biomechanics": bio, "Clinical Tests": tests, "Pain Referral": pain,
        "Common Pathologies": path, "Rehabilitation": rehab, "References": REF,
    })


JOINTS = [
    joint("ANK-JNT-01", "Talocrural Joint",
          "Synovial hinge (ginglymus) — primarily sagittal DF/PF with coupled minor rotation",
          "Capsule thin anterior/posterior; reinforced by collaterals medially/laterally",
          "Tibial plafond + malleoli with talar trochlea (wider anteriorly)",
          "ATFL, CFL, PTFL laterally; deltoid medially; syndesmosis proximally related",
          "Malleolar arterial anastomosis",
          "Deep peroneal, tibial, saphenous, sural articular branches",
          "Convex talus rolls/glides on concave tibia — DF: posterior glide of talus; PF: anterior glide (open chain)",
          "DF ~20 deg; PF ~50 deg typical (individual); slight ABD/ADD and rotation coupled",
          "Primarily 1 DOF (DF/PF) with accessory motions",
          "Bony mortise congruence + ligaments; most stable in DF (wider anterior talus)",
          "Primary sagittal ankle rocker in gait; high compressive loads in run/jump",
          "Anterior drawer, talar tilt, ROM DF/PF knee flexed/extended (Silfverskiöld for gastroc)",
          "Anterior/lateral/medial ankle; may refer to midfoot",
          "Lateral sprain, OA, impingement, OLT, fracture-dislocation",
          "POLICE/PEACE&LOVE early; restore DF; progressive strength/balance; Ottawa rules for imaging"),
    joint("ANK-JNT-02", "Subtalar Joint",
          "Synovial plane/compound (anterior and posterior articulations) — triplanar motion",
          "Capsule + interosseous talocalcaneal ligament in sinus tarsi",
          "Talar facets on calcaneal posterior/middle/anterior facets",
          "Interosseous talocalcaneal, cervical, CFL (stabilizes STJ laterally), deltoid deep fibers, spring supports talar head",
          "Posterior tibial / fibular branches to sinus tarsi",
          "Tibial, deep peroneal articular",
          "Screw-like motion of talus on calcaneus; open-chain calcaneal INV/EV; closed-chain tibial rotation coupling",
          "Inversion ~20 deg / eversion ~10 deg approximate total STJ contribution",
          "1 primary functional DOF along oblique axis (triplanar pronation/supination)",
          "Interosseous ligament + CFL + bony facets; sinus tarsi stability",
          "Converts tibial rotation to foot pronation/supination; shock absorption early stance",
          "Talar tilt (also TC), STJ medial/lateral glide, Coleman block for cavovarus workup",
          "Sinus tarsi / lateral hindfoot pain common",
          "Sinus tarsi syndrome, STJ OA, coalition, calcaneal fracture malunion",
          "Restore INV/EV control; TP/fibularis balance; proprioception"),
    joint("ANK-JNT-03", "Distal Tibiofibular Syndesmosis",
          "Fibrous syndesmosis (amphiarthrosis) with synovial recess superiorly variable",
          "Not a classic capsule — ligaments + interosseous membrane",
          "Convex fibula against concave tibial fibular notch",
          "AITFL, PITFL, interosseous ligament/membrane, inferior transverse ligament",
          "Peroneal / anterior tibial perforators",
          "Deep peroneal, tibial articular",
          "Slight fibular translation/ER with DF to accommodate wide anterior talus",
          "Minimal osteokinematic motion — essential for mortise flexibility",
          "Accessory micromotion (not primary DOF)",
          "Ligamentous complex critical — disruption widens mortise and destabilizes talus",
          "Maintains mortise integrity under ER/DF load; high ankle sprain mechanism",
          "Squeeze, ER stress, Cotton, crossed-leg; syndesmosis tenderness",
          "Anterolateral ankle above joint line",
          "High ankle sprain; Maisonneuve; chronic instability/OA if missed",
          "Longer protection than lateral sprain; progressive DF/ER loading; surgery if unstable diastasis"),
    joint("ANK-JNT-04", "Talonavicular Joint",
          "Synovial ball-and-socket–like (part of acetabulum pedis / TN-CC complex)",
          "Capsule continuous with midfoot",
          "Talar head with navicular concavity",
          "Spring ligament (plantar support), dorsal talonavicular, bifurcate, deltoid tibionavicular",
          "Dorsalis pedis / medial plantar branches",
          "Deep peroneal, medial plantar",
          "Large mobility — key to midfoot adaptability; TN motion major in foot pronation/supination",
          "Triplanar midfoot motion contribution",
          "Multiplanar — functionally linked to STJ (acetabulum pedis)",
          "Spring ligament + TP tendon dynamic support of talar head",
          "Medial column motion; failure → adult-acquired flatfoot with PTTD/spring attenuation",
          "Single heel rise (TP), too-many-toes, navicular drop",
          "Medial midfoot / arch",
          "PTTD, spring ligament tear, TN OA, Kohler/accessory navicular",
          "Arch support orthoses selected; TP progressive loading; surgical reconstruction advanced PTTD"),
    joint("ANK-JNT-05", "Calcaneocuboid Joint",
          "Synovial saddle",
          "Capsule reinforced by plantar/dorsal ligaments",
          "Anterior calcaneus with posterior cuboid",
          "Long and short plantar ligaments, bifurcate (calcaneocuboid part), dorsal CC ligaments",
          "Lateral tarsal branches",
          "Lateral plantar, sural, deep peroneal",
          "Limited gliding; lateral column stability; locks with midtarsal during late stance",
          "Minimal INV/EV contribution vs TN",
          "Limited DOF vs TN",
          "Plantar ligaments + PL tendon dynamic",
          "Lateral column length/stability; Chopart joint with TN forms transverse tarsal",
          "Cuboid mobility tests; PL assessment",
          "Lateral midfoot",
          "Cuboid syndrome, CC OA, PL pathology",
          "Lateral column mobilization/stability; PL loading"),
    joint("ANK-JNT-06", "Transverse Tarsal (Chopart) Joint",
          "Functional compound joint — talonavicular + calcaneocuboid",
          "Combined capsules/ligaments of TN and CC",
          "As TN + CC",
          "Spring, bifurcate, long/short plantar, dorsal midtarsal ligaments",
          "Dorsalis pedis / lateral tarsal",
          "Deep peroneal, medial/lateral plantar",
          "Axes allow flexibility early stance and rigidity late stance (oblique + longitudinal midtarsal axes model — Elftman/Manter classical teaching)",
          "Pronation unlocks / supination locks midfoot for push-off (simplified clinical model)",
          "Coupled multiplanar",
          "Ligamentous + TP/PL dynamic",
          "Critical transition flexibility→rigidity in gait",
          "Midtarsal mobility; arch assessment",
          "Midfoot",
          "Chopart injury, midfoot sprain, flatfoot/cavus compensation",
          "Restore control of pronation/supination timing; orthoses; progressive loading"),
]
