"""Ankle ligaments, tendons, muscles, biomechanics, stability, NV, assessment, tests, pathologies, rehab."""
from __future__ import annotations
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _kinora_pdf_common import RA, RB, RC

REF = f"{RA} {RB} {RC}"


def lig(id_, name, origin, insertion, fiber, function, bio, mech, heal, tests, img, rehab):
    return (name, {
        "ID": id_, "Ligament": name, "Origin": origin, "Insertion": insertion,
        "Fiber Orientation": fiber, "Function": function, "Biomechanics": bio,
        "Injury Mechanism": mech, "Healing": heal, "Clinical Tests": tests,
        "Imaging": img, "Rehabilitation": rehab, "References": REF,
    })


LIGAMENTS = [
    lig("ANK-LIG-01", "ATFL (Anterior Talofibular Ligament)",
        "Anterior distal fibula (lateral malleolus)", "Neck of talus anterolaterally",
        "Horizontal / slightly inferior when ankle neutral — most horizontal of lateral ligaments",
        "Primary restraint to anterior talar translation and inversion in PF",
        "First and most commonly injured lateral ligament; taut in PF+INV",
        "Plantarflexion-inversion sprain (classic lateral ankle sprain)",
        "Extra-articular — usually good healing with protected early motion for grade I-II",
        "Anterior drawer (ankle PF ~10-20 deg); anterolateral palpation",
        "MRI/US for grade; XR Ottawa rules for fracture",
        "Early protected ROM, progressive strength, balance/NMC; brace for return"),
    lig("ANK-LIG-02", "CFL (Calcaneofibular Ligament)",
        "Tip of lateral malleolus", "Lateral calcaneus",
        "Cord-like, inferior-posterior — crosses both TC and STJ",
        "Resists inversion in neutral/DF; stabilizes STJ as well as TC",
        "Taut in DF+INV; injured with ATFL in higher-grade sprains",
        "Inversion with more DF component; grade II-III lateral sprain",
        "Extra-articular — heals with bracing/early motion typically",
        "Talar tilt (inversion stress); STJ tilt contribution",
        "MRI/US; stress XR historical",
        "Frontal-plane strength (fibularis); STJ control; progressive COD"),
    lig("ANK-LIG-03", "PTFL (Posterior Talofibular Ligament)",
        "Malleolar fossa of fibula", "Lateral tubercle posterior talar process",
        "Horizontal deep posterior",
        "Strongest lateral ligament; resists posterior talar translation / DF extremes",
        "Rarely isolated injury — usually with severe/dislocation patterns",
        "High-energy inversion/DF or dislocation",
        "Severe injuries — often surgical ankle context",
        "Posterior drawer rarely isolated clinically",
        "MRI",
        "Per severe ankle trauma protocols"),
    lig("ANK-LIG-04", "Deltoid Ligament Complex",
        "Medial malleolus (anterior/posterior colliculi)",
        "Navicular (tibionavicular), spring/sustentaculum (tibiocalcaneal), talus (deep anterior/posterior tibiotalar) — superficial and deep layers",
        "Fan-shaped medial — superficial spans to navicular/calcaneus; deep to talus",
        "Primary restraint to eversion and lateral talar translation; deep layer strongest against abduction of talus",
        "Stabilizes medial mortise; injured in eversion/ER; associated with Weber C / Maisonneuve",
        "Eversion or ER force; often with fibular fracture/syndesmosis",
        "Deep deltoid injury may need longer protection; instability with ER stress",
        "Eversion stress; Kleiger (ER) test; medial clear space on mortise XR",
        "MRI; mortise XR medial clear space >4-5 mm suggests deltoid/syndesmosis injury (context-dependent)",
        "Protect eversion; progressive medial strength (TP); address syndesmosis if combined"),
    lig("ANK-LIG-05", "Anterior Inferior Tibiofibular Ligament (AITFL)",
        "Chaput tubercle (tibia)", "Wagstaffe tubercle (fibula)",
        "Oblique inferior-lateral",
        "Primary anterior syndesmotic stabilizer",
        "Resists ER and posterior fibular translation; injured in high ankle sprain",
        "ER of foot with DF; contact; ski/boot; cutting with planted foot",
        "Longer healing than ATFL — often 6-8+ weeks before cutting",
        "Squeeze, ER stress, tenderness over AITFL",
        "MRI; WB XR tibiofibular clear space; stress views",
        "Protect ER/DF early; progressive loading; surgery if diastasis unstable"),
    lig("ANK-LIG-06", "Posterior Inferior Tibiofibular Ligament (PITFL)",
        "Posterior distal tibia (Volkmann region)", "Posterior distal fibula",
        "Strong posterior band + inferior transverse ligament contribution",
        "Strongest syndesmotic ligament; resists posterior diastasis",
        "Often intact as hinge in some injury patterns; avulsion with posterior malleolus fracture",
        "High-energy ER/DF; fracture-associated",
        "Healing tied to fracture/syndesmosis fixation protocols",
        "ER stress; posterior palpation",
        "MRI/CT for posterior malleolus",
        "Per syndesmosis/ORIF protocols"),
    lig("ANK-LIG-07", "Interosseous Ligament / Membrane (Distal)",
        "Length of tibia-fibula via IO membrane; distal IO ligament thickening",
        "Corresponding fibular border",
        "Vertical fibrous sheet",
        "Major syndesmotic stabilizer; load transfer tibia-fibula",
        "Disruption allows mortise widening; Maisonneuve tears proximal membrane",
        "ER force propagating up IO membrane",
        "Requires anatomic reduction if unstable",
        "Clinical syndesmosis cluster; full-length XR",
        "MRI; proximal fibula XR",
        "Longer protection; avoid early aggressive ER/DF loading"),
    lig("ANK-LIG-08", "Spring Ligament (Plantar Calcaneonavicular)",
        "Sustentaculum tali of calcaneus", "Plantar navicular",
        "Superomedial, medioplantar, inferoplantar bands (complex)",
        "Supports talar head; static medial arch keystone support",
        "Works with TP tendon; failure with advanced PTTD → peritalar subluxation",
        "Degenerative attenuation with TP dysfunction; acute trauma less common isolated",
        "Poor spontaneous restoration if elongated — may need reconstruction with TP surgery",
        "Single heel rise, too-many-toes, arch assessment",
        "MRI spring ligament edema/discontinuity",
        "Orthoses, TP loading early stages; surgical reconstruction selected advanced flatfoot"),
]


def tendon(id_, name, muscle, origin, insertion, nerve, blood, function, bio, clin, inj, assess, rehab):
    return (name, {
        "ID": id_, "Tendon": name, "Muscle": muscle, "Origin": origin, "Insertion": insertion,
        "Innervation": nerve, "Blood Supply": blood, "Function": function, "Biomechanics": bio,
        "Clinical Importance": clin, "Common Injuries": inj, "Assessment": assess,
        "Rehabilitation": rehab, "References": REF,
    })


TENDONS = [
    tendon("ANK-TEN-01", "Achilles Tendon", "Gastrocnemius + soleus (triceps surae); plantaris variable",
           "Musculotendinous junction mid-calf", "Calcaneal tuberosity",
           "Tibial nerve (S1-S2)", "Posterior tibial / peroneal — watershed 2-6 cm above insertion",
           "Primary plantarflexion torque transmitter",
           "Energy storage-release in running; highest load tendon in body (multiples of BW)",
           "Tendinopathy continuum midportion vs insertional; rupture classic middle-aged athlete",
           "Midportion tendinopathy; insertional; complete rupture",
           "Palpation, Royal London, painful arc, Thompson for rupture, Silfverskiöld",
           "Progressive loading (Alfredson/heavy slow/isometrics); rupture: functional rehab vs surgery shared decision"),
    tendon("ANK-TEN-02", "Tibialis Posterior Tendon", "Tibialis posterior",
           "IO membrane / posterior tibia-fibula", "Navicular tuberosity + broad plantar inserts",
           "Tibial nerve (L4-L5)", "Posterior tibial artery",
           "Inversion, PF assist, dynamic medial arch support",
           "Eccentric control of pronation midstance; key in PTTD continuum",
           "Most important dynamic arch supporter; dysfunction → adult-acquired flatfoot",
           "Tendinopathy, tenosynovitis, rupture (degenerative)",
           "Single heel rise (lack of inversion), too-many-toes, swelling behind medial malleolus",
           "Stage-based: orthoses, TP progressive loading early; surgery advanced stages"),
    tendon("ANK-TEN-03", "Tibialis Anterior Tendon", "Tibialis anterior",
           "Lateral tibia / IO membrane", "Medial cuneiform + 1st MT base",
           "Deep peroneal (L4-L5)", "Anterior tibial artery",
           "DF and inversion",
           "Eccentric heel-strike control; swing clearance",
           "Foot drop if nerve injured; rare spontaneous rupture in older adults",
           "Tendinopathy; rupture; laceration",
           "Heel walk, DF strength, palpation anterior ankle",
           "Eccentric DF loading; gait; AFO if neurogenic"),
    tendon("ANK-TEN-04", "Peroneus Longus Tendon", "Peroneus (fibularis) longus",
           "Proximal fibula", "Medial cuneiform + 1st MT base plantar (via cuboid groove)",
           "Superficial peroneal (L5-S1)", "Fibular artery perforators",
           "Eversion; PF 1st ray",
           "Turns at malleolus and cuboid — friction zones; balances TA at 1st ray",
           "Tendinopathy; subluxation with retinaculum injury; cuboid interaction",
           "Tendinopathy, tears, dislocation",
           "Resisted eversion, retromalleolar palpation, DF-eversion subluxation test",
           "Progressive eversion loading; address instability; surgery for recurrent dislocation"),
    tendon("ANK-TEN-05", "Peroneus Brevis Tendon", "Peroneus (fibularis) brevis",
           "Distal fibula", "5th MT tuberosity",
           "Superficial peroneal (L5-S1)", "Fibular perforators",
           "Eversion; lateral ankle dynamic stability",
           "Most commonly torn peroneal tendon (longitudinal splits)",
           "Associated with lateral ankle instability and cavovarus",
           "Longitudinal tear, tendinopathy, 5th MT avulsion differential",
           "Eversion strength, US dynamic",
           "Load + stability; repair selected tears"),
    tendon("ANK-TEN-06", "Flexor Hallucis Longus Tendon", "FHL",
           "Posterior fibula", "Distal phalanx hallux",
           "Tibial nerve (S2-S3)", "Fibular/posterior tibial",
           "Hallux flexion; PF assist; arch assist",
           "Passes under sustentaculum; posteromedial ankle — dancer's tendinopathy / os trigonum overlap",
           "Posterior impingement continuum in pointe/dance",
           "Tenosynovitis, trigger hallux, posteromedial pain",
           "Hallux flexion strength, posterior medial palpation",
           "Load management; progressive hallux flexion; address os trigonum if indicated"),
    tendon("ANK-TEN-07", "Flexor Digitorum Longus Tendon", "FDL",
           "Posterior tibia", "Distal phalanges 2-5",
           "Tibial nerve (S2-S3)", "Posterior tibial",
           "Toe flexion; PF/inversion assist",
           "Henry knot cross with FHL; tarsal tunnel contents",
           "Tarsal tunnel differential; lesser toe deformities contribution",
           "Tenosynovitis uncommon isolated",
           "Toe flexion strength",
           "Intrinsic/extrinsic balance training"),
    tendon("ANK-TEN-08", "Extensor Hallucis Longus Tendon", "EHL",
           "Fibula / IO membrane", "Distal phalanx hallux dorsal",
           "Deep peroneal (L5)", "Anterior tibial",
           "Hallux extension; DF assist",
           "L5 myotome clinical testing",
           "Laceration risk dorsum foot; L5 radiculopathy differential",
           "Laceration; rare rupture",
           "Hallux extension MMT",
           "Protect/repair lacerations; progressive extension"),
    tendon("ANK-TEN-09", "Extensor Digitorum Longus Tendon", "EDL",
           "Tibia/fibula/IO", "Extensor expansions toes 2-5",
           "Deep peroneal (L4-L5)", "Anterior tibial",
           "Toe extension; DF assist",
           "Swing clearance with TA/EHL",
           "Anterior ankle structures under retinaculum",
           "Laceration; tenosynovitis rare",
           "Toe extension strength",
           "DF endurance; retinacular protection post-op"),
]


def mus(id_, name, origin, insertion, nerve, blood, function, emg, clin, ex, prog):
    return (name, {
        "ID": id_, "Muscle": name, "Origin": origin, "Insertion": insertion,
        "Innervation": nerve, "Blood Supply": blood, "Function": function, "EMG": emg,
        "Clinical Importance": clin, "Exercises": ex, "Progressions": prog, "References": REF,
    })


MUSCLES = [
    mus("ANK-MUS-01", "Gastrocnemius", "Femoral condyles", "Achilles → calcaneus", "Tibial S1-S2", "Popliteal sural branches",
        "PF + knee flexion; propulsion", "High sprint/jump push-off", "Tennis leg; Achilles load", "Straight-knee heel raises", "Isometrics → HSR → plyometrics"),
    mus("ANK-MUS-02", "Soleus", "Soleal line / fibula", "Achilles → calcaneus", "Tibial S1-S2", "Posterior tibial/fibular",
        "Primary postural PF; midstance tibial control", "High continuous stance EMG", "Achilles; soleus strain", "Bent-knee heel raises", "Heavy slow soleus bias → run hills"),
    mus("ANK-MUS-03", "Tibialis Anterior", "Lateral tibia/IO", "Medial cuneiform/1st MT", "Deep peroneal L4-L5", "Anterior tibial",
        "DF + inversion; heel-strike control", "High eccentric IC / swing concentric", "Foot drop; MTSS ddx", "Heel walks, eccentric DF lowers", "Endurance → speed walking/run form"),
    mus("ANK-MUS-04", "Tibialis Posterior", "IO/posterior tib-fib", "Navicular + plantar tarsals", "Tibial L4-L5", "Posterior tibial",
        "Inversion + arch support", "High midstance eccentric", "PTTD key muscle", "Inversion band, short-foot, heel rise with INV", "Isometrics → isotonic → single-heel rise"),
    mus("ANK-MUS-05", "Peroneus Longus", "Proximal fibula", "Medial cuneiform/1st MT plantar", "Superficial peroneal L5-S1", "Fibular perforators",
        "Eversion + 1st ray PF", "High cutting/uneven ground", "Tendinopathy; 1st ray stability", "Band eversion, PL-biased heel raises", "Isometrics → functional uneven → COD"),
    mus("ANK-MUS-06", "Peroneus Brevis", "Distal fibula", "5th MT base", "Superficial peroneal L5-S1", "Fibular perforators",
        "Eversion; lateral dynamic stability", "High eversion tasks", "Most torn peroneal tendon", "Resisted eversion", "Add unstable surfaces → cutting"),
    mus("ANK-MUS-07", "FHL", "Posterior fibula", "Hallux distal phalanx", "Tibial S2-S3", "Fibular/PTA",
        "Hallux flexion; push-off", "High dance push-off", "Posterior impingement continuum", "Toe curls, calf raise with toe flexion", "Load manage → progressive pointe/push-off"),
    mus("ANK-MUS-08", "FDL", "Posterior tibia", "Distal phalanges 2-5", "Tibial S2-S3", "PTA",
        "Toe flexion; PF/INV assist", "Stance grip", "Tarsal tunnel contents", "Towel curls", "Combined intrinsic training"),
    mus("ANK-MUS-09", "EHL", "Fibula/IO", "Hallux distal phalanx dorsal", "Deep peroneal L5", "Anterior tibial",
        "Hallux extension; DF assist", "Swing", "L5 myotome", "Resisted hallux extension", "Gait clearance drills"),
    mus("ANK-MUS-10", "EDL", "Tib/fib/IO", "Toes 2-5 extensor expansions", "Deep peroneal L4-L5", "Anterior tibial",
        "Toe extension; DF assist", "Swing", "Anterior compartment", "Heel walks, toe extension", "DF endurance"),
    mus("ANK-MUS-11", "Fibularis Tertius", "Distal fibula/EDL continuum (variable)", "5th MT base dorsal", "Deep peroneal L5-S1", "Anterior tibial",
        "DF + eversion", "Variable EMG", "Anatomic variant often present", "DF-eversion band", "Uneven ground progressions"),
]


def bio(id_, topic, plane, movers, stab, arthro, osteo, role, clin, ex):
    return (topic, {
        "ID": id_, "Topic": topic, "Plane": plane, "Primary Movers": movers, "Stabilizers": stab,
        "Arthrokinematics": arthro, "Osteokinematics": osteo, "Functional Role": role,
        "Clinical Relevance": clin, "Exercises": ex, "References": REF,
    })


BIOMECHANICS = [
    bio("ANK-BIO-01", "Dorsiflexion", "Sagittal", "TA, EHL, EDL, fibularis tertius", "Mortise congruence; ATFL slackens relative",
        "Talus posterior glide (open chain)", "~20 deg typical", "Ankle rocker midstance; squat depth",
        "Limited DF → early heel rise, Achilles stress, ACL risk cascade proximal", "Knee-to-wall DF, soleus stretch, step DF"),
    bio("ANK-BIO-02", "Plantarflexion", "Sagittal", "Gastroc, soleus, TP, PL, FHL, FDL", "Anterior capsule/ATFL check extremes",
        "Talus anterior glide (open chain)", "~50 deg typical", "Propulsion toe-off",
        "Achilles overload; PF weakness impairs push-off", "Heel raises progressive"),
    bio("ANK-BIO-03", "Inversion", "Frontal / triplanar STJ", "TP, TA, FHL, FDL", "ATFL/CFL lateral check",
        "STJ calcaneal INV open chain", "~20 deg STJ contribution approx", "Supination component",
        "Lateral sprain mechanism when excessive + PF", "Controlled INV ROM; avoid early end-range post-sprain"),
    bio("ANK-BIO-04", "Eversion", "Frontal / triplanar STJ", "PL, PB, fibularis tertius", "Deltoid medial check",
        "STJ calcaneal EV", "~10 deg approx", "Pronation component; shock absorption",
        "Deltoid/medial injury if forced; fibularis strengthen for CAI", "Band eversion"),
    bio("ANK-BIO-05", "Pronation", "Triplanar (EV + ABD + DF components)", "Controlled eccentrically by TP/soleus complex", "Spring/TP static-dynamic",
        "STJ + midtarsal unlocking", "Closed-chain tibial IR coupling", "Shock absorb early stance",
        "Excess → PTTD/MTSS cascade; insufficient → poor shock share", "Short-foot, TP eccentrics, cadence"),
    bio("ANK-BIO-06", "Supination", "Triplanar (INV + ADD + PF)", "TP concentric; fibularis eccentrics", "Lateral ligaments",
        "STJ + midtarsal locking late stance", "Rigid lever for push-off", "Propulsive lever",
        "CAI with recurrent INV-supination injury", "Fibularis strength + NMC"),
    bio("ANK-BIO-07", "Closed Chain Mechanics", "Multiplanar", "Entire kinetic chain", "Mortise + STJ + midfoot",
        "Tibial rotation drives STJ; opposite open-chain descriptions", "Foot fixed — body moves over foot",
        "Gait, squat, land", "Most sport injuries closed-chain INV", "Single-leg strength and land training"),
    bio("ANK-BIO-08", "Open Chain Mechanics", "Multiplanar", "Ankle movers", "Ligaments",
        "Classic convex-talus rules", "Foot free — non-WB ROM testing", "Assessment & early rehab",
        "Do not assume open-chain gains transfer without closed-chain training", "Combine OKC + CKC"),
    bio("ANK-BIO-09", "Walking", "Sagittal + STJ triplanar", "TA IC; soleus mid; gastroc/soleus toe-off", "Mortise/STJ",
        "Three rockers", "DF then PF progression", "Community ambulation", "Antalgic patterns post-sprain", "Gait retraining"),
    bio("ANK-BIO-10", "Running", "Multiplanar", "Soleus/Achilles spring; TA impact", "Bone/tendon capacity",
        "Higher load rates", "Strike pattern variable", "Sport locomotion", "Achilles/BSI/CAI risk with spikes", "Cadence, graded volume"),
    bio("ANK-BIO-11", "Jumping", "Sagittal", "PF power", "Achilles SSC", "Rapid PF", "Triple extension", "Jump sports",
        "Achilles tendinopathy if volume excess", "Plyometric ladder after strength"),
    bio("ANK-BIO-12", "Landing", "Multiplanar", "Eccentric PF/DF control; hip strategy", "CAI risk if INV collapse",
        "Rapid DF loading Achilles/soleus", "Soft land preferred", "ACL/ankle injury prevention crossover",
        "Recurrent sprain on poor land INV", "Drop-land progressions, fibularis prep"),
    bio("ANK-BIO-13", "Cutting", "Multiplanar", "Fibularis + hip", "ATFL high demand", "INV/ER stresses", "COD",
        "Lateral & high ankle sprain mechanisms", "Delayed COD after sprain/syndesmosis", "Shadow cut → full speed"),
    bio("ANK-BIO-14", "Balance", "Multiplanar sway", "Intrinsic foot + ankle strategy", "Proprioceptive ligaments",
        "Micro-adjustments STJ/TC", "SLS", "CAI hallmark deficit", "Recurrent sprain risk with poor balance", "Eyes-closed SLS, SEBT/YBT"),
    bio("ANK-BIO-15", "Load Transfer", "Axial + shear", "Bone + tendon + ligament share", "Mortise congruence",
        "Tibia → talus → calcaneus/forefoot", "WB column mechanics", "Fracture/OA if malaligned",
        "Restore length/rotation after fracture", "Progressive WB per injury"),
]

STABILITY = [("""Ankle Stability System""", {
    "ID": "ANK-STAB-01",
    "Static Stabilizers": "Bony mortise congruence (wider anterior talus); ATFL, CFL, PTFL; deltoid complex; syndesmosis (AITFL/PITFL/IO); capsule; spring ligament for talar head/medial arch",
    "Dynamic Stabilizers": "Peroneus longus/brevis (lateral); TP (medial arch); TA; soleus/gastroc; intrinsic foot muscles",
    "Neuromuscular Control": "Feed-forward peroneal activation before landing; delayed peroneal latency common after sprain/CAI",
    "Proprioception": "Ligament/capsule mechanoreceptors; deficit after sprain contributes to CAI",
    "Balance": "Ankle strategy primary on firm surface; hip strategy when challenged; SEBT/YBT assess",
    "Force Transmission": "Axial via plafond; shear restrained by collaterals/syndesmosis; Achilles transmits propulsion",
    "Injury Prevention": "Neuromuscular warm-ups, balance programs, external brace/tape in high-risk sport (evidence for sprain prevention), adequate calf capacity, graded COD exposure",
    "Rehabilitation": "Restore ROM → strength (especially fibularis/TP/soleus) → balance/NMC → hop/land → cut → RTS criteria",
    "References": REF + " International Ankle Consortium CAI criteria themes; sprain prevention literature.",
})]

NERVES = [
    ("Tibial Nerve", {"ID": "ANK-NV-01", "Nerve": "Tibial nerve (ankle/tarsal tunnel)", "Sensory Distribution": "Heel via medial calcaneal; plantar foot via medial/lateral plantar",
     "Motor Supply": "PF muscles proximal; plantar intrinsics via plantar nerves", "Entrapment Sites": "Tarsal tunnel behind medial malleolus",
     "Clinical Tests": "Tinel at tarsal tunnel; DF-eversion neurodynamics; plantar sensation",
     "Vascular Supply": "Travels with posterior tibial artery/vein in tarsal tunnel", "Pulses": "Posterior tibial pulse — 2 cm posteroinferior to medial malleolus", "References": REF}),
    ("Deep Peroneal Nerve", {"ID": "ANK-NV-02", "Nerve": "Deep peroneal (fibular) nerve", "Sensory Distribution": "1st web space",
     "Motor Supply": "Anterior compartment; EDB/EHB", "Entrapment Sites": "Anterior tarsal tunnel under extensor retinaculum; anterior CS",
     "Clinical Tests": "1st web sensation; EHL strength; Tinel anterior ankle",
     "Vascular Supply": "Courses with anterior tibial → dorsalis pedis", "Pulses": "Dorsalis pedis — lateral to EHL tendon on dorsum", "References": REF}),
    ("Superficial Peroneal Nerve", {"ID": "ANK-NV-03", "Nerve": "Superficial peroneal nerve", "Sensory Distribution": "Dorsum foot (most)",
     "Motor Supply": "PL/PB", "Entrapment Sites": "Fascial exit mid-lateral leg; stretched in INV sprain",
     "Clinical Tests": "Dorsal sensation; eversion strength; Tinel fascial exit",
     "Vascular Supply": "Perforators near course; no major named artery companion throughout", "Pulses": "Assess DP/PT as limb perfusion context", "References": REF}),
    ("Sural Nerve", {"ID": "ANK-NV-04", "Nerve": "Sural nerve", "Sensory Distribution": "Lateral foot border / posterolateral ankle",
     "Motor Supply": "None", "Entrapment Sites": "Lateral ankle; Achilles surgery; footwear compression",
     "Clinical Tests": "Lateral foot sensation; Tinel sural course",
     "Vascular Supply": "Near small saphenous vein", "Pulses": "N/A direct — document DP/PT", "References": REF}),
    ("Saphenous Nerve", {"ID": "ANK-NV-05", "Nerve": "Saphenous nerve", "Sensory Distribution": "Medial ankle/foot border",
     "Motor Supply": "None", "Entrapment Sites": "Medial ankle surgery; along great saphenous vein",
     "Clinical Tests": "Medial sensation; infrapatellar branch history at knee",
     "Vascular Supply": "Along great saphenous vein", "Pulses": "Near but distinct from PT pulse", "References": REF}),
]

FUNCTIONAL = [("""Ankle Functional Assessment""", {
    "ID": "ANK-FUNC-01",
    "ROM": "DF (knee flexed/extended), PF, INV, EV; compare sides; knee-to-wall DF (cm)",
    "Strength": "Heel-rise endurance (soleus/gastroc), DF MMT, eversion/inversion handheld dynamometry preferred",
    "Gait": "Observe IC foot slap, midstance pronation, heel rise symmetry, antalgic patterns",
    "Balance": "SLS eyes open/closed; foam; SEBT/YBT",
    "Functional Tests": "Heel walking, toe walking, lunges, step-downs",
    "Hop Tests": "Single hop, triple hop, side hop, figure-8 — LSI ≥90% often targeted for RTS",
    "Heel Raise": "Bilateral then unilateral; note inversion (TP) and height symmetry",
    "Landing": "Drop land quality — avoid INV collapse",
    "Return-to-Sport Criteria": "Full ROM, strength LSI, hop battery, sport-specific COD without apprehension, psych readiness; time alone insufficient",
    "Outcome Measures": "FAAM, FAOS, CAIT (CAI), VISA-A (Achilles), NPRS",
    "References": REF + " International Ankle Consortium; VISA-A.",
})]


def test(id_, name, purpose, positive, sn, sp, evid):
    return (name, {
        "ID": id_, "Test": name, "Purpose": purpose, "Positive Finding": positive,
        "Sensitivity": sn, "Specificity": sp, "Evidence": evid, "References": REF,
    })


TESTS = [
    test("ANK-TEST-01", "Anterior Drawer (Ankle)", "ATFL integrity / anterior talar translation",
         "Increased anterior translation ± sulcus sign vs contralateral",
         "Variable (~30-80% across studies; better delayed than immediate acute)",
         "Moderate-high when clearly asymmetric (study-dependent)",
         "Best interpreted with history/swelling timing; compare sides"),
    test("ANK-TEST-02", "Talar Tilt", "CFL (± ATFL) inversion laxity",
         "Increased inversion talar tilt vs opposite",
         "Moderate/variable", "Moderate/variable",
         "More useful in chronic CAI; painful acutely"),
    test("ANK-TEST-03", "External Rotation Stress Test (Kleiger)", "Syndesmosis and/or deltoid",
         "Pain over syndesmosis ± medial clear space feeling",
         "Moderate", "Relatively higher specificity reported in some series",
         "Part of syndesmosis cluster with squeeze"),
    test("ANK-TEST-04", "Squeeze Test", "Syndesmosis injury",
         "Pain at syndesmosis when compressing mid-tibia-fibula",
         "Lower sensitivity", "Higher specificity in several studies",
         "Positive strongly suggestive; negative does not rule out"),
    test("ANK-TEST-05", "Cotton Test", "Syndesmotic instability (often intraoperative)",
         "Increased lateral translation of talus in mortise",
         "Primarily surgical assessment", "Intraoperative utility",
         "Clinical outpatient use limited vs ER/squeeze"),
    test("ANK-TEST-06", "Thompson Test", "Achilles continuity",
         "Absent PF of foot when calf squeezed = rupture",
         "Very high (~0.96+ often cited)", "Very high (~0.93+ often cited)",
         "Excellent bedside test — still confirm with US/MRI as needed"),
    test("ANK-TEST-07", "Silfverskiöld Test", "Gastroc vs Achilles/soleus tightness",
         "DF improves with knee flexion = gastroc limited; no change = soleus/Achilles",
         "Clinical reliability acceptable for decision-making", "N/A diagnostic Sn/Sp classic",
         "Guides stretching bias (straight vs bent knee)"),
    test("ANK-TEST-08", "Single Heel Raise", "TP function / Achilles capacity",
         "Inability to invert/rise or early fatigue — TP dysfunction stages",
         "Useful clinically for PTTD staging", "Not a classic Sn/Sp metric",
         "Core PTTD examination element"),
    test("ANK-TEST-09", "Star Excursion Balance Test (SEBT)", "Dynamic balance / reach asymmetry",
         "Asymmetry >~4 cm anterior or composite deficits linked to injury risk in some studies",
         "Predictive utility moderate — population-dependent", "Screening tool not diagnostic",
         "Widely used in CAI research"),
    test("ANK-TEST-10", "Y-Balance Test", "Simplified SEBT — anterior/posteromedial/posterolateral",
         "Asymmetry and low composite scores associated with injury risk in athletic cohorts",
         "Moderate predictive validity in published cohorts", "Screening",
         "Practical RTS/balance battery component"),
]


def path(id_, cond, epi, mech, sx, ddx, tests, img, cons, surg, rehab, rts, prog):
    return (cond, {
        "ID": id_, "Condition": cond, "Epidemiology": epi, "Mechanism": mech, "Symptoms": sx,
        "Differential Diagnosis": ddx, "Clinical Tests": tests, "Imaging": img,
        "Conservative Treatment": cons, "Surgical Treatment": surg, "Rehabilitation": rehab,
        "Return to Sport": rts, "Prognosis": prog, "References": REF,
    })


PATHOLOGIES = [
    path("ANK-PATH-01", "Lateral Ankle Sprain",
         "Most common sports ankle injury; ATFL ± CFL", "PF-inversion",
         "Lateral pain, swelling, bruising, difficulty WB", "Fracture, syndesmosis, peroneal tear, OLT",
         "Anterior drawer, talar tilt, Ottawa rules", "XR if Ottawa positive; MRI if refractory/CAI",
         "Early protected motion, brace, progressive NMC — avoid prolonged immobilization",
         "Rare acute; reconstruction for CAI failures", "Functional rehab phases", "Days–weeks grade-dependent with criteria",
         "Good but CAI develops in a substantial minority without adequate rehab"),
    path("ANK-PATH-02", "High Ankle Sprain (Syndesmosis)",
         "Less common than lateral; more time-loss", "ER-DF; contact",
         "Pain above joint line, worse with ER/DF, out of proportion to swelling sometimes",
         "Lateral sprain, Maisonneuve, deltoid", "Squeeze, ER stress, Cotton",
         "MRI; WB XR; full-length tib-fib", "Protect longer; boot period common",
         "Screw/suture-button if unstable diastasis", "Delayed cutting vs lateral sprain", "Often 6-8+ weeks minimum",
         "Good if recognized; missed → OA/instability"),
    path("ANK-PATH-03", "Deltoid Ligament Sprain",
         "Less isolated; often with fibular fracture/syndesmosis", "Eversion/ER",
         "Medial pain, medial clear space issues", "Medial malleolus fracture, TP injury, spring ligament",
         "Eversion stress, Kleiger", "Mortise XR, MRI", "Protect eversion; address combined injuries",
         "Repair/reconstruct in selected unstable/fracture cases", "Medial stability + TP", "Tied to combined injury",
         "Depends on associated mortise stability"),
    path("ANK-PATH-04", "Chronic Ankle Instability (CAI)",
         "Common sequela after recurrent sprain", "Repeated INV injuries + sensorimotor deficit",
         "Giving-way, recurrent sprain, residual pain, impaired balance", "OLT, peroneal tear, subtalar instability, impingement",
         "CAIT questionnaire, drawer/tilt, SEBT", "MRI ligaments/OLT", "NMC, strengthening, brace for sport",
         "Anatomic reconstruction (e.g. Broström) if failed care", "Long-term NMC maintenance", "Criteria + psych",
         "Improved with multimodal care; some need surgery"),
    path("ANK-PATH-05", "Achilles Tendinopathy",
         "Common in runners/masters athletes", "Load exceeding capacity — midportion vs insertional",
         "Morning stiffness, load-related tendon pain", "Rupture partial, bursitis, radiculopathy, DVT",
         "Palpation, painful arc, Royal London, VISA-A", "US/MRI if unclear",
         "Education + progressive loading (strong evidence midportion)", "Rare for pure tendinopathy; debridement selected insertional",
         "Isometrics → HSR → energy storage", "When energy-storage tolerated", "Good but often months"),
    path("ANK-PATH-06", "Achilles Rupture",
         "Middle-aged recreational athletes classic peak", "Sudden push-off / eccentric DF",
         "Pop, weak PF, palpable gap, difficulty toe-off", "Tennis leg, plantaris, ankle sprain",
         "Thompson (high Sn/Sp), Matles, gap", "US/MRI confirm",
         "Functional rehab protocols with early protected motion accepted option in many centers",
         "Surgical repair selected (athletes/shared decision) — re-rupture/infection tradeoffs",
         "Progressive PF loading per protocol 0-6 months", "Often 6-9+ months", "Generally good; re-rupture risk exists either path"),
    path("ANK-PATH-07", "Posterior Tibial Tendinopathy (PTTD)",
         "Middle-aged women common; associated obesity", "Degenerative overload of TP/spring",
         "Medial ankle pain, progressive flatfoot, difficulty heel rise", "Spring tear, deltoid, midfoot OA, tarsal coalition youth",
         "Single heel rise, too-many-toes, too many toes + valgus", "MRI/US; WB XR alignment",
         "Stage-based orthoses, loading, PT early", "Tendon transfer/osteotomy/arthrodesis advanced",
         "Stage I-II active care; III-IV structural", "Limited high-impact if advanced flatfoot", "Stage-dependent"),
    path("ANK-PATH-08", "Peroneal Tendinopathy",
         "Runners, dancers, post-sprain", "Repetitive eversion / instability / cavovarus",
         "Lateral retromalleolar pain, swelling", "Lateral sprain, sural nerve, 5th MT fracture",
         "Resisted eversion, subluxation observation, US", "US dynamic; MRI tears",
         "Load + stability; address retinaculum", "Repair/groove deepening for dislocation/tears",
         "Progressive eversion + NMC", "When COD tolerated", "Good if instability fixed"),
    path("ANK-PATH-09", "Anterior Ankle Impingement",
         "Soccer athletes classic (athlete's ankle)", "Repetitive DF; osteophytes",
         "Anterior pain with DF, kicking", "OLT, soft-tissue impingement, ankle OA",
         "DF impingement provocation", "XR osteophytes; MRI soft tissue",
         "Activity mod, DF mobility carefully, injection selected", "Arthroscopic debridement",
         "Restore DF without forcing bony block", "When DF sport demands met", "Good after arthroscopy if OA limited"),
    path("ANK-PATH-10", "Posterior Ankle Impingement",
         "Ballet/pointe, kicking sports", "Os trigonum / FHL / posterior process",
         "Posterior pain with PF", "Achilles insertional, Haglund, FHL tendinopathy",
         "PF impingement, posteromedial/lateral palpation", "XR os trigonum; MRI",
         "Load modify, FHL mobility, injection", "Excise os trigonum selected",
         "Graded PF loading", "When PF sport demands met", "Good with activity adjust/surgery selected"),
    path("ANK-PATH-11", "Osteochondral Lesion of Talus (OLT)",
         "Post-sprain or idiopathic; medial or lateral talar dome", "Trauma/ischemia theories",
         "Deep ankle pain, catching, swelling after activity", "Impingement, loose body, OA",
         "Pain with load; limited specific test", "MRI staging; CT for cystic",
         "Unload, protected WB selected lesions", "Microfracture/OATS/allograft per size/location",
         "Protected WB → progressive impact per surgery", "Delayed months", "Variable by lesion size/stability"),
    path("ANK-PATH-12", "Ankle Osteoarthritis",
         "Post-traumatic common etiology", "Prior fracture/instability/OLT",
         "Activity pain, stiffness, swelling, reduced DF", "Impingement, inflammatory arthritis",
         "ROM, crepitus, alignment", "WB XR",
         "Exercise, weight loss, brace, injection selective", "Arthrodesis/arthroplasty selected end-stage",
         "Maintain function, strength, activity pacing", "Modified sport often", "Chronic progressive"),
    path("ANK-PATH-13", "Sinus Tarsi Syndrome",
         "Post-sprain lateral hindfoot pain syndrome", "STJ instability / synovitis in sinus tarsi",
         "Lateral pain worse on uneven ground", "CFL, CECS, peroneal, STJ OA",
         "Sinus tarsi tenderness, STJ motion pain", "MRI sinus tarsi; anesthetic injection diagnostic",
         "Proprioception, STJ control, injection", "Synovectomy rare",
         "Balance + fibularis/TP", "When uneven ground tolerated", "Variable"),
    path("ANK-PATH-14", "Ankle/Hindfoot Stress Fracture",
         "Navicular high-risk; medial malleolus; calcaneus in runners/military", "Repetitive overload / energy deficit",
         "Focal bony pain, night pain, hop pain", "Tendinopathy, sprain, MTSS",
         "Point tenderness, hop", "MRI preferred early",
         "Unload risk-stratified; nutrition/RED-S screen", "Navicular may need fixation if delayed/high-risk",
         "Protected → graded run", "Delayed; site-dependent", "Guarded for navicular tension-side"),
    path("ANK-PATH-15", "Ankle Region Fractures (Malleolar, Talar, Calcaneal)",
         "Common traumatic injuries; classification guides care (Weber/Lauge-Hansen; Hawkins; Sanders)",
         "Twisting, fall from height (calcaneus), forced DF/PF (talus)",
         "Pain, swelling, inability to WB, deformity", "Severe sprain, dislocation, syndesmosis",
         "Ottawa rules; neurovascular exam mandatory", "XR; CT articular mapping",
         "Stable nondisplaced may be nonop in boot/cast per ortho",
         "ORIF common for unstable malleolar; talar neck urgent reduction; calcaneus individualized",
         "Surgeon WB/ROM protocols; progressive strength/gait; watch for AVN after talar neck",
         "Months; articular injuries longer", "Depends on reduction quality; OA risk residual"),
]

REHAB = [
    ("Lateral Ankle Sprain Rehab", {"ID": "ANK-REHAB-01", "Condition": "Lateral ankle sprain",
     "Acute Phase": "Protect, optimal loading, ice/compress/elevate as needed; rule out fracture (Ottawa)",
     "Protection": "Functional brace preferred over prolonged cast for most grades I-II",
     "Mobility": "Early DF/PF within pain; progress INV carefully",
     "Strength": "Isometrics → isotonic fibularis/TP/calf",
     "Balance": "SLS progressions early as pain allows",
     "Plyometrics": "After strength/balance base — hop in place → multiplanar",
     "Running Progression": "Walk-run when hop comfortable",
     "Cutting": "Last — after linear run and land quality",
     "Sport-Specific Drills": "Graded COD and sport skills",
     "Return-to-Play Criteria": "Full ROM, strength, hop LSI, sport drills without giving-way; brace optional for high-risk",
     "References": REF}),
    ("Achilles Tendinopathy Rehab", {"ID": "ANK-REHAB-02", "Condition": "Achilles tendinopathy",
     "Acute Phase": "Reduce provocative sprint/hill volume; maintain load capacity",
     "Protection": "Avoid complete rest; relative rest from aggravators",
     "Mobility": "Gentle DF; careful with insertional (limit aggressive stretch into compression)",
     "Strength": "Isometrics for analgesia → heavy slow resistance → energy storage",
     "Balance": "SLS as accessory",
     "Plyometrics": "Late — after HSR tolerance",
     "Running Progression": "Pain-monitoring return",
     "Cutting": "After linear run tolerance",
     "Sport-Specific Drills": "Graded sprint/jump volumes",
     "Return-to-Play Criteria": "VISA-A improvement; sport loads tolerated repeatedly",
     "References": REF + " Cook & Purdam; Alfredson/HSR literature."}),
    ("Achilles Rupture Rehab", {"ID": "ANK-REHAB-03", "Condition": "Achilles rupture (functional or post-op)",
     "Acute Phase": "Ortho protocol — protected PF position early often",
     "Protection": "Boot with wedges weaning per protocol",
     "Mobility": "Gradual DF toward neutral then beyond per timeline",
     "Strength": "Seated PF → bilateral standing → unilateral late",
     "Balance": "When WB allows",
     "Plyometrics": "Late (often 4-6+ months)",
     "Running Progression": "Often ~4-6 months if criteria met",
     "Cutting": "After run and hop capacity",
     "Sport-Specific Drills": "Graded 6-9+ months",
     "Return-to-Play Criteria": "Heel-rise index, hop, psych, surgeon clearance — often ≥6-9 months",
     "References": REF}),
    ("CAI Rehab", {"ID": "ANK-REHAB-04", "Condition": "Chronic ankle instability",
     "Acute Phase": "Settle irritability if recent sprain",
     "Protection": "Brace for high-risk sport during rehab",
     "Mobility": "Restore DF if limited",
     "Strength": "Fibularis, TP, proximal hip",
     "Balance": "Progressive NMC cornerstone — SEBT/YBT",
     "Plyometrics": "Multiplanar landings",
     "Running Progression": "As control allows",
     "Cutting": "Emphasize technique + fatigue resistance",
     "Sport-Specific Drills": "Reactive COD",
     "Return-to-Play Criteria": "CAIT improvement, hop/YBT, no giving-way in sport drills",
     "References": REF + " International Ankle Consortium."}),
    ("Syndesmosis Rehab", {"ID": "ANK-REHAB-05", "Condition": "High ankle sprain",
     "Acute Phase": "Longer protection than lateral; boot common",
     "Protection": "Avoid early forced ER/DF",
     "Mobility": "Gradual DF after protection window",
     "Strength": "Calf, fibularis, proximal",
     "Balance": "Delayed vs simple sprain",
     "Plyometrics": "Delayed",
     "Running Progression": "Later — often after 4-6 weeks minimum depending on grade",
     "Cutting": "Last — ER stress risk",
     "Sport-Specific Drills": "Graded after linear power",
     "Return-to-Play Criteria": "Pain-free ER/DF, hop, sport drills; imaging/surgeon if fixed",
     "References": REF}),
    ("PTTD Rehab", {"ID": "ANK-REHAB-06", "Condition": "Posterior tibial tendinopathy / early AAFD",
     "Acute Phase": "Unload medial tendon (orthosis/boot as stage dictates)",
     "Protection": "UCBL/AFO/orthoses stage-based",
     "Mobility": "Gastroc-soleus flexibility if limited DF contributes to pronation",
     "Strength": "TP progressive, intrinsics, proximal hip",
     "Balance": "Arch-control SLS",
     "Plyometrics": "Only early stages if appropriate",
     "Running Progression": "Often limited in advanced flatfoot",
     "Cutting": "Caution in flexible collapse",
     "Sport-Specific Drills": "Individualize to stage",
     "Return-to-Play Criteria": "Single heel rise capacity, pain, orthosis plan for sport",
     "References": REF}),
]

EVIDENCE = [("""Key Evidence — Ankle Module""", {
    "ID": "ANK-EVID-01",
    "Topic": "Foundational ankle references",
    "Anatomy_Biomechanics": REF,
    "Ottawa_Rules": "Validated decision rules to reduce unnecessary ankle/foot radiographs after acute injury.",
    "CAI": "International Ankle Consortium selection criteria and CAIT themes for chronic ankle instability research/clinical framing.",
    "Achilles": "Thompson test excellent accuracy; progressive loading for tendinopathy; shared decision functional vs surgical rupture care.",
    "Prevention": "Neuromuscular programs and bracing can reduce sprain rates in high-risk sports (evidence supportive).",
    "AI_Note": "Sn/Sp and timelines are approximate and study-dependent — verify with current protocols and individual assessment.",
    "References": REF,
})]
