# Knee tendons through evidence data
from __future__ import annotations
from typing import Any

RA = "Standring S. Gray's Anatomy. Moore KL et al. Clinically Oriented Anatomy. Netter FH."
RB = "Neumann DA. Kinesiology of the Musculoskeletal System."
RC = "Magee DJ. Orthopedic Physical Assessment. Brukner & Khan Clinical Sports Medicine."

TENDON_RECORDS: list[tuple[str, dict[str, Any]]] = [
    ("Patellar Tendon", {
        "ID": "KNEE-TEN-01", "Tendon": "Patellar tendon (ligamentum patellae)",
        "Associated Muscle": "Quadriceps via patella", "Insertion": "Tibial tuberosity",
        "Blood Supply": "Inferior medial/lateral genicular; fat pad vessels — proximal posterior watershed relevant to tendinopathy",
        "Biomechanics": "Transmits extensor force; high load in jump-land (energy storage/release)",
        "Healing": "Tendinopathy is collagen disrepair continuum (Cook & Purdam) — responds to progressive loading over months",
        "Clinical Assessment": "Localized inferior pole pain; decline squat pain; load-related pattern; rule out Osgood in youth",
        "Ultrasound Findings": "Thickening, hypoechoic zones, neovascularization (Doppler) at proximal tendon common",
        "MRI Findings": "Increased T2 signal proximal tendon; rule out partial tear/fat pad",
        "Common Injuries": "Patellar tendinopathy (jumper's knee); rupture (rare — often systemic risk or prior injections)",
        "Treatment": "Education, load management, progressive tendon loading; surgery rare for tendinopathy",
        "Exercises": "Isometric hold (e.g. Spanish squat) for analgesia → heavy slow resistance → energy storage/plyometrics",
        "Rehabilitation": "Pain-monitoring model (e.g. tolerable during/after); 12+ weeks typical; address kinetic chain",
        "Return to Sport": "Criteria: pain-tolerable training loads, hop/jump capacity, sport volume built gradually",
        "References": f"Cook JL & Purdam CR continuum. Malliaras P patellar tendinopathy. {RC}",
    }),
    ("Quadriceps Tendon", {
        "ID": "KNEE-TEN-02", "Tendon": "Quadriceps tendon",
        "Associated Muscle": "Rectus femoris and vastii", "Insertion": "Patellar base / anterior patella",
        "Blood Supply": "Genicular anastomosis — ruptures more in older adults with degeneration",
        "Biomechanics": "Extensor force to patella; rupture loses active extension",
        "Healing": "Complete rupture needs surgical repair; tendinopathy managed with loading",
        "Clinical Assessment": "Suprapatellar pain; palpable gap if rupture; unable to SLR/extend actively if complete",
        "Ultrasound Findings": "Fiber disruption, hematoma; dynamic gap",
        "MRI Findings": "Confirms partial vs complete; retraction",
        "Common Injuries": "Tendinopathy; rupture (often >40 years, systemic risk factors)",
        "Treatment": "Complete rupture — urgent ortho repair; tendinopathy — progressive loading",
        "Exercises": "Isometrics → progressive closed chain → eccentrics as tolerated",
        "Rehabilitation": "Post-repair: protected ROM/brace per surgeon; delayed heavy loading",
        "Return to Sport": "Often 6-9+ months post-repair; tendinopathy criteria-based earlier",
        "References": f"{RA} {RC} Quad tendon rupture reviews.",
    }),
    ("Hamstring Tendons", {
        "ID": "KNEE-TEN-03", "Tendon": "Distal and proximal hamstring tendons (knee module focus distal BF/ST/SM + graft tendons)",
        "Associated Muscle": "Biceps femoris, semitendinosus, semimembranosus",
        "Insertion": "Fibular head (BF); pes anserinus (ST); posteromedial tibia (SM)",
        "Blood Supply": "Perforators; watershed zones near free tendon",
        "Biomechanics": "Eccentric late-swing sprint; distal BF lateral stability with PLC",
        "Healing": "Muscle-tendon strains remodel with progressive lengthening loads; proximal free-tendon slower",
        "Clinical Assessment": "Palpation map; strength; Nordic capacity; differentiate sciatic referred pain",
        "Ultrasound Findings": "Useful for distal/proximal tendon integrity; operator-dependent",
        "MRI Findings": "BAMIC grading for intramuscular; retraction for free-tendon tears",
        "Common Injuries": "LH strain; distal BF; ST/gracilis harvest morbidity after ACLR",
        "Treatment": "Progressive criteria-based rehab; surgery for selected proximal avulsions",
        "Exercises": "Isometrics → heavy slow → Nordics → sprint mechanics",
        "Rehabilitation": "Askling/BAMIC-informed; avoid rapid RTS",
        "Return to Sport": "Strength symmetry, H-test, sprint exposure progressive",
        "References": f"Askling C. British Athletics BAMIC. {RC}",
    }),
    ("Popliteus Tendon", {
        "ID": "KNEE-TEN-04", "Tendon": "Popliteus tendon",
        "Associated Muscle": "Popliteus", "Insertion": "Posterior tibia (muscle belly); tendon originates lateral femoral condyle",
        "Blood Supply": "Lateral genicular / popliteal branches",
        "Biomechanics": "Dynamic PLC; unlocks screw-home; resists tibial ER",
        "Healing": "With PLC injuries — often surgical if grade III complex",
        "Clinical Assessment": "Posterolateral pain; dial test; PLC cluster",
        "Ultrasound Findings": "Limited deep visualization",
        "MRI Findings": "Tendon signal/discontinuity; associated LCL/PFL",
        "Common Injuries": "PLC trauma; rare isolated tendinopathy",
        "Treatment": "Per PLC grade; protect rotational stress",
        "Exercises": "Tibial IR control; progressive rotational stability after clearance",
        "Rehabilitation": "PLC protocols dominate timeline",
        "Return to Sport": "Tied to PLC/multi-ligament RTS criteria",
        "References": f"LaPrade PLC. {RA} {RC}",
    }),
    ("Pes Anserinus", {
        "ID": "KNEE-TEN-05", "Tendon": "Pes anserinus complex (sartorius, gracilis, semitendinosus tendons)",
        "Associated Muscle": "Sartorius, gracilis, semitendinosus",
        "Insertion": "Anteromedial proximal tibia distal to medial joint line",
        "Blood Supply": "Inferior medial genicular / soft tissue",
        "Biomechanics": "Medial knee stabilization; resists valgus/ER dynamically",
        "Healing": "Bursitis/tendinopathy responds to load modification and progressive strength",
        "Clinical Assessment": "Tenderness below medial joint line; swelling; differentiate MCL/meniscus",
        "Ultrasound Findings": "Bursal fluid; tendon thickening",
        "MRI Findings": "Bursitis; rules out meniscal/MCL pathology",
        "Common Injuries": "Pes anserine bursitis; insertional irritation in cyclists/swimmers/OA patients",
        "Treatment": "Load management, flexibility, strengthening; injection selective",
        "Exercises": "Quad/hip strength; gradual hamstring-pes loading; address training errors",
        "Rehabilitation": "Reduce provocative adduction sitting loads; progressive return",
        "Return to Sport": "When tenderness and strength allow sport-specific volume",
        "References": f"{RA} {RC}",
    }),
]

BURSA_RECORDS: list[tuple[str, dict[str, Any]]] = [
    ("Suprapatellar Bursa", {
        "ID": "KNEE-BUR-01", "Bursa": "Suprapatellar bursa/pouch",
        "Location": "Deep to quad tendon, proximal to patella — communicates with knee joint in adults",
        "Structures Protected": "Quadriceps tendon from femur",
        "Function": "Allows smooth extensor glide; reflects intra-articular effusion",
        "Clinical Importance": "Effusion visible/palpable here; communicates with joint",
        "Common Disorders": "Effusion from intra-articular pathology; bursitis rare as isolated",
        "Clinical Examination": "Stroke test, ballottement, bulge sign",
        "Ultrasound": "Excellent for effusion quantification",
        "MRI": "Fluid signal continuous with joint",
        "Treatment": "Treat cause of effusion; aspiration if indicated",
        "Rehabilitation": "Quad activation despite effusion; address intra-articular drivers",
        "References": f"{RA} {RC}",
    }),
    ("Prepatellar Bursa", {
        "ID": "KNEE-BUR-02", "Bursa": "Prepatellar bursa",
        "Location": "Subcutaneous anterior to patella",
        "Structures Protected": "Skin from patella",
        "Function": "Reduce friction during kneeling",
        "Clinical Importance": "Housemaid's knee — swelling localized anterior patella (not joint effusion)",
        "Common Disorders": "Traumatic/inflammatory bursitis; septic bursitis (urgent)",
        "Clinical Examination": "Discrete anterior swelling; knee ROM often preserved vs septic arthritis",
        "Ultrasound": "Fluid collection superficial to patella; guide aspiration",
        "MRI": "If deep infection or unclear diagnosis",
        "Treatment": "Protection, NSAIDs if appropriate; antibiotics/drainage if septic; avoid recurrent kneeling trauma",
        "Rehabilitation": "Padding, activity modification, gradual kneeling exposure",
        "References": f"{RA} {RC}",
    }),
    ("Superficial Infrapatellar Bursa", {
        "ID": "KNEE-BUR-03", "Bursa": "Superficial infrapatellar bursa",
        "Location": "Between skin and patellar tendon / tibial tuberosity",
        "Structures Protected": "Skin from patellar tendon",
        "Function": "Kneeling friction reduction",
        "Clinical Importance": "Clergyman's knee continuum with kneeling bursitis",
        "Common Disorders": "Bursitis from repetitive kneeling",
        "Clinical Examination": "Swelling over tibial tuberosity/tendon — differentiate Osgood in youth",
        "Ultrasound": "Superficial fluid",
        "MRI": "If needed to exclude tendon pathology",
        "Treatment": "Load modification, padding; rare injection",
        "Rehabilitation": "Kneeling hygiene; tendon loading if concurrent tendinopathy",
        "References": f"{RA} {RC}",
    }),
    ("Deep Infrapatellar Bursa", {
        "ID": "KNEE-BUR-04", "Bursa": "Deep infrapatellar bursa",
        "Location": "Between patellar tendon and tibia, below fat pad",
        "Structures Protected": "Patellar tendon from tibia",
        "Function": "Reduce tendon-bone friction",
        "Clinical Importance": "Can accompany fat pad / patellar tendinopathy pain maps",
        "Common Disorders": "Bursitis; often secondary",
        "Clinical Examination": "Deep pain near distal pole/tuberosity; less visible swelling",
        "Ultrasound": "Deep fluid relative to tendon",
        "MRI": "Fluid deep to tendon; assess fat pad",
        "Treatment": "Treat associated tendon/fat pad drivers",
        "Rehabilitation": "Patellar tendon progressive loading principles",
        "References": f"{RA} {RC}",
    }),
    ("Pes Anserine Bursa", {
        "ID": "KNEE-BUR-05", "Bursa": "Pes anserine bursa",
        "Location": "Between pes tendons and MCL / medial tibia",
        "Structures Protected": "Pes tendons from MCL/tibia",
        "Function": "Reduce friction of pes complex",
        "Clinical Importance": "Medial knee pain below joint line — common in OA and overweight patients",
        "Common Disorders": "Pes anserine bursitis",
        "Clinical Examination": "Point tenderness; pain with resisted knee flexion; differentiate meniscus/MCL",
        "Ultrasound": "Bursal fluid",
        "MRI": "Confirms; excludes other medial pathology",
        "Treatment": "Load modification, stretching/strengthening, injection selective",
        "Rehabilitation": "Quad/hip strength; gradual return to provocative activity",
        "References": f"{RA} {RC}",
    }),
    ("Semimembranosus Bursa (Baker Cyst Region)", {
        "ID": "KNEE-BUR-06", "Bursa": "Semimembranosus-medial gastrocnemius bursa (related to Baker's cyst)",
        "Location": "Posteromedial knee between SM tendon and medial gastrocnemius head",
        "Structures Protected": "Tendons in popliteal region",
        "Function": "Reduce friction; may communicate with joint",
        "Clinical Importance": "Baker's (popliteal) cyst enlargement — often secondary to intra-articular disease",
        "Common Disorders": "Baker's cyst; rupture mimics DVT (must differentiate)",
        "Clinical Examination": "Popliteal mass; fullness in extension; screen for effusion/OA/meniscus",
        "Ultrasound": "First-line for cyst vs DVT differentiation support",
        "MRI": "Defines cyst and intra-articular drivers",
        "Treatment": "Treat underlying knee pathology; aspiration/injection selective; surgery rare",
        "Rehabilitation": "Quad strength, effusion control, address meniscal/OA drivers",
        "References": f"{RA} {RC} Baker cyst reviews.",
    }),
]

NERVE_RECORDS: list[tuple[str, dict[str, Any]]] = [
    ("Femoral Nerve", {
        "ID": "KNEE-NRV-01", "Nerve": "Femoral nerve (quadriceps motor; saphenous sensory continuation)",
        "Root Levels": "L2-L4", "Motor Function": "Iliacus, sartorius, pectineus, quadriceps",
        "Sensory Distribution": "Anterior thigh; saphenous to medial leg/foot",
        "Dermatomes": "Primarily L3-L4 anterior thigh/medial leg via saphenous",
        "Myotomes": "L3-L4 knee extension",
        "Entrapment Sites": "Retroperitoneal/iliacus hematoma; under inguinal ligament; iatrogenic",
        "Clinical Presentation": "Quad weakness, reduced patellar reflex, anterior thigh sensory loss",
        "Neurodynamic Tests": "Femoral nerve stretch (prone knee bend) — interpret cautiously",
        "Differential Diagnosis": "L3-L4 radiculopathy; AMI from knee effusion (not true neuropathy)",
        "EMG": "Confirms femoral neuropathy vs root vs AMI patterns",
        "Imaging": "MRI lumbar/plexus if indicated",
        "Treatment": "Address cause; protect falls from quad weakness",
        "Rehabilitation": "Quad re-education, NMES, gait aid, progressive strengthening",
        "References": f"{RA} {RC}",
    }),
    ("Saphenous Nerve", {
        "ID": "KNEE-NRV-02", "Nerve": "Saphenous nerve (including infrapatellar branch)",
        "Root Levels": "L3-L4 (femoral continuation)", "Motor Function": "None (pure sensory)",
        "Sensory Distribution": "Medial knee (infrapatellar branch), medial leg to medial foot",
        "Dermatomes": "Medial leg L4 typically", "Myotomes": "N/A",
        "Entrapment Sites": "Hunter's (adductor) canal; infrapatellar branch neuroma after medial knee surgery/trauma",
        "Clinical Presentation": "Medial knee burning/numbness; pain with kneeling; Tinel at scar",
        "Neurodynamic Tests": "Saphenous neurodynamics / slump variants",
        "Differential Diagnosis": "MCL, pes, medial meniscus, L4 radiculopathy",
        "EMG": "Sensory NCS may help; often clinical diagnosis for infrapatellar neuroma",
        "Imaging": "US/MRI for neuroma in selected cases",
        "Treatment": "Desensitization, neurodynamics, topical agents, injection/neuroma procedures selected",
        "Rehabilitation": "Scar mobility, graded exposure, strength around knee",
        "References": f"{RA} Infrapatellar saphenous neuroma literature. {RC}",
    }),
    ("Tibial Nerve (at Knee)", {
        "ID": "KNEE-NRV-03", "Nerve": "Tibial nerve in popliteal fossa",
        "Root Levels": "L4-S3", "Motor Function": "Hamstrings (tibial portions), posterior compartment distal, intrinsics via plantar nerves",
        "Sensory Distribution": "Posterolateral leg via sural contributions; plantar foot via medial/lateral plantar",
        "Dermatomes": "S1-S2 plantar emphasis", "Myotomes": "S1-S2 plantarflexion / toe flexion",
        "Entrapment Sites": "Popliteal fossa mass/cyst compression; more distal tarsal tunnel",
        "Clinical Presentation": "Posterior pain/paresthesia; intrinsic weakness if distal",
        "Neurodynamic Tests": "SLR with tibial bias (dorsiflexion/eversion)",
        "Differential Diagnosis": "Baker cyst, DVT, S1 radiculopathy, PCL injury pain",
        "EMG": "Localizes tibial neuropathy",
        "Imaging": "US/MRI popliteal fossa",
        "Treatment": "Treat compressive cause; neurodynamics",
        "Rehabilitation": "Nerve mobility, address cyst drivers, strength",
        "References": f"{RA} {RC}",
    }),
    ("Common Fibular (Peroneal) Nerve", {
        "ID": "KNEE-NRV-04", "Nerve": "Common fibular nerve at fibular neck",
        "Root Levels": "L4-S2", "Motor Function": "Short head BF; then deep/superficial fibular — dorsiflexors/evertors",
        "Sensory Distribution": "Lateral leg and dorsum foot",
        "Dermatomes": "L5 dorsal foot emphasis", "Myotomes": "L4-L5 dorsiflexion/eversion",
        "Entrapment Sites": "Fibular neck — cast, habit leg crossing, trauma, PLC surgery risk",
        "Clinical Presentation": "Foot drop, steppage gait, sensory loss dorsum foot",
        "Neurodynamic Tests": "SLR with fibular bias (plantarflexion/inversion)",
        "Differential Diagnosis": "L4-L5 radiculopathy, compartment syndrome, sciatic injury",
        "EMG": "Critical for localization and prognosis",
        "Imaging": "US at fibular neck; MRI if mass/trauma",
        "Treatment": "Relieve compression, AFO as needed, surgical decompression selected",
        "Rehabilitation": "AFO gait, dorsiflexion strengthening/NMES, skin protection",
        "References": f"{RA} {RC}",
    }),
    ("Obturator Nerve", {
        "ID": "KNEE-NRV-05", "Nerve": "Obturator nerve (gracilis / adductor relevance to medial knee)",
        "Root Levels": "L2-L4", "Motor Function": "Adductors, gracilis, obturator externus",
        "Sensory Distribution": "Small medial thigh cutaneous field (variable to knee)",
        "Dermatomes": "Medial thigh L2-L3", "Myotomes": "L2-L3 hip adduction",
        "Entrapment Sites": "Obturator canal; pelvic surgery; less commonly at knee",
        "Clinical Presentation": "Medial thigh pain/weak adduction; may refer toward medial knee",
        "Neurodynamic Tests": "Hip extension-abduction biased neurodynamics",
        "Differential Diagnosis": "Adductor strain, athletic pubalgia, L2-L3 radiculopathy, pes pain",
        "EMG": "Confirms obturator neuropathy",
        "Imaging": "MRI pelvis/thigh if indicated",
        "Treatment": "Address entrapment cause; load management adductors",
        "Rehabilitation": "Adductor progressive loading; differential motor control",
        "References": f"{RA} {RC}",
    }),
]

BLOOD_RECORDS: list[tuple[str, dict[str, Any]]] = [
    ("Popliteal Artery", {
        "ID": "KNEE-ART-01", "Artery": "Popliteal artery",
        "Origin": "Continuation of femoral artery after hiatus adductorius",
        "Course": "Through popliteal fossa deep to tibial nerve/vein orientation variations; divides at lower border soleus into anterior and posterior tibial",
        "Branches": "Genicular arteries (SM/SL/IM/IL/middle); sural arteries",
        "Structures Supplied": "Knee joint via genicular anastomosis; posterior capsule; surrounding muscles",
        "Venous Drainage": "Popliteal vein → femoral vein",
        "Clinical Importance": "Dislocation of knee — limb-threatening vascular injury risk; always neurovascular exam; ABI/CTA if concern",
        "Imaging": "Duplex, CTA, angiography for trauma",
        "References": f"{RA} Knee dislocation vascular injury guidelines.",
    }),
    ("Superior Medial Genicular", {
        "ID": "KNEE-ART-02", "Artery": "Superior medial genicular artery",
        "Origin": "Popliteal artery", "Course": "Winds above medial femoral condyle deep to muscles toward anterior anastomosis",
        "Branches": "Articular and soft-tissue rami", "Structures Supplied": "Medial femoral condyle, vastus medialis, medial capsule, ACL region anastomoses",
        "Venous Drainage": "Genicular veins to popliteal", "Clinical Importance": "Part of genicular anastomosis; target in genicular artery embolization for knee OA pain (emerging)",
        "Imaging": "Angiography/CTA", "References": f"{RA}",
    }),
    ("Superior Lateral Genicular", {
        "ID": "KNEE-ART-03", "Artery": "Superior lateral genicular artery",
        "Origin": "Popliteal artery", "Course": "Above lateral femoral condyle to anterior anastomosis",
        "Branches": "Articular rami", "Structures Supplied": "Lateral femoral condyle, VL, lateral capsule, PF anastomosis",
        "Venous Drainage": "Genicular veins to popliteal", "Clinical Importance": "Anastomosis redundancy if one genicular injured; surgical approach awareness",
        "Imaging": "Angiography/CTA", "References": f"{RA}",
    }),
    ("Inferior Medial Genicular", {
        "ID": "KNEE-ART-04", "Artery": "Inferior medial genicular artery",
        "Origin": "Popliteal artery", "Course": "Below medial tibial plateau along MCL region forward",
        "Branches": "Articular rami", "Structures Supplied": "Medial tibial plateau, MCL region, inferior PF anastomosis, patellar tendon region",
        "Venous Drainage": "Genicular veins to popliteal", "Clinical Importance": "Patellar blood supply contribution; medial surgery awareness",
        "Imaging": "Angiography/CTA", "References": f"{RA}",
    }),
    ("Inferior Lateral Genicular", {
        "ID": "KNEE-ART-05", "Artery": "Inferior lateral genicular artery",
        "Origin": "Popliteal artery", "Course": "Passes above fibular head / near LCL toward anterior anastomosis",
        "Branches": "Articular rami", "Structures Supplied": "Lateral tibial plateau, LCL region, inferior PF anastomosis",
        "Venous Drainage": "Genicular veins to popliteal", "Clinical Importance": "PLC surgical proximity; anastomosis participant",
        "Imaging": "Angiography/CTA", "References": f"{RA}",
    }),
    ("Middle Genicular", {
        "ID": "KNEE-ART-06", "Artery": "Middle genicular artery",
        "Origin": "Popliteal artery", "Course": "Pierces oblique popliteal ligament into intercondylar notch",
        "Branches": "Branches to cruciate ligaments and synovial notch tissues",
        "Structures Supplied": "ACL and PCL primary blood supply; synovium of notch",
        "Venous Drainage": "To popliteal venous system", "Clinical Importance": "Cruciate healing/vascularity; notch surgery awareness",
        "Imaging": "Angiography (not routine clinically)", "References": f"{RA} ACL vascular anatomy literature.",
    }),
]
