# Knee ligaments–bursae data (Part A continued)
from __future__ import annotations
from typing import Any

try:
    from _knee_data import RA, RB, RC
except ImportError:
    RA = "Standring S. Gray's Anatomy. Moore KL et al. Clinically Oriented Anatomy. Netter FH."
    RB = "Neumann DA. Kinesiology of the Musculoskeletal System."
    RC = "Magee DJ. Orthopedic Physical Assessment. Brukner & Khan Clinical Sports Medicine."

LIGAMENT_RECORDS: list[tuple[str, dict[str, Any]]] = [
    ("ACL", {
        "ID": "KNEE-LIG-01", "Ligament": "Anterior cruciate ligament",
        "Origin": "Posteromedial aspect of lateral femoral condyle (intercondylar notch wall)",
        "Insertion": "Anterior intercondylar area of tibia, just anterior/between tibial spines",
        "Primary Function": "Resists anterior tibial translation; resists tibial IR; key rotational stabilizer",
        "Secondary Function": "Secondary restraint to varus/valgus at extension; proprioception",
        "Biomechanics": "Anteromedial and posterolateral bundles; AM tighter in flexion, PL in extension (simplified teaching model)",
        "Load Capacity": "Ultimate load classically about 1700-2200 N in young specimens (study-dependent); grafts remodel over months",
        "Blood Supply": "Middle genicular artery primary; fat pad contributions",
        "Healing": "Intra-articular — poor spontaneous healing of complete tears; reconstruction common in cutting athletes",
        "Clinical Tests": "Lachman (most sensitive), anterior drawer, pivot shift (specific for rotational laxity)",
        "Common Injuries": "Noncontact pivot (cut/land); contact valgus; often with meniscus/MCL (unhappy triad)",
        "MRI Findings": "Fiber discontinuity, abnormal signal, bone bruises (lateral femoral condyle + posterior lateral tibia classic)",
        "Ultrasound": "Limited for ACL proper; not first-line",
        "Treatment": "Coper vs reconstruction shared decision; bracing/rehab for selected; ACLR for instability/sport demand",
        "Rehabilitation": "Quad activation, extension early, progressive strength/NMC, criteria-based RTS often 9-12+ months",
        "Return to Sport": "Time + criteria (strength symmetry, hop tests, psych readiness); reinjury risk if premature",
        "References": f"{RA} {RC} AAOS/AOSSM ACL themes. Musahl/Karlsson consensus literature.",
    }),
    ("PCL", {
        "ID": "KNEE-LIG-02", "Ligament": "Posterior cruciate ligament",
        "Origin": "Anterolateral medial femoral condyle (notch)",
        "Insertion": "Posterior tibial sulcus / posterior intercondylar area",
        "Primary Function": "Resists posterior tibial translation",
        "Secondary Function": "Secondary rotational and varus/valgus restraint",
        "Biomechanics": "AL and PM bundles; strongest knee ligament by cross-section",
        "Load Capacity": "Higher ultimate load than ACL in many cadaver series (approx 2500-4000 N — study-dependent)",
        "Blood Supply": "Middle genicular artery",
        "Healing": "Better healing potential than ACL; many isolated PCL injuries treated nonoperatively",
        "Clinical Tests": "Posterior drawer, posterior sag (Godfrey), quadriceps active test; dial if PLC combined",
        "Common Injuries": "Dashboard injury; fall on flexed knee with plantarflexed foot; combined PLC",
        "MRI Findings": "Fiber disruption/thickening; posterior tibial translation signs",
        "Ultrasound": "Not primary",
        "Treatment": "Grade I-II often conservative; grade III / combined / bony avulsion may need surgery",
        "Rehabilitation": "Avoid early isolated hamstring loading that posteriorly shears; progressive quad; protect against posterior sag",
        "Return to Sport": "Often 3-9 months depending on grade/surgery; criteria-based",
        "References": f"{RA} {RC} PCL management reviews.",
    }),
    ("MCL", {
        "ID": "KNEE-LIG-03", "Ligament": "Medial collateral ligament (tibial collateral) — superficial and deep layers",
        "Origin": "Medial femoral epicondyle",
        "Insertion": "Superficial: proximal medial tibia about 5-7 cm below joint. Deep: meniscocapsular attachments",
        "Primary Function": "Primary restraint to valgus; resists tibial ER",
        "Secondary Function": "Secondary anterior translation restraint (especially if ACL deficient)",
        "Biomechanics": "Superficial MCL primary valgus stabilizer across flexion; deep MCL linked to medial meniscus",
        "Load Capacity": "Robust healing potential compared with ACL; grades I-II usually heal",
        "Blood Supply": "Inferior medial genicular and soft-tissue plexus — relatively good",
        "Healing": "Extra-articular — excellent healing with protected motion for most grade I-II",
        "Clinical Tests": "Valgus stress at 0 and 30 degrees; 30 degrees isolates MCL more",
        "Common Injuries": "Valgus blow; cutting; unhappy triad with ACL/medial meniscus",
        "MRI Findings": "Fiber edema/discontinuity; femoral insertion common; Pellegrini-Stieda chronic calcification",
        "Ultrasound": "Useful for superficial MCL fiber disruption and dynamic gapping",
        "Treatment": "Bracing and early ROM for most; surgery rare (distal Stener-like / multi-ligament)",
        "Rehabilitation": "Early motion in brace; progressive adductor/quad; avoid early aggressive valgus stress",
        "Return to Sport": "Grade I about 1-3 wks; II about 3-6 wks; III often 6-12+ wks — criteria-based",
        "References": f"{RA} {RC} MCL healing literature.",
    }),
    ("LCL", {
        "ID": "KNEE-LIG-04", "Ligament": "Lateral collateral ligament (fibular collateral)",
        "Origin": "Lateral femoral epicondyle",
        "Insertion": "Fibular head",
        "Primary Function": "Primary restraint to varus at 30 degrees flexion",
        "Secondary Function": "Secondary ER/rotation restraint with PLC",
        "Biomechanics": "Cord-like; extracapsular; distinct from popliteus tendon",
        "Load Capacity": "Smaller than MCL; often injured with PLC not in isolation",
        "Blood Supply": "Inferior lateral genicular / soft tissue",
        "Healing": "Variable; grade III / PLC often need surgical consideration",
        "Clinical Tests": "Varus stress 0 and 30 degrees; dial test; posterolateral drawer",
        "Common Injuries": "Varus trauma; combined PLC; fibular head avulsion",
        "MRI Findings": "LCL discontinuity; associated PLC/biceps; arcuate sign on X-ray if styloid avulsion",
        "Ultrasound": "Can visualize LCL dynamically",
        "Treatment": "Isolated low-grade conservative; unstable PLC/LCL often reconstruct",
        "Rehabilitation": "Protect varus; progressive lateral strength; gait with unloader strategies if needed",
        "Return to Sport": "Depends on PLC involvement — often months after reconstruction",
        "References": f"{RA} LaPrade PLC/LCL literature. {RC}",
    }),
    ("MPFL", {
        "ID": "KNEE-LIG-05", "Ligament": "Medial patellofemoral ligament",
        "Origin": "Between adductor tubercle and medial epicondyle (Schottle point surgical landmark)",
        "Insertion": "Upper/medial patella (proximal half typically)",
        "Primary Function": "Primary soft-tissue restraint to lateral patellar dislocation in early flexion (0-30 degrees)",
        "Secondary Function": "Guides patellar engagement into trochlea",
        "Biomechanics": "Highest contribution to medial restraint near extension; trochlea bony constraint dominates deeper flexion",
        "Load Capacity": "Fails commonly in first-time lateral dislocation",
        "Blood Supply": "Medial genicular / soft-tissue network",
        "Healing": "May heal elongated; recurrent instability if anatomic risk factors (trochlear dysplasia, TT-TG, patella alta)",
        "Clinical Tests": "Patellar apprehension; moving apprehension; lateral glide excess",
        "Common Injuries": "Lateral patellar dislocation — MPFL tear often at femoral or patellar attachment",
        "MRI Findings": "MPFL disruption; medial patellar / lateral femoral osteochondral injury; bone bruise pattern",
        "Ultrasound": "Dynamic MPFL/medial restraint assessment adjunct",
        "Treatment": "First dislocation often conservative if reduced and no unstable osteochondral fragments; reconstruction for recurrent",
        "Rehabilitation": "Brace/ROM protocols; VMO/quad and hip strength; avoid early provocative lateral stress",
        "Return to Sport": "Often 3-6+ months criteria-based after reconstruction",
        "References": f"{RA} Patellar instability consensus literature. {RC}",
    }),
    ("Posterolateral Corner", {
        "ID": "KNEE-LIG-06",
        "Ligament": "Posterolateral corner complex (LCL, popliteus tendon, popliteofibular ligament, capsule/arcuate)",
        "Origin": "Lateral femoral condyle / fibular head / posterolateral tibia (structure-specific)",
        "Insertion": "Structure-specific — see LCL, popliteus, PFL",
        "Primary Function": "Resists varus, tibial ER, and posterior translation near extension",
        "Secondary Function": "Protects ACL/PCL from abnormal coupled motions",
        "Biomechanics": "Critical in combined ligament injury; missed PLC raises ACL/PCL graft failure risk",
        "Load Capacity": "Complex failure under high-energy trauma",
        "Blood Supply": "Inferior lateral genicular and popliteal branches",
        "Healing": "Grade III PLC often poor with nonoperative care alone — early diagnosis important",
        "Clinical Tests": "Dial at 30/90, posterolateral drawer, reverse pivot, varus stress, external rotation recurvatum",
        "Common Injuries": "High-energy varus/hyperextension/twist; combined ACL/PCL",
        "MRI Findings": "LCL/popliteus/PFL injury; bone bruises; arcuate sign",
        "Ultrasound": "Limited completeness vs MRI",
        "Treatment": "Acute repair/reconstruct per injury pattern; chronic reconstruction",
        "Rehabilitation": "Protected ROM/WB per surgery; progressive rotational control; delayed aggressive pivoting",
        "Return to Sport": "Often 9-12+ months in multi-ligament knees",
        "References": f"LaPrade RF PLC anatomy/reconstruction. {RC}",
    }),
    ("Posteromedial Corner", {
        "ID": "KNEE-LIG-07",
        "Ligament": "Posteromedial corner (posterior oblique ligament, semimembranosus expansions, posteromedial capsule, deep MCL)",
        "Origin": "Medial femoral epicondyle / adductor tubercle region and posteromedial tibia",
        "Insertion": "Posteromedial tibia / meniscocapsular complex",
        "Primary Function": "Resists valgus and tibial IR/anteromedial rotational instability near extension",
        "Secondary Function": "Supports medial meniscus; complements superficial MCL",
        "Biomechanics": "POL tight in extension; important in AMRI with ACL injury",
        "Load Capacity": "Often injured with MCL/ACL",
        "Blood Supply": "Medial genicular network",
        "Healing": "Capsular structures may heal with protected motion; residual AMRI may need addressing",
        "Clinical Tests": "Valgus at 0 degrees (capsule/PMC); anteromedial drawer; Slocum test variants",
        "Common Injuries": "Valgus-rotation; ACL + medial sided injury",
        "MRI Findings": "POL/capsular edema; meniscocapsular separation (ramp)",
        "Ultrasound": "Adjunct for MCL; PMC deeper harder",
        "Treatment": "Often with MCL bracing; surgery in multi-ligament / persistent AMRI",
        "Rehabilitation": "Early protected ROM; quad; progressive rotational control",
        "Return to Sport": "Tied to MCL/ACL timelines",
        "References": f"{RA} PMC/AMRI literature. {RC}",
    }),
    ("Coronary Ligaments", {
        "ID": "KNEE-LIG-08", "Ligament": "Coronary (meniscotibial) ligaments",
        "Origin": "Peripheral meniscal margins",
        "Insertion": "Tibial plateau margins",
        "Primary Function": "Anchor menisci to tibia; allow controlled meniscal motion",
        "Secondary Function": "Contribute to meniscal stability and load sharing",
        "Biomechanics": "Disruption permits meniscal extrusion and altered hoop stress",
        "Load Capacity": "Can tear with meniscal root/peripheral injuries",
        "Blood Supply": "Peripheral meniscal capillary plexus",
        "Healing": "Peripheral — potential if vascular zone involved and stabilized",
        "Clinical Tests": "No isolated bedside test; inferred with meniscal exam and MRI",
        "Common Injuries": "With meniscal tears, root injuries, trauma",
        "MRI Findings": "Meniscal extrusion; meniscotibial ligament discontinuity",
        "Ultrasound": "Limited",
        "Treatment": "Address with meniscal repair when indicated",
        "Rehabilitation": "Per meniscal repair protocol",
        "Return to Sport": "Per associated meniscal surgery",
        "References": f"{RA} Meniscotibial ligament / extrusion literature.",
    }),
]


def _m(id_, name, origin, insertion, nerve, blood, fiber, primary, secondary, stab, syn, ant,
       lt, emg, trg, ref_pain, stretch, strength, nmc, clin, inj, rehab) -> dict[str, Any]:
    return {
        "ID": id_, "Muscle": name, "Origin": origin, "Insertion": insertion, "Innervation": nerve,
        "Blood Supply": blood, "Fiber Direction": fiber, "Primary Action": primary,
        "Secondary Action": secondary, "Stabilizing Function": stab, "Synergists": syn,
        "Antagonists": ant, "Length-Tension Relationship": lt, "EMG Activation": emg,
        "Trigger Points": trg, "Pain Referral": ref_pain, "Stretch": stretch, "Strengthening": strength,
        "Neuromuscular Control": nmc, "Clinical Importance": clin, "Common Injuries": inj,
        "Rehabilitation": rehab, "References": f"{RA} {RB} {RC}",
    }


MUSCLE_RECORDS: list[tuple[str, dict[str, Any]]] = [
    ("Rectus Femoris", _m(
        "KNEE-MUS-01", "Rectus femoris",
        "AIIS (straight head) and superior acetabular rim (reflected head)",
        "Quadriceps tendon to patella to tibial tuberosity via patellar tendon",
        "Femoral nerve (L2-L4)", "LCFA and femoral branches", "Vertical biarticular anterior thigh",
        "Knee extension and hip flexion", "Anterior pelvic tilt influence",
        "Extensor mechanism; decelerates knee flexion", "Vastii", "Hamstrings",
        "Active insufficiency with combined hip flexion + knee extension; passive insufficiency opposite",
        "High in kicking, sprinting, jumping", "Anterior thigh", "Anterior thigh to knee",
        "Prone quad stretch with hip extension", "Short-arc quads, Spanish squat, graded kicking",
        "Coordinate hip-knee coupling in landing", "AIIS apophysitis; RF strain in kickers",
        "Myotendinous strain; AIIS avulsion (youth)", "Progressive loading; delayed max kicking",
    )),
    ("Vastus Medialis", _m(
        "KNEE-MUS-02", "Vastus medialis (including VMO oblique fibers)",
        "Medial linea aspera, intertrochanteric line, medial supracondylar line, tendons of adductors",
        "Medial quad tendon / medial patellar retinaculum / patella",
        "Femoral nerve (L2-L4)", "Femoral / descending genicular", "Oblique distal fibers (VMO) medially to patella",
        "Knee extension; medial patellar stabilization (VMO contribution)", "Last-degree extension contribution debated",
        "Medial PF tracking restraint with MPFL", "Other vastii, RF", "Hamstrings",
        "Best force mid-range extension; atrophy common after effusion/ACL",
        "Active in terminal extension and SLR; open vs closed chain both useful",
        "Medial thigh to medial knee", "Medial knee",
        "Not typically stretched in isolation", "Quad sets, TKE, step-downs, closed-chain squats",
        "Timing with VL for tracking; address effusion first",
        "PFPS; post-op inhibition (arthrogenic muscle inhibition)",
        "AMI after injury/surgery", "NMES adjunct; effusion control; progressive closed chain",
    )),
    ("Vastus Lateralis", _m(
        "KNEE-MUS-03", "Vastus lateralis",
        "Greater trochanter, linea aspera, intertrochanteric line, lateral intermuscular septum",
        "Lateral quad tendon / lateral retinaculum / patella",
        "Femoral nerve (L2-L4)", "LCFA descending branch", "Large lateral bulk — lateral pull on patella",
        "Knee extension", "Lateral patellar force vector",
        "Extensor torque; can dominate if medial structures weak/tight lateral tissues",
        "Other vastii, RF", "Hamstrings",
        "Large CSA — major extensor torque contributor",
        "High in squats, lunges, jumping", "Lateral thigh", "Lateral thigh to lateral knee",
        "ITB/lateral retinacular soft-tissue techniques as adjunct", "Squats, lunges, step-ups",
        "Balance with medial quad and hip control for PF tracking",
        "PFPS lateral overload patterns; ITB interplay", "Contusion; strain less than RF",
        "Load management; hip abductor strength; avoid chronic lateral tightness assumptions alone",
    )),
    ("Vastus Intermedius", _m(
        "KNEE-MUS-04", "Vastus intermedius",
        "Anterior and lateral femoral shaft", "Deep quad tendon / patella",
        "Femoral nerve (L2-L4)", "LCFA / femoral perforators", "Deep vertical under RF",
        "Knee extension", "Articularis genu related to synovial retraction",
        "Deep extensor force", "Other vastii", "Hamstrings",
        "Works across knee ROM with vastii group", "Co-activates with quad set/squat",
        "Deep anterior thigh", "Anterior thigh", "With RF stretch", "Same quad progressions",
        "Part of global quad reactivation after AMI", "Often overlooked contributor to extension lag",
        "Contusion deep thigh", "Progressive quad loading post-injury",
    )),
    ("Biceps Femoris", _m(
        "KNEE-MUS-05", "Biceps femoris (long and short heads)",
        "LH: ischial tuberosity. SH: linea aspera / lateral supracondylar line",
        "Fibular head (and lateral tibial contributions)",
        "LH tibial nerve; SH common fibular nerve (L5-S2)", "Perforators / inferior gluteal",
        "Lateral posterior thigh — biarticular LH", "Knee flexion and tibial ER; LH hip extension",
        "Hip extension (long head); assists PLC dynamically", "PLC dynamic support with LCL/biceps complex",
        "Other hamstrings", "Quadriceps",
        "High late-swing sprint strain risk when lengthening",
        "Very high late-swing sprint EMG (LH)", "Lateral posterior thigh", "To fibular head / lateral knee",
        "Supine SLR-based stretch with neural differentiation", "Nordics, RDLs, leg curls, sprint drills",
        "Deceleration control; fibular head stability with LCL",
        "Most common sprint hamstring strain (LH); PLC association at insertion",
        "Myofascial strain; distal insertion injury", "BAMIC-informed progressive lengthening rehab",
    )),
    ("Semitendinosus", _m(
        "KNEE-MUS-06", "Semitendinosus",
        "Ischial tuberosity (conjoint with BF LH)", "Pes anserinus (proximal medial tibia)",
        "Tibial nerve (L5-S2)", "Perforators", "Medial posterior — long tendon",
        "Knee flexion and tibial IR; hip extension", "Pes anserinus medial stability",
        "Dynamic MCL assistant", "SM, BF", "Quadriceps",
        "Common ACL autograft harvest — monitor donor morbidity",
        "High in Nordic and RDL", "Medial posterior thigh", "Medial knee / pes",
        "Hamstring stretch", "Nordics, curls, RDL", "Medial chain control in cutting",
        "Graft harvest; proximal tendinopathy; pes bursitis differential",
        "Strain; harvest-related weakness", "Progressive eccentric; graft-site rehab after ACLR",
    )),
    ("Semimembranosus", _m(
        "KNEE-MUS-07", "Semimembranosus",
        "Ischial tuberosity (separate footprint)", "Posteromedial tibial condyle with expansions to PMC/meniscus",
        "Tibial nerve (L5-S2)", "Perforators", "Deep medial hamstring",
        "Knee flexion, tibial IR, hip extension", "Retracts medial meniscus posteriorly; PMC tension",
        "Posteromedial stability", "ST, BF", "Quadriceps",
        "Expansions clinically important in PMC and Baker cyst region",
        "High in hip hinge and curl", "Posteromedial knee", "Posteromedial knee",
        "Hamstring stretch", "RDL, curls, bridge progressions", "PMC control with ACL rehab",
        "PMC injury; distal tendinopathy; Baker cyst association",
        "Distal insertional pain; strain", "Load progressive; differentiate meniscal pain",
    )),
    ("Popliteus", _m(
        "KNEE-MUS-08", "Popliteus",
        "Lateral femoral condyle (intra-articular origin) and fibular head via popliteofibular ligament complex",
        "Posterior proximal tibia above soleal line",
        "Tibial nerve (L4-S1)", "Inferior medial genicular / popliteal branches",
        "Oblique across posterior knee",
        "Unlocks knee by tibial IR (open chain) / femoral ER (closed chain) initiating flexion",
        "Assists knee flexion; resists tibial ER",
        "Dynamic PLC stabilizer",
        "LCL / popliteofibular ligament complex",
        "Knee extensors; tibial external rotators",
        "Critical in screw-home reversal",
        "Active at flexion initiation and rotational control",
        "Posterior knee", "Posterolateral knee",
        "Gentle tibial ER stretch variants",
        "Tibial IR against resistance; terminal stance control drills",
        "PLC rehab rotational control",
        "PLC injury; difficult isolated strain diagnosis",
        "With PLC trauma",
        "Protect varus/ER early after PLC surgery",
    )),
    ("Gastrocnemius", _m(
        "KNEE-MUS-09", "Gastrocnemius (medial and lateral heads)",
        "Posterior femoral condyles", "Achilles tendon to calcaneus",
        "Tibial nerve (S1-S2)", "Sural branches of popliteal", "Biarticular posterior — crosses knee and ankle",
        "Ankle plantarflexion; knee flexion assist", "Posterior capsular dynamic support",
        "Resists knee hyperextension dynamically", "Soleus (ankle), hamstrings (knee)", "Tibialis anterior; quadriceps",
        "Active insufficiency with knee flexion + PF", "High in sprint push-off and jump",
        "Calf to posterior knee", "Posterior knee / calf — DVT differential important",
        "Wall gastroc stretch knee extended", "Heel raises (knee extended biases gastroc)",
        "Deceleration and landing stiffness control", "Strain (tennis leg medial head); Baker cyst differential",
        "Medial head strain; contusion", "Progressive loading; screen vascular red flags if acute calf swelling",
    )),
    ("Sartorius", _m(
        "KNEE-MUS-10", "Sartorius",
        "ASIS", "Pes anserinus",
        "Femoral nerve (L2-L3)", "Femoral artery branches", "Oblique longest muscle",
        "Hip FABER; knee flexion and tibial IR", "Pes medial support",
        "Minor dynamic medial stabilizer", "Gracilis, ST at pes", "Glute max / vastii depending on action",
        "Active across hip and knee — multiplanar", "FABER motions, early swing",
        "Anterior thigh strip", "Anterior medial knee",
        "Combined extension-adduction-IR stretch carefully", "FABER loading, step-ups",
        "Pes anserine load management", "Pes anserine bursitis differential; ASIS avulsion youth",
        "Proximal avulsion; strain", "Progressive multiplanar loading",
    )),
    ("Gracilis", _m(
        "KNEE-MUS-11", "Gracilis",
        "Inferior pubic ramus / body", "Pes anserinus",
        "Obturator nerve (L2-L3)", "Obturator artery", "Medial thigh vertical",
        "Hip adduction; knee flexion and tibial IR", "Pes medial stability",
        "Dynamic medial restraint assistant", "Other adductors, ST, sartorius", "Abductors, VL",
        "Common ACL graft with ST (hamstring graft)", "Adductor and pes tasks",
        "Medial thigh", "Medial knee",
        "Butterfly / adductor stretch graded", "Copenhagen, squeezes, curls",
        "Graft harvest rehab after ACLR", "Adductor-related groin pain; harvest morbidity",
        "Strain; harvest", "Progressive adductor and knee flexion strength",
    )),
    ("Tensor Fasciae Latae", _m(
        "KNEE-MUS-12", "Tensor fasciae latae",
        "ASIS / anterior iliac crest", "ITB to Gerdy's tubercle",
        "Superior gluteal nerve (L4-S1)", "Superior gluteal artery", "Anterolateral into ITB",
        "Hip flexion, abduction, IR; tensions ITB", "Assists knee stability via ITB near extension",
        "Lateral knee restraint via ITB", "Glute med (abd), RF (flex)", "Adductors",
        "Overactivity common when glute med weak", "Side-step and flexion-abduction tasks",
        "Lateral hip/thigh", "Lateral knee (ITBS continuum)",
        "Hip extension-adduction stretch; foam roll adjunct (evidence mixed)",
        "Usually prioritize glute med over TFL dominance", "Pelvic control in running",
        "IT band syndrome contributor; PF lateral force", "Myofascial overuse",
        "Cadence/load management; hip abductor endurance; running form",
    )),
]
