# Knee biomechanics, pathologies, rehab
from __future__ import annotations
from typing import Any

RB = "Neumann DA. Kinesiology of the Musculoskeletal System."
RC = "Magee DJ. Orthopedic Physical Assessment. Brukner & Khan Clinical Sports Medicine."


def bio(id_, movement, plane, axis, primary, secondary, stab, arthro, osteo, jrf, torque, lt, emg,
        func, sport, comp, dys, assess, corr) -> dict[str, Any]:
    return {
        "ID": id_, "Movement": movement, "Plane": plane, "Axis": axis,
        "Primary Movers": primary, "Secondary Movers": secondary, "Stabilizers": stab,
        "Arthrokinematics": arthro, "Osteokinematics": osteo, "Joint Reaction Forces": jrf,
        "Torque": torque, "Length-Tension": lt, "EMG": emg, "Functional Activities": func,
        "Sport Applications": sport, "Compensations": comp, "Common Dysfunctions": dys,
        "Clinical Assessment": assess, "Corrective Exercises": corr,
        "References": f"{RB} {RC}",
    }


BIOMECHANICS_RECORDS: list[tuple[str, dict[str, Any]]] = [
    ("Walking", bio(
        "KNEE-BIO-01", "Walking gait — knee", "Sagittal primary", "Transepicondylar approximate",
        "Quadriceps early stance; hamstrings late swing; gastroc/soleus",
        "Popliteus unlock; hip abductors for alignment", "ACL/PCL/collaterals passive; menisci load share",
        "Screw-home into extension; flexion with femoral roll-glide pattern",
        "Stance flexion ~15-20 deg; swing flexion ~60 deg typical",
        "Often about 2-3x BW peak (model-dependent)", "Extensor then flexor moments phasic",
        "Quad works near mid-length early stance", "Phasic low-moderate vs running",
        "Community ambulation", "Base for RTS progressions",
        "Stiff-knee gait; vaulting; antalgic shortened stance", "OA limited extension; quad weakness",
        "Observational gait; ROM; strength", "Gait drill, quad strength, extension mobility",
    )),
    ("Running", bio(
        "KNEE-BIO-02", "Running", "Multiplanar", "Multi-joint",
        "Quads absorb; glutes/hamstrings propulsion coupling", "Gastroc; hip abductors",
        "ACL under rotational/valgus loads if poor mechanics",
        "Greater flexion excursions than walking; rapid transitions",
        "Flight + stance; cadence/stride tradeoff",
        "Often 4-8x BW estimates vary by speed/style", "High extensor demand early stance",
        "Tendon energy storage important", "High burst EMG",
        "Fitness/field running", "All running sports",
        "Overstride; dynamic valgus; crossover gait", "PFPS, ITBS, tendinopathy, bone stress",
        "Video gait; step rate; pain map", "Cadence cues, run-walk, hip/quad capacity",
    )),
    ("Sprinting", bio(
        "KNEE-BIO-03", "Sprinting", "Sagittal dominant", "Multi-joint",
        "Hamstrings late swing; iliopsoas/RF swing; glute propulsion", "Gastroc push-off",
        "ACL risk on plant/cut more than pure straight sprint; hamstring high risk",
        "Rapid flexion-extension; extreme angular velocities",
        "Max velocity mechanics", "Very high soft-tissue loads",
        "Huge hamstring eccentric torque late swing", "Lengthening hamstrings vulnerable",
        "Max EMG hamstring late swing", "Track sprinting", "Athletics, field sport speed",
        "Early overstride; anterior pelvic tilt excess", "Hamstring strain",
        "Sprint mechanics video; Nordic capacity", "Askling drills, progressive exposures",
    )),
    ("Jumping", bio(
        "KNEE-BIO-04", "Jump takeoff", "Sagittal", "Multi-joint",
        "Quads, glutes, plantarflexors triple extension", "Hamstring co-contraction",
        "Extensor mechanism / patellar tendon high load",
        "Rapid extension from countermovement flexion", "CMJ pattern",
        "Multiple x BW", "High knee extensor torque", "Tendon spring contribution",
        "Explosive quad/glute EMG", "Jump sports", "Basketball/volleyball",
        "Knee-only strategy without hip", "Tendinopathy risk if volume spike",
        "CMJ testing", "Strength base then plyometric ladder",
    )),
    ("Landing", bio(
        "KNEE-BIO-05", "Jump landing", "Multiplanar", "Multi-joint",
        "Eccentric quads/glutes", "Hamstrings; hip ERs/abductors",
        "ACL vulnerable with valgus + IR + shallow flexion",
        "Rapid flexion with controlled rotation", "Soft vs stiff landing strategies",
        "Very high transient loads", "Frontal plane moments linked to ACL risk",
        "Quad eccentric dominant", "High eccentric EMG",
        "Drop land, cut decelerations", "All jump-land sports",
        "Stiff land; dynamic valgus; hip drop", "ACL, PFPS",
        "Drop-jump assessment", "Soft-land cues, hip strategy, single-leg progressions",
    )),
    ("Squat", bio(
        "KNEE-BIO-06", "Squat", "Sagittal dominant", "Multi-joint",
        "Quads and glutes", "Adductors deep; erectors trunk",
        "Menisci/ACL depending on depth/valgus",
        "Tibiofemoral roll-glide with depth; PF contact rises with flexion",
        "Coupled hip-knee-ankle flexion", "PF and TF forces rise with depth/load",
        "Knee extensor moment increases with forward knee travel (style-dependent)",
        "Quad lengthens under load", "High VL/VM EMG",
        "ADLs sit-to-stand", "Strength training",
        "Knee valgus; heel rise; lumbar flexion", "PF pain deep squat; meniscal symptoms",
        "Bodyweight squat screen", "Box squat to tolerable depth; tempo; hip hinge mix",
    )),
    ("Lunge", bio(
        "KNEE-BIO-07", "Lunge", "Sagittal + frontal control", "Multi-joint",
        "Lead-leg quad/glute", "Trail hip flexor; adductors",
        "Frontal knee alignment critical",
        "Lead knee flexion with tibial translation control", "Split-stance osteokinematics",
        "High PF demand on lead limb", "Unilateral extensor torque",
        "Similar to single-leg squat demands", "Unilateral EMG high",
        "Stairs, running mechanics prep", "Field sport strength",
        "Lead knee valgus; trunk lean", "PFPS, patellar tendinopathy if overloaded",
        "Forward/reverse lunge quality", "Short-range → full; trunk upright cues",
    )),
    ("Cutting", bio(
        "KNEE-BIO-08", "Cutting / COD", "Multiplanar", "Multi-joint",
        "Quads decelerate; glute med/max; adductors", "Hamstrings; trunk",
        "ACL and MCL high demand with valgus/rotation",
        "Rapid plant-limb flexion with tibial rotation", "Direction change",
        "High combined loads", "Large frontal/transverse moments",
        "Plant limb at vulnerable lengths", "High co-contraction EMG",
        "Evasion", "Football, soccer, basketball",
        "Lateral trunk lean; stiff plant; knee collapse", "ACL injury mechanism",
        "COD tests; 2D frontal projection", "Technique + strength + plyometrics + graded COD",
    )),
    ("Pivoting", bio(
        "KNEE-BIO-09", "Pivoting", "Transverse dominant", "Longitudinal tibial/femoral",
        "Hamstrings rotational control; popliteus; quads", "Hip rotators",
        "ACL primary rotational stabilizer",
        "Tibial IR/ER on femur with flexed knee", "Pivot on planted foot",
        "High shear/rotation", "Rotational torque through knee",
        "Depends on flexion angle", "PLC/ACL related activation",
        "Court sports turns", "Soccer, skiing",
        "Kneeing-in; spinning on locked knee", "ACL tear, meniscal tear",
        "Pivot shift clinically (laxity); movement quality", "Rotational control progressions after ACLR",
    )),
    ("Stair Climbing", bio(
        "KNEE-BIO-10", "Stair ascent/descent", "Sagittal", "Multi-joint",
        "Ascent: concentric quad/glute. Descent: eccentric quad", "Hip abductors",
        "High PF joint stress especially descent",
        "Greater knee flexion than level walking", "Step-over-step patterns",
        "PF forces often high on descent (study-dependent multiples of BW)",
        "Large eccentric knee extensor torque descending", "Quad eccentrically loaded",
        "High VM/VL EMG", "ADLs", "Stadium training",
        "Step-to pattern; handrail lean; leading with same leg", "PFPS, OA pain",
        "Step-down test; pain mapping", "Step-ups/downs progressive; hip strength; cadence",
    )),
]


def path(id_, cond, definition, mech, risk, sx, red, ddx, exam, tests, img, heal, cons, surg,
         rehab, rtr, rts, prog, guide, evid) -> dict[str, Any]:
    return {
        "ID": id_, "Condition": cond, "Definition": definition, "Mechanism": mech,
        "Risk Factors": risk, "Symptoms": sx, "Red Flags": red, "Differential Diagnosis": ddx,
        "Clinical Examination": exam, "Special Tests": tests, "Imaging": img,
        "Healing Timeline": heal, "Conservative Management": cons, "Surgical Management": surg,
        "Rehabilitation Phases": rehab, "Return to Running": rtr, "Return to Sport": rts,
        "Prognosis": prog, "Clinical Guidelines": guide, "Evidence Level": evid,
        "References": f"{RC} Specialty consensus literature as noted in guidelines field.",
    }


PATHOLOGY_RECORDS: list[tuple[str, dict[str, Any]]] = [
    ("ACL Tear", path(
        "KNEE-PATH-01", "ACL tear",
        "Partial or complete disruption of ACL fibers with anterior-rotational laxity",
        "Noncontact pivot (deceleration, cut, land) most common; contact valgus also",
        "Female sex (sport-specific), prior ACL, cutting sports, neuromuscular factors, anatomy (notch, slope) debated contributors",
        "Pop, rapid effusion, giving-way, loss of confidence in cutting",
        "Locked knee (bucket-handle), fracture, neurovascular injury, multi-ligament/dislocation",
        "MCL, meniscus, patellar dislocation, PCL",
        "Effusion, ROM, Lachman, pivot, associated structures",
        "Lachman, pivot shift, anterior drawer",
        "MRI confirms; radiographs for Segond/fracture",
        "Does not reliably heal complete midsubstance tears; graft maturation many months after ACLR",
        "Coper algorithm, bracing, progressive NMC rehab for selected patients",
        "ACLR (autograft BTB/hamstring/quad) for instability/sport; repair selected proximal tears evolving evidence",
        "Early ROM/quad → strength → plyometrics → COD → RTS testing",
        "Often after 3-4+ months if criteria met post-ACLR — individualize",
        "Commonly 9-12+ months with passing criteria; reinjury risk if early",
        "Good with appropriate surgery/rehab; osteoarthritis risk long-term still elevated",
        "AAOS/AOSSM-aligned shared decision themes; criteria-based RTS literature",
        "Strong evidence for Lachman/MRI diagnosis; RTS criteria reduce but do not eliminate reinjury",
    )),
    ("PCL Tear", path(
        "KNEE-PATH-02", "PCL tear",
        "Disruption of PCL with posterior tibial laxity",
        "Dashboard; fall on flexed knee plantarflexed foot",
        "High-energy trauma; combined PLC",
        "Vague posterior pain, difficulty deceleration, posterior sag",
        "Multi-ligament, vascular injury if dislocation history",
        "PLC, ACL, posteromedial pain generators",
        "Posterior drawer/sag, quad active test, dial",
        "Posterior drawer, sag, dial",
        "MRI; stress radiography selected",
        "Many isolated grade I-II improve over 6-12 weeks protected rehab",
        "Extension bracing early, quad focus, avoid early isolated hamstring shear",
        "Grade III/combined/bony avulsion may need surgery",
        "Protect posterior sag → progressive strength → functional",
        "When effusion/strength/control allow",
        "Criteria-based; longer if reconstructed",
        "Generally favorable for isolated treated appropriately",
        "PCL management reviews",
        "Moderate — many recommendations consensus-based",
    )),
    ("MCL Injury", path(
        "KNEE-PATH-03", "MCL injury",
        "Sprain/tear of superficial ± deep MCL",
        "Valgus force; cutting",
        "Contact sports; ACL concomitant",
        "Medial pain, valgus stress pain, mild-moderate laxity",
        "Multi-ligament; fracture; locked knee",
        "Medial meniscus, pes bursitis, medial tibial plateau fracture",
        "Valgus stress 0/30, joint line exam",
        "Valgus stress test",
        "MRI if high grade/unsure/concomitant; US adjunct",
        "Grade I-II often 1-6 weeks; III longer",
        "Hinged brace, early ROM, progressive loading — excellent healing",
        "Rare except Stener-like distal / multi-ligament",
        "Protect valgus early → strength → COD",
        "When pain/laxity allow jog progression",
        "Grade-dependent weeks to months",
        "Excellent for isolated",
        "Standard sports medicine MCL pathways",
        "Good clinical consensus evidence for nonop grade I-II",
    )),
    ("LCL Injury", path(
        "KNEE-PATH-04", "LCL injury",
        "Sprain/tear of LCL often with PLC",
        "Varus trauma",
        "High-energy; thin LCL anatomy",
        "Lateral pain, varus laxity",
        "PLC, common fibular nerve, vascular if high energy",
        "ITBS, meniscus, PTFJ",
        "Varus stress, dial, nerve exam",
        "Varus stress, dial, posterolateral drawer",
        "MRI; radiographs for arcuate sign",
        "Low grade weeks; grade III often surgical timeline months",
        "Brace protection for low grade",
        "Often reconstruct if grade III/PLC",
        "Protect varus → rotational control → RTS",
        "Delayed until stability restored",
        "Months if surgical",
        "Depends on PLC recognition",
        "LaPrade-aligned PLC approach",
        "Moderate evidence; anatomy-driven",
    )),
    ("Meniscal Tear", path(
        "KNEE-PATH-05", "Meniscal tear",
        "Disruption of medial or lateral meniscal fibrocartilage",
        "Twist on flexed planted foot; degenerative cleavage",
        "ACL injury, age, squatting sports, discoid lateral",
        "Joint-line pain, clicking, locking, effusion intermittent",
        "True locking with loss of extension — urgent ortho; infection signs",
        "PFPS, plica, OCD, loose body",
        "Joint-line tenderness, Thessaly, McMurray",
        "McMurray, Thessaly, Apley",
        "MRI; radiographs for OA",
        "Vascular zone dependent; degenerative may stabilize symptomatically",
        "Exercise therapy first-line many degenerative tears (trial evidence)",
        "Repair if feasible; partial meniscectomy if irreparable; avoid unnecessary meniscectomy in degenerative OA",
        "Repair-protected vs meniscectomy accelerated pathways",
        "Earlier after meniscectomy; delayed after repair",
        "Criteria + surgery-specific",
        "Better if repaired when appropriate; OA risk after meniscectomy",
        "ESSKA/AAOS-aligned meniscus preservation themes",
        "Stronger evidence favoring conservative care for many degenerative tears",
    )),
    ("Patellofemoral Pain Syndrome", path(
        "KNEE-PATH-06", "Patellofemoral pain syndrome (PFPS)",
        "Anterior knee pain related to PF joint without other specific pathology explaining symptoms",
        "Load exceeding capacity; training errors; movement factors multifactorial",
        "Adolescents/young adults, females, runners, weak hip/quad, abrupt load spikes",
        "Diffuse anterior pain with stairs, squats, prolonged sitting (theater sign)",
        "True locking, significant effusion, night pain systemic — reassess diagnosis",
        "Tendinopathy, fat pad, plica, OA, referred hip",
        "Step-down, squat, palpation, flexibility, hip strength",
        "Limited specific tests; functional pain reproduction more useful",
        "Usually clinical; imaging to exclude other pathology",
        "Symptoms often improve over weeks–months with active care",
        "Education, load management, hip + quad exercise (best evidence)",
        "Rare — only for specific structural problems not PFPS per se",
        "Symptom-guided progressive loading + movement retraining",
        "Graded return with pain rules",
        "When training loads tolerated",
        "Good with active rehab; recurrent if load mismanaged",
        "PFPS consensus statements (e.g. British Journal of Sports Medicine consensus themes)",
        "Strong evidence for exercise therapy",
    )),
    ("Patellar Tendinopathy", path(
        "KNEE-PATH-07", "Patellar tendinopathy",
        "Overuse insertional/proximal patellar tendon pain and dysfunction (continuum model)",
        "Energy-storage overload (jumping); sudden volume increase",
        "Jump sports, males historically higher in some cohorts, limited ankle DF, high BMI debated",
        "Localized inferior pole pain, load-related, morning stiffness mild",
        "Rupture signs (rare); apophyseal pain in youth = Osgood not adult tendinopathy",
        "PFPS, fat pad, Osgood (youth), SLJ",
        "Decline squat pain, palpation proximal tendon",
        "Royal London / decline squat clinical",
        "US/MRI if unclear or refractory",
        "Collagen remodeling months — not 2-week fix",
        "Progressive tendon loading (isometrics → HSR → plyometrics); education",
        "Rare for pure tendinopathy",
        "Pain-monitoring progressive loading phases",
        "When energy-storage drills tolerated",
        "Gradual return to jump volume",
        "Good but often prolonged",
        "Cook & Purdam / Malliaras loading frameworks",
        "Good evidence for progressive loading over passive-only care",
    )),
    ("Quadriceps Tendinopathy", path(
        "KNEE-PATH-08", "Quadriceps tendinopathy",
        "Pain/dysfunction of quadriceps tendon typically at patellar base",
        "Overload of extensor mechanism",
        "Jumping/lifting sports; age-related degeneration",
        "Superior pole/patellar base pain with loading",
        "Extensor lag / palpable gap suggests rupture",
        "PFPS, bursitis, partial tear",
        "Palpation, resisted extension pain",
        "Functional loading tests",
        "US/MRI",
        "Months with progressive loading",
        "Load management + progressive strengthening",
        "If rupture — repair",
        "Similar tendon continuum phases",
        "When pain allows impact",
        "Criteria-based",
        "Favorable if not ruptured",
        "Tendinopathy management principles",
        "Moderate evidence extrapolated from patellar tendon literature",
    )),
    ("Osgood-Schlatter Disease", path(
        "KNEE-PATH-09", "Osgood-Schlatter disease",
        "Traction apophysitis of tibial tuberosity in growing athletes",
        "Repetitive quad traction on open tibial tubercle apophysis",
        "Ages ~10-15, sports with running/jumping, growth spurts",
        "Activity-related tuberosity pain/swelling; prominence",
        "Fever/redness infection; night pain tumor rare but consider if atypical",
        "Patellar tendinopathy, SLJ, fracture, infection",
        "Tenderness over tibial tuberosity; pain with resisted extension",
        "Clinical diagnosis primarily",
        "Radiographs if atypical; avoid over-imaging",
        "Self-limited with skeletal maturity months–years; symptoms wax/wane",
        "Load modification, ice, quad/hip strength, flexibility; rarely cast",
        "Rare — only complications/ossicle refractory selected",
        "Symptom-guided activity; maintain fitness cross-train",
        "When symptoms allow — not forced through severe pain",
        "Usually before skeletal maturity ends symptoms",
        "Excellent long-term",
        "Pediatric sports medicine standard care",
        "Good observational/clinical consensus evidence",
    )),
    ("Sinding-Larsen-Johansson Syndrome", path(
        "KNEE-PATH-10", "Sinding-Larsen-Johansson syndrome",
        "Traction apophysitis of inferior patellar pole in youth",
        "Repetitive traction at proximal patellar tendon attachment on immature pole",
        "Young jumping athletes",
        "Inferior pole pain with loading",
        "Atypical systemic signs",
        "Patellar tendinopathy, Osgood, fracture",
        "Point tenderness inferior pole",
        "Clinical",
        "Radiograph/MRI if needed",
        "Self-limited with growth/load management",
        "Activity modification and progressive loading",
        "Rare",
        "Symptom-guided",
        "Graded",
        "When tolerated",
        "Excellent",
        "Pediatric overuse guidelines",
        "Consensus clinical evidence",
    )),
    ("IT Band Syndrome", path(
        "KNEE-PATH-11", "Iliotibial band syndrome",
        "Lateral knee pain related to ITB–lateral femoral epicondyle region (impingement/compression paradigm evolving)",
        "Repetitive knee flexion-extension around 20-30 deg (running)",
        "Runners, sudden volume increase, hip abductor weakness, cadence/stride factors",
        "Sharp lateral pain that worsens with distance; often at same distance",
        "Locked knee, significant swelling — reconsider",
        "LCL, lateral meniscus, PF pain referral",
        "Noble compression, Ober (limited specificity), single-leg stance pelvic control",
        "Noble test classic but interpret cautiously",
        "Clinical primarily; MRI excludes other",
        "Weeks with load modification typically",
        "Reduce running load, cadence increase, hip abductor endurance, progressive return",
        "Not indicated for primary ITBS",
        "Load → capacity → graded running",
        "Run-walk then continuous",
        "When training distances pain-tolerable",
        "Good",
        "Running injury management reviews",
        "Moderate evidence for load and hip strengthening",
    )),
    ("Baker's Cyst", path(
        "KNEE-PATH-12", "Baker's (popliteal) cyst",
        "Fluid-filled enlargement in popliteal bursa often communicating with knee joint",
        "Secondary to effusion from OA, meniscal tear, inflammatory arthritis",
        "OA, meniscal pathology, inflammatory disease",
        "Popliteal swelling/fullness; stiffness; rupture causes calf pain",
        "DVT must be excluded if acute calf swelling/pain; infection",
        "DVT, soft-tissue tumor (rare), gastroc strain",
        "Popliteal mass; knee effusion exam",
        "Clinical + US",
        "US first; MRI for intra-articular drivers",
        "Tracks underlying disease; may persist",
        "Treat intra-articular cause; aspiration/CSI selective",
        "Rare cyst excision; address meniscus/OA as indicated",
        "Effusion control and strength for underlying knee",
        "Per underlying condition",
        "Per underlying condition",
        "Depends on driver",
        "Standard ortho pathways",
        "Good diagnostic evidence for US vs DVT workflow",
    )),
    ("Osteoarthritis", path(
        "KNEE-PATH-13", "Knee osteoarthritis",
        "Degenerative joint disease of TF and/or PF compartments",
        "Cumulative load, injury legacy (ACL/meniscus), age, alignment, obesity",
        "Age, prior injury, obesity, female sex (some cohorts), genetics",
        "Activity pain, stiffness <30-60 min, crepitus, swelling, reduced function",
        "Night pain severe, fever, rapid hot swelling — infection/crystal/tumor workup",
        "Meniscal symptoms, referred hip, inflammatory arthritis",
        "Alignment, ROM, crepitus, effusion, function scores",
        "No single special test — clinical + imaging",
        "Weight-bearing radiographs (Kellgren-Lawrence); MRI if atypical",
        "Chronic progressive; flares weeks",
        "Exercise, weight loss, education first-line (OARSI/NICE themes); injections selective",
        "Osteotomy selected; arthroplasty when indicated",
        "Flare control → progressive strength → activity pacing",
        "As tolerated with symptom rules",
        "Activity goals not always competitive sport",
        "Variable; function improvable without reversing structure",
        "OARSI / NICE osteoarthritis guidelines themes",
        "Strong evidence for exercise and weight loss",
    )),
    ("Plica Syndrome", path(
        "KNEE-PATH-14", "Plica syndrome",
        "Symptomatic synovial plica (often mediopatellar) causing pain/clicking",
        "Inflamed plica snapping over medial femoral condyle",
        "Trauma, overuse, immature PF tracking issues",
        "Medial pain, clicking, theater sign overlap with PFPS",
        "Locking true mechanical — meniscus/loose body",
        "PFPS, medial meniscus, fat pad",
        "Medial parapatellar tenderness; stutter test limited value",
        "Clinical diagnosis of exclusion often",
        "MRI may show plica but poor specificity",
        "Weeks–months",
        "Load modification, flexibility, quad/hip exercise, injection rare",
        "Arthroscopic resection if refractory after failed conservative",
        "As PFPS-like progressive loading",
        "Graded",
        "When symptoms settle",
        "Good if correctly selected surgical cases after failed care",
        "Clinical reviews",
        "Limited high-level evidence; diagnosis challenging",
    )),
    ("Osteochondritis Dissecans", path(
        "KNEE-PATH-15", "Osteochondritis dissecans (OCD)",
        "Idiopathic subchondral bone lesion with possible fragment instability — classic medial femoral condyle in youth",
        "Multifactorial — ischemia/repetitive stress theories",
        "Juvenile athletes, males historically, repetitive impact",
        "Activity pain, swelling, catching if loose fragment",
        "Locked knee from loose body; infection signs",
        "Meniscal tear, normal growing pain, AVN adult",
        "Wilson test historically limited; effusion; mechanical symptoms",
        "Clinical suspicion + imaging",
        "Radiographs (notch view); MRI staging stability",
        "Juvenile open physis better healing; adult poorer",
        "Activity modification, unloading for stable juvenile lesions",
        "Fixation/drilling/restore cartilage for unstable lesions",
        "Protect WB per stage → progressive impact",
        "Delayed until healing evidence",
        "Delayed; criteria + imaging",
        "Better in juvenile stable lesions",
        "Pediatric ortho OCD pathways",
        "Moderate evidence; staging-guided",
    )),
]

REHAB_RECORDS: list[tuple[str, dict[str, Any]]] = [
    ("ACL Reconstruction — Early Phase", {
        "ID": "KNEE-REHAB-01", "Condition": "ACL reconstruction", "Rehabilitation Phase": "Early (approx 0-6 weeks — protocol-dependent)",
        "Goals": "Protect graft, full extension, quad activation, control effusion, gait with crutches as needed",
        "Pain Management": "Ice, elevation, analgesics per physician, effusion control",
        "Weight Bearing Status": "Usually WBAT with crutches unless concomitant meniscal repair/osteotomy dictates otherwise",
        "ROM Goals": "Full extension ASAP; flexion progressive to 90+ per protocol",
        "Strength Goals": "Quad sets, SLR without lag, NMES if AMI",
        "Motor Control": "Terminal knee control; avoid uncontrolled pivoting",
        "Balance Training": "Bilateral weight shift → bilateral stance",
        "Proprioception": "Early gentle joint position as effusion allows",
        "Functional Training": "ADL gait, step-to stairs",
        "Sport-Specific Progression": "None yet",
        "Criteria to Progress": "Full extension, SLR no lag, effusion controlled, flexion milestones met",
        "Return to Running": "Not in this phase",
        "Return to Sport": "Not in this phase",
        "Outcome Measures": "IKDC, Lysholm, pain NPRS, effusion grade, quad lag",
        "Clinical Guidelines": "Criterion-based ACLR rehab frameworks",
        "Evidence": "Early extension and quad activation strongly supported to reduce arthrofibrosis",
        "References": RC + " ACLR rehab consensus literature.",
    }),
    ("ACL Reconstruction — Intermediate/Late Strength", {
        "ID": "KNEE-REHAB-02", "Condition": "ACL reconstruction", "Rehabilitation Phase": "Intermediate to late strength (approx 6 weeks-6 months)",
        "Goals": "Strength symmetry progress, single-leg control, aerobic base",
        "Pain Management": "Monitor delayed onset pain; adjust volume",
        "Weight Bearing Status": "Full",
        "ROM Goals": "Full symmetrical ROM",
        "Strength Goals": "Progress closed chain; hamstring carefully per graft; aim toward >80-90% LSI before advanced plyometrics",
        "Motor Control": "Single-leg squat quality; land mechanics foundation",
        "Balance Training": "Single-leg stance progressions",
        "Proprioception": "Perturbation training progressive",
        "Functional Training": "Step-downs, bridges, bike/swim",
        "Sport-Specific Progression": "Linear movement preparation late in window",
        "Criteria to Progress": "Strength LSI thresholds, hop test readiness, no effusion with load",
        "Return to Running": "Often around 3-4+ months if criteria met",
        "Return to Sport": "Not yet — build capacity",
        "Outcome Measures": "Isokinetic/HHD LSI, hop battery, ACL-RSI",
        "Clinical Guidelines": "Criteria-based progression",
        "Evidence": "Strength and hop symmetry associated with better RTS outcomes",
        "References": RC + " Grindem/Kyritsis RTS criteria literature.",
    }),
    ("ACL Reconstruction — RTS Phase", {
        "ID": "KNEE-REHAB-03", "Condition": "ACL reconstruction", "Rehabilitation Phase": "Return to sport (often 9-12+ months)",
        "Goals": "Pass RTS battery; graded COD/contact exposure; psychological readiness",
        "Pain Management": "Should be minimal with high loads",
        "Weight Bearing Status": "Full",
        "ROM Goals": "Full",
        "Strength Goals": "Quad LSI often ≥90% recommended in many protocols",
        "Motor Control": "Cut/land quality under fatigue",
        "Balance Training": "Sport-specific unstable/chaotic",
        "Proprioception": "Reactive agility",
        "Functional Training": "Full practice participation graded",
        "Sport-Specific Progression": "Noncontact → contact; partial → full play",
        "Criteria to Progress": "Time + criteria (strength, hops, movement, ACL-RSI)",
        "Return to Running": "Already achieved earlier",
        "Return to Sport": "Clearance shared decision with surgeon/team",
        "Outcome Measures": "RTS test battery, ACL-RSI, reinjury tracking",
        "Clinical Guidelines": "Do not use time alone",
        "Evidence": "Passing criteria reduces but does not eliminate second injury risk",
        "References": "RTS criteria papers; " + RC,
    }),
    ("Meniscal Repair Rehab", {
        "ID": "KNEE-REHAB-04", "Condition": "Meniscal repair", "Rehabilitation Phase": "Protected healing then progressive (protocol-specific 0-4/6 weeks restricted often)",
        "Goals": "Protect repair, limit shear/deep flexion early per surgeon",
        "Pain Management": "Effusion control",
        "Weight Bearing Status": "NWB/PWB/WBAT varies by tear type/repair — follow surgeon",
        "ROM Goals": "Often limited flexion early (e.g. 0-90) then progress",
        "Strength Goals": "Quad activation early; avoid early weighted deep squat",
        "Motor Control": "Gait restoration when WB allows",
        "Balance Training": "When WB allows",
        "Proprioception": "Progressive",
        "Functional Training": "ADL first",
        "Sport-Specific Progression": "Delayed vs meniscectomy",
        "Criteria to Progress": "Surgeon milestones + effusion/pain",
        "Return to Running": "Often 3-4+ months",
        "Return to Sport": "Often 4-6+ months",
        "Outcome Measures": "Pain, effusion, IKDC",
        "Clinical Guidelines": "Repair protection principles",
        "Evidence": "Protocols vary — communicate with surgeon essential",
        "References": RC,
    }),
    ("PFPS Rehab", {
        "ID": "KNEE-REHAB-05", "Condition": "Patellofemoral pain", "Rehabilitation Phase": "Active rehabilitation (weeks to months)",
        "Goals": "Reduce pain, restore capacity, return to desired activity",
        "Pain Management": "Load adjustment; relative rest from aggravators not complete rest",
        "Weight Bearing Status": "Full as tolerated",
        "ROM Goals": "Full; address restrictions if present",
        "Strength Goals": "Quad + hip abductor/ER progressive resistance",
        "Motor Control": "Step-down and squat mechanics",
        "Balance Training": "Single-leg control",
        "Proprioception": "Task-specific",
        "Functional Training": "Stairs, sit-to-stand graded",
        "Sport-Specific Progression": "Run/jump volume graded with pain rules",
        "Criteria to Progress": "Pain stable with increased load",
        "Return to Running": "Walk-run with symptom monitoring",
        "Return to Sport": "When training loads match sport demands",
        "Outcome Measures": "AKPS/Kujala, NPRS, functional step-down",
        "Clinical Guidelines": "PFPS consensus — exercise first-line",
        "Evidence": "Strong for combined hip+knee exercise",
        "References": "BJSM PFPS consensus themes. " + RC,
    }),
    ("Patellar Tendinopathy Rehab", {
        "ID": "KNEE-REHAB-06", "Condition": "Patellar tendinopathy", "Rehabilitation Phase": "Progressive tendon loading continuum",
        "Goals": "Improve load tolerance of tendon and kinetic chain",
        "Pain Management": "Isometrics for analgesia; pain-monitoring model (e.g. ≤3-5/10 acceptable if settles)",
        "Weight Bearing Status": "Full",
        "ROM Goals": "Ankle DF and hip mobility as needed",
        "Strength Goals": "Heavy slow resistance 3-4x/week then energy storage",
        "Motor Control": "Landing mechanics",
        "Balance Training": "Single-leg landing prep",
        "Proprioception": "Jump-land awareness",
        "Functional Training": "Decline squat progressions",
        "Sport-Specific Progression": "Jump counts graded",
        "Criteria to Progress": "Pain rules + strength + plyometric tolerance",
        "Return to Running": "When tendon tolerates impact volume",
        "Return to Sport": "When sport-specific energy storage tolerated repeatedly",
        "Outcome Measures": "VISA-P, pain map, hop/jump load",
        "Clinical Guidelines": "Cook & Purdam / Malliaras frameworks",
        "Evidence": "Progressive loading superior to passive-only approaches",
        "References": "Cook & Purdam; Malliaras. " + RC,
    }),
    ("MCL Injury Rehab", {
        "ID": "KNEE-REHAB-07", "Condition": "MCL sprain", "Rehabilitation Phase": "Protected motion to RTS (grade-dependent)",
        "Goals": "Allow ligament healing, restore ROM/strength, return without valgus apprehension",
        "Pain Management": "Brace comfort, ice early",
        "Weight Bearing Status": "WBAT usually in hinged brace",
        "ROM Goals": "Early ROM in brace; avoid forcing valgus",
        "Strength Goals": "Quad/hip; progressive frontal plane",
        "Motor Control": "Frontal knee control",
        "Balance Training": "Progressive",
        "Proprioception": "Progressive",
        "Functional Training": "Bike, swim, linear run before COD",
        "Sport-Specific Progression": "Shielded contact → full",
        "Criteria to Progress": "Painless valgus stress, strength, hop",
        "Return to Running": "When walking pain-free and brace plan allows",
        "Return to Sport": "Grade I weeks; III often 6-12+ weeks",
        "Outcome Measures": "Pain, laxity grade, function",
        "Clinical Guidelines": "Nonoperative MCL pathways",
        "Evidence": "Good healing with early motion for most",
        "References": RC,
    }),
    ("Knee OA Rehab", {
        "ID": "KNEE-REHAB-08", "Condition": "Knee osteoarthritis", "Rehabilitation Phase": "Long-term self-management with flares",
        "Goals": "Function, pain control, delay/optimize surgical timing if needed",
        "Pain Management": "Activity pacing, ice/heat, medications per physician, injections selective",
        "Weight Bearing Status": "Full; assistive device if helpful; unloader brace selected",
        "ROM Goals": "Maintain extension and functional flexion",
        "Strength Goals": "Quad and hip strength cornerstone",
        "Motor Control": "Sit-to-stand, stair strategies",
        "Balance Training": "Fall prevention",
        "Proprioception": "Stable stance tasks",
        "Functional Training": "Walking program, cycling",
        "Sport-Specific Progression": "Modify impact as needed",
        "Criteria to Progress": "Symptom-guided increases",
        "Return to Running": "Individual — many switch to lower impact; some tolerate graded run",
        "Return to Sport": "Participation goals individualized",
        "Outcome Measures": "WOMAC, KOOS, 30-sec chair stand",
        "Clinical Guidelines": "OARSI/NICE — education, exercise, weight loss first-line",
        "Evidence": "Strong for exercise and weight loss",
        "References": "OARSI/NICE OA themes. " + RC,
    }),
]

EVIDENCE_RECORDS: list[tuple[str, dict[str, Any]]] = [
    ("Key Evidence and Guidelines — Knee Module", {
        "ID": "KNEE-EVID-01",
        "Topic": "Foundational references for Kinora knee AI orientation",
        "Anatomy": "Standring S. Gray's Anatomy. Moore KL. Netter FH.",
        "Biomechanics": RB,
        "Assessment": RC,
        "ACL": "AAOS/AOSSM-aligned themes; criteria-based RTS literature (e.g. Grindem, Kyritsis, ACL-RSI).",
        "Meniscus": "Meniscus preservation and exercise-first evidence for many degenerative tears.",
        "PFPS": "BJSM consensus themes — hip + knee exercise, education, load management.",
        "Tendinopathy": "Cook & Purdam continuum; Malliaras progressive loading; VISA-P.",
        "OA": "OARSI / NICE osteoarthritis guideline themes — exercise and weight loss first-line.",
        "Vascular": "Knee dislocation — urgent vascular assessment protocols.",
        "AI Use Note": "ROM values, force multiples, and timelines are approximate and protocol-dependent. Prefer current surgeon protocols and individual assessment.",
        "References": "See fields above.",
    }),
]
