# Clinical data module for Kinora Knee PDF — educational synthesis from standard sources.
from __future__ import annotations
from typing import Any

RA = "Standring S. Gray's Anatomy. Moore KL et al. Clinically Oriented Anatomy. Netter FH."
RB = "Neumann DA. Kinesiology of the Musculoskeletal System."
RC = "Magee DJ. Orthopedic Physical Assessment. Brukner & Khan Clinical Sports Medicine."

BONE_RECORDS: list[tuple[str, dict[str, Any]]] = [
    ("Femur (Distal)", {
        "ID": "KNEE-BONE-01",
        "Bone": "Distal femur — medial and lateral condyles, intercondylar notch, trochlear groove",
        "Region": "Knee — distal thigh / tibiofemoral and patellofemoral articulations",
        "Type": "Long bone (distal epiphysis and metaphysis)",
        "Landmarks": "Medial/lateral femoral condyles; medial/lateral epicondyles; adductor tubercle; intercondylar notch (ACL/PCL); trochlear (patellar) groove; popliteal surface; sulcus terminalis",
        "Articulations": "Tibial plateaus via menisci (tibiofemoral); patella (patellofemoral)",
        "Muscle Attachments": "Gastrocnemius (posterior condyles); plantaris; popliteus (lateral condyle groove); articularis genu; adductor magnus to adductor tubercle; collateral ligaments near epicondyles",
        "Ligament Attachments": "ACL (posteromedial lateral femoral condyle / notch wall); PCL (anterolateral medial femoral condyle); MCL (medial epicondyle); LCL (lateral epicondyle); MPFL (near medial epicondyle / adductor tubercle complex)",
        "Blood Supply": "Genicular anastomosis (superior medial/lateral genicular, middle genicular into notch); descending genicular; popliteal branches",
        "Venous Drainage": "Genicular veins → popliteal vein",
        "Innervation": "Capsular/periosteal branches from femoral, tibial, common fibular, obturator (variable genicular nerves)",
        "Biomechanical Role": "Convex femoral condyles roll and glide on tibia; trochlea guides patella; notch houses cruciate ligaments",
        "Load Transmission": "Compressive load through condyles to tibia; medial compartment often higher load in neutral alignment; PF load through trochlea",
        "Clinical Importance": "OA preferential medial compartment; notch stenosis and ACL graft impingement; distal femur fractures; OCD of medial femoral condyle in youth",
        "Common Fractures": "Supracondylar; intercondylar (AO/OTA distal femur); osteochondral fractures with patellar dislocation",
        "Healing Timeline": "Metaphyseal fractures often 8–16 weeks depending on fixation/stability; cartilage injuries longer and variable",
        "Imaging": "AP/lateral/notch/sunrise radiographs; CT for fracture mapping; MRI for ligaments/cartilage/OCD",
        "Rehabilitation Considerations": "Protect fracture fixation WB orders; early ROM if stable; quad activation; alignment and gait retraining",
        "References": f"{RA} {RB} {RC}",
    }),
    ("Tibia (Proximal)", {
        "ID": "KNEE-BONE-02",
        "Bone": "Proximal tibia — medial/lateral plateaus, intercondylar eminence, tibial tuberosity",
        "Region": "Knee — proximal leg",
        "Type": "Long bone (proximal epiphysis/metaphysis)",
        "Landmarks": "Medial/lateral tibial plateaus; tibial spines (eminence); Gerdy's tubercle; tibial tuberosity; pes anserinus insertion area; posterior tibial slope",
        "Articulations": "Femoral condyles (via menisci); proximal fibula (proximal tibiofibular joint); patellar tendon at tuberosity",
        "Muscle Attachments": "Pes anserinus (sartorius, gracilis, semitendinosus); semimembranosus expansions; ITB/TFL to Gerdy's; tibialis anterior nearby; popliteus inserts posteromedial tibia",
        "Ligament Attachments": "ACL (anterior intercondylar area); PCL (posterior intercondylar area); meniscal roots/horns; MCL distal tibial attachment; coronary ligaments to plateau margins",
        "Blood Supply": "Inferior genicular arteries; anterior/posterior tibial recurrent; nutrient vessels",
        "Venous Drainage": "Genicular and tibial veins → popliteal",
        "Innervation": "Infrapatellar branch of saphenous; tibial and common fibular genicular branches",
        "Biomechanical Role": "Concave plateaus (lateral more convex) receive femoral load; slope influences ACL strain and anterior tibial translation",
        "Load Transmission": "Medial plateau larger/thicker cartilage typically; menisci expand contact area; tuberosity transmits extensor mechanism force",
        "Clinical Importance": "Tibial plateau fractures (Schatzker); ACL tibial footprint; Osgood-Schlatter at tuberosity; slope in ACL failure risk discussions",
        "Common Fractures": "Tibial plateau (lateral most common); tibial eminence avulsion (pediatric ACL equivalent); tuberosity avulsion",
        "Healing Timeline": "Plateau fractures often 12+ weeks; articular depression needs anatomic restoration for OA prevention",
        "Imaging": "AP/lateral/oblique; CT for plateau depression/split; MRI for soft tissue and occult fracture",
        "Rehabilitation Considerations": "WB per plateau depression and fixation; early ROM critical; progressive strength; monitor alignment",
        "References": f"{RA} {RB} Schatzker classification literature. {RC}",
    }),
    ("Fibula (Proximal)", {
        "ID": "KNEE-BONE-03",
        "Bone": "Proximal fibula — fibular head and neck",
        "Region": "Lateral knee / proximal leg",
        "Type": "Long bone (proximal)",
        "Landmarks": "Fibular head; fibular neck (common fibular nerve winds around); styloid process (arcuate/PLC attachments)",
        "Articulations": "Proximal tibiofibular joint with lateral tibial condyle",
        "Muscle Attachments": "Biceps femoris to fibular head; soleus/peroneals more distal but relevant kinetic chain; fibularis longus origin nearby",
        "Ligament Attachments": "LCL to fibular head; popliteofibular ligament; arcuate complex / PLC structures; biceps femoris tendon continuity",
        "Blood Supply": "Inferior lateral genicular; anterior tibial recurrent; circumflex fibular branches",
        "Venous Drainage": "Accompanying veins to popliteal system",
        "Innervation": "Common fibular nerve closely related at neck — clinical landmark more than periosteal supply",
        "Biomechanical Role": "Lateral collateral and PLC anchor; proximal TFJ allows fibular rotation with ankle motion",
        "Load Transmission": "Minimal axial load vs tibia (~6–30% debated by study/condition); more ligamentous/lateral stabilizer role at knee",
        "Clinical Importance": "Common fibular nerve palsy at neck; Maisonneuve association; LCL/PLC injury with fibular head avulsion (arcuate sign)",
        "Common Fractures": "Fibular head/neck fracture; avulsion of styloid (arcuate sign on radiograph)",
        "Healing Timeline": "Typically 6–10 weeks if isolated; dictated by associated PLC/ankle injury",
        "Imaging": "AP/lateral knee including fibular head; MRI for PLC; assess nerve clinically",
        "Rehabilitation Considerations": "Screen foot drop; protect PLC repairs; progressive lateral stability training",
        "References": f"{RA} {RC} PLC injury reviews (LaPrade).",
    }),
    ("Patella", {
        "ID": "KNEE-BONE-04",
        "Bone": "Patella — largest sesamoid bone",
        "Region": "Anterior knee within extensor mechanism",
        "Type": "Sesamoid bone",
        "Landmarks": "Base (superior); apex (inferior — patellar tendon); anterior subcutaneous surface; posterior medial/lateral facets; odd facet (far medial)",
        "Articulations": "Femoral trochlea (patellofemoral joint)",
        "Muscle Attachments": "Quadriceps tendon inserts on base/anterior; vastus medialis/lateralis expansions (retinacula); patellar tendon from apex",
        "Ligament Attachments": "MPFL to medial patella; LPFL/lateral retinaculum; medial/lateral patellotibial and patellomeniscal ligaments (variable)",
        "Blood Supply": "Genicular anastomosis (esp. inferior medial/lateral genicular; supreme/descending genicular) — bipartite and AVN considerations after surgery",
        "Venous Drainage": "Prepatellar venous plexus → genicular/popliteal veins",
        "Innervation": "Infrapatellar branch of saphenous; femoral cutaneous contributions — neuroma risk after incision",
        "Biomechanical Role": "Increases quadriceps moment arm; centralizes extensor force; thickest cartilage in body on posterior surface",
        "Load Transmission": "PF joint reaction force rises with flexion and quad demand — often several × BW in deep squat/stairs (study-dependent)",
        "Clinical Importance": "PFPS; patellar dislocation/instability; chondromalacia; bipartite patella; fracture; Sinding-Larsen-Johansson at apex in youth",
        "Common Fractures": "Transverse (most common); stellate; osteochondral with dislocation",
        "Healing Timeline": "ORIF/nonop 6–12 weeks typical bony union window; cartilage sequelae longer",
        "Imaging": "AP/lateral/sunrise (Merchant/Laurin); MRI for cartilage/MPFL; CT for fracture comminution",
        "Rehabilitation Considerations": "Protect extensor mechanism repairs; progressive ROM; VMO/quad control without early aggressive deep loaded flexion if chondral injury",
        "References": f"{RA} {RB} {RC} PF biomechanics reviews.",
    }),
]

JOINT_RECORDS: list[tuple[str, dict[str, Any]]] = [
    ("Tibiofemoral Joint", {
        "ID": "KNEE-JNT-01",
        "Joint": "Tibiofemoral joint",
        "Type": "Modified hinge (bicondylar synovial) — flexion/extension with coupled rotation",
        "Capsule": "Fibrous capsule reinforced by collaterals, retinacula, oblique popliteal and arcuate ligaments; synovial lining with multiple recesses",
        "Articular Cartilage": "Hyaline cartilage on femoral condyles and tibial plateaus; thickness varies; menisci interposed",
        "Ligaments": "ACL, PCL, MCL, LCL; posteromedial and posterolateral corner complexes; coronary ligaments to menisci",
        "Menisci": "Medial and lateral menisci deepen tibial surface and distribute load",
        "Blood Supply": "Genicular anastomosis; middle genicular to cruciates",
        "Innervation": "Posterior articular nerve (tibial); genicular branches of femoral, common fibular, obturator — rich nociception/proprioception",
        "Arthrokinematics": "Flexion: femoral condyles roll posterior and glide anterior on tibia (open chain opposite described for tibia-on-femur). Screw-home: tibia ER on femur into terminal extension (open chain)",
        "Osteokinematics": "Flexion/extension primary; IR/ER increases with flexion; abduction/adduction minimal (collateral constrained)",
        "Normal ROM": "Extension 0 to slight hyperextension (~5 deg); flexion ~135–150 deg (soft tissue dependent); rotation ~20–30 deg at 90 deg flexion (approx.)",
        "Joint Reaction Forces": "Compressive forces often 2–4× BW walking and higher in running/squatting (instrumented and model estimates vary)",
        "Clinical Assessment": "Effusion (stroke/ballottement); alignment (Q-angle, varus/valgus); ROM; strength; ligament laxity; meniscal signs; gait",
        "Special Tests": "Lachman, anterior/posterior drawer, pivot shift, valgus/varus stress, McMurray, Thessaly, dial test — interpret in cluster",
        "Common Pathologies": "Ligament tears, meniscal injury, OA, OCD, loose bodies, arthrofibrosis",
        "Imaging": "Radiographs first for fracture/OA; MRI for soft tissue; CT for complex fracture",
        "Manual Therapy": "Tibiofemoral AP/PA glides, distraction, soft-tissue — as adjunct within pain-free ranges; avoid aggressive mobility on acute ligament tears",
        "Rehabilitation": "Quad activation, ROM restoration, progressive strengthening, neuromuscular control, criteria-based RTS",
        "References": f"{RB} {RC} {RA}",
    }),
    ("Patellofemoral Joint", {
        "ID": "KNEE-JNT-02",
        "Joint": "Patellofemoral joint",
        "Type": "Synovial plane/saddle-like articulation between patella and trochlea",
        "Capsule": "Continuous with knee capsule; medial/lateral retinacula; suprapatellar pouch communication",
        "Articular Cartilage": "Thick patellar cartilage; trochlear cartilage — early PF OA common",
        "Ligaments": "MPFL primary medial stabilizer 0–30 deg flexion; medial/lateral retinacula; LPFL less discrete",
        "Menisci": "Not primary PF structures; patellomeniscal ligaments variable",
        "Blood Supply": "Genicular anastomosis around patella",
        "Innervation": "Infrapatellar saphenous branch; retinacular nerves — anterior knee pain substrate",
        "Arthrokinematics": "Patella glides inferior with flexion and superior with extension; medial-lateral tilt/rotation accompany tracking",
        "Osteokinematics": "Patellar motion coupled to tibiofemoral flexion angle; contact area migrates proximal on patella with deeper flexion",
        "Normal ROM": "Patellar mobility assessed mediolateral glide (~1–2 quadrants typical teaching — individualize); TF flexion ROM governs PF contact",
        "Joint Reaction Forces": "Increase with knee flexion angle and quad force; stairs and deep squat high PF load",
        "Clinical Assessment": "Tracking, apprehension, grind/clarke (interpret cautiously), step-down quality, hip/foot contributors",
        "Special Tests": "Patellar apprehension; moving apprehension; J-sign observation; compression tests limited specificity",
        "Common Pathologies": "PFPS, instability/dislocation, chondral lesions, OA, plica irritation",
        "Imaging": "Sunrise/Merchant views; MRI for MPFL/cartilage; TT-TG distance in instability workups",
        "Manual Therapy": "Medial patellar glides if lateral tightness; soft-tissue ITB/lateral retinaculum — evidence mixed; combine with exercise",
        "Rehabilitation": "Quad strengthening (including VMO emphasis as part of quad, not isolated myth); hip abductor/ER; load management; taping/orthoses adjunct",
        "References": f"{RB} PFPS consensus statements. {RC}",
    }),
    ("Proximal Tibiofibular Joint", {
        "ID": "KNEE-JNT-03",
        "Joint": "Proximal tibiofibular joint (PTFJ)",
        "Type": "Plane synovial joint",
        "Capsule": "Fibrous capsule with anterior and posterior tibiofibular ligaments",
        "Articular Cartilage": "Hyaline on tibial facet and fibular head",
        "Ligaments": "Anterior and posterior proximal tibiofibular ligaments; association with LCL/biceps complex",
        "Menisci": "None",
        "Blood Supply": "Inferior lateral genicular; anterior tibial recurrent",
        "Innervation": "Common fibular nerve branches; recurrent genicular",
        "Arthrokinematics": "Small superior/inferior and rotational glides with ankle dorsi/plantarflexion",
        "Osteokinematics": "Accessory motion supporting ankle; not a primary knee mover",
        "Normal ROM": "Minimal — assessed by fibular head AP glide",
        "Joint Reaction Forces": "Low compared with tibiofemoral; higher with certain ankle-loaded sports",
        "Clinical Assessment": "Fibular head tenderness/mobility; common fibular nerve screen; differentiate LCL/PLC pain",
        "Special Tests": "Fibular head translation; ankle dorsiflexion with PTFJ symptom change",
        "Common Pathologies": "Instability (anterolateral dislocation rare); OA; referred pain; injury with PLC",
        "Imaging": "Radiographs comparing sides; MRI if PLC/nerve concern",
        "Manual Therapy": "Fibular head AP/PA mobilizations when hypomobile and indicated",
        "Rehabilitation": "Progressive loading; address ankle DF; lateral knee stability if PLC involved",
        "References": f"{RA} {RC}",
    }),
]

MENISCUS_RECORDS: list[tuple[str, dict[str, Any]]] = [
    ("Medial Meniscus", {
        "ID": "KNEE-MEN-01",
        "Structure": "C-shaped fibrocartilage disc; broader posterior horn; firmly attached to MCL deep layer / capsule",
        "Region": "Medial tibiofemoral compartment",
        "Attachments": "Anterior and posterior roots to tibial intercondylar region; coronary (meniscotibial) ligaments; deep MCL; semimembranosus expansions posteriorly",
        "Blood Supply": "Peripheral capillary plexus from genicular/middle genicular — red-red outer third; inner two-thirds relatively avascular",
        "Innervation": "Peripheral horns richly innervated (mechanoreceptors/nociceptors); free edge less",
        "Zones": "Red-red (peripheral), red-white (middle), white-white (central) — healing potential follows vascularity",
        "Function": "Load distribution, shock absorption, joint stability (esp. anterior translation secondary), lubrication/nutrition",
        "Shock Absorption": "Converts compressive loads to hoop stresses via circumferential collagen",
        "Load Distribution": "Increases contact area; medial meniscectomy substantially elevates peak contact stress",
        "Biomechanics": "Less mobile than lateral (~2–5 mm translation); torn more often partly due to MCL fixation",
        "Clinical Tests": "McMurray (medial), Thessaly, Apley compression, joint-line tenderness — clusters better than single tests",
        "MRI Findings": "Intrameniscal signal to articular surface (Grade 3 tear); root tear with extrusion; ramp lesions with ACL",
        "Healing Potential": "Peripheral longitudinal tears best; white-white poor; roots critical if repaired early",
        "Common Injuries": "Posterior horn tears; bucket-handle; root tears; degenerative horizontal cleavage in middle age",
        "Mechanism": "Twisting on flexed planted foot; degenerative attrition; ACL injury association (medial ramp)",
        "Conservative Treatment": "Activity modification, effusion control, quad strength, progressive loading for stable degenerative tears per evidence",
        "Surgical Treatment": "Repair preferred when feasible (esp. young/peripheral/root); partial meniscectomy if irreparable; meniscal transplant selected cases",
        "Rehabilitation": "Repair: protected WB/ROM per protocol often 4–6+ weeks. Meniscectomy: faster ROM/WB progression",
        "Return to Sport": "Repair often 4–6 months criteria-based; meniscectomy earlier if strength/effusion allow — individualize",
        "References": f"{RA} Meniscal repair healing literature. {RC} Beaufils/Pujol meniscus guidelines themes.",
    }),
    ("Lateral Meniscus", {
        "ID": "KNEE-MEN-02",
        "Structure": "More circular O-shaped fibrocartilage; covers greater % of lateral plateau; more mobile",
        "Region": "Lateral tibiofemoral compartment",
        "Attachments": "Anterior/posterior roots; loose coronary ligaments; no firm LCL attachment; meniscofemoral ligaments (Humphrey/Wrisberg) variable to PCL",
        "Blood Supply": "Similar peripheral-to-central gradient from genicular plexus",
        "Innervation": "Peripheral mechanoreceptors/nociceptors",
        "Zones": "Red-red / red-white / white-white as medial",
        "Function": "Lateral load distribution; rotational congruence; secondary stability",
        "Shock Absorption": "Hoop stress mechanism; discoid variants alter mechanics",
        "Load Distribution": "Lateral meniscectomy particularly detrimental to contact mechanics",
        "Biomechanics": "Translation ~9–11 mm possible — more mobile, slightly lower tear rate than medial overall but common with ACL",
        "Clinical Tests": "McMurray lateral; Thessaly; joint-line tenderness; bounce home",
        "MRI Findings": "Tear patterns; discoid meniscus; meniscofemoral ligament mimics; root/extrusion",
        "Healing Potential": "Vascular zone dependent; discoid saucerization considerations in youth",
        "Common Injuries": "ACL-associated lateral tears; discoid tear in children; popliteomeniscal fascicle injuries",
        "Mechanism": "Pivot-shift ACL mechanism; squat/twist; discoid abnormal morphology",
        "Conservative Treatment": "Selected stable tears; activity and strength programs",
        "Surgical Treatment": "Repair when possible; saucerization of symptomatic discoid; preserve tissue",
        "Rehabilitation": "Similar repair protections; emphasize quad and neuromuscular control",
        "Return to Sport": "Criteria-based; concurrent ACL dictates timeline often",
        "References": f"{RA} {RC} Discoid meniscus reviews.",
    }),
]
