-- Physio invite codes: patients create their own account and link with a code
-- generated by their physiotherapist (replaces physio-created patient accounts).

-- 1. Store one active invite code per physio on profiles --------------------------

alter table public.profiles
  add column if not exists invite_code text;

create unique index if not exists profiles_invite_code_uidx
  on public.profiles (invite_code)
  where invite_code is not null;

-- 2. Allow controlled physio_id linking via RPC (trigger bypass flag) ------------

create or replace function public.profiles_protect_is_admin()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    if auth.uid() is not null then
      new.is_admin := false;
      new.account_type := 'patient';
      -- Allow invite_code only for physio rows created by service role (auth.uid null).
      -- Patients cannot self-set invite_code / physio_id on insert via client.
      if coalesce(current_setting('app.linking_physio', true), '') <> '1' then
        new.physio_id := null;
        new.invite_code := null;
      end if;
    end if;
  elsif tg_op = 'UPDATE' then
    if auth.uid() is not null then
      new.is_admin := old.is_admin;
      new.account_type := old.account_type;
      if coalesce(current_setting('app.linking_physio', true), '') = '1' then
        -- RPC may update physio_id / invite_code
        null;
      else
        new.physio_id := old.physio_id;
        new.invite_code := old.invite_code;
      end if;
    end if;
  end if;
  return new;
end;
$$;

-- 3. Helpers ---------------------------------------------------------------------

create or replace function public._generate_physio_invite_code()
returns text
language plpgsql
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  candidate text;
  i int;
begin
  loop
    candidate := '';
    for i in 1..8 loop
      candidate := candidate || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
    end loop;
    exit when not exists (
      select 1 from public.profiles p where p.invite_code = candidate
    );
  end loop;
  return candidate;
end;
$$;

-- 4. Physio: ensure / regenerate invite code -------------------------------------

create or replace function public.physio_get_or_create_invite_code()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  existing text;
  generated text;
begin
  if not public.is_physio() then
    raise exception 'not authorized';
  end if;

  select p.invite_code into existing
  from public.profiles p
  where p.id = auth.uid();

  if existing is not null and length(existing) > 0 then
    return existing;
  end if;

  generated := public._generate_physio_invite_code();
  perform set_config('app.linking_physio', '1', true);
  update public.profiles
  set invite_code = generated
  where id = auth.uid();
  return generated;
end;
$$;

revoke all on function public.physio_get_or_create_invite_code() from public;
grant execute on function public.physio_get_or_create_invite_code() to authenticated;

create or replace function public.physio_regenerate_invite_code()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  generated text;
begin
  if not public.is_physio() then
    raise exception 'not authorized';
  end if;

  generated := public._generate_physio_invite_code();
  perform set_config('app.linking_physio', '1', true);
  update public.profiles
  set invite_code = generated
  where id = auth.uid();
  return generated;
end;
$$;

revoke all on function public.physio_regenerate_invite_code() from public;
grant execute on function public.physio_regenerate_invite_code() to authenticated;

-- 5. Patient: redeem code → set physio_id ----------------------------------------

create or replace function public.patient_link_physio_code(p_code text)
returns table (
  physio_id uuid,
  physio_name text,
  clinic_name text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized text;
  target record;
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;

  -- Only patients (or unset) may link; physios cannot link to another physio.
  if exists (
    select 1 from public.profiles me
    where me.id = auth.uid() and me.account_type = 'physio'
  ) then
    raise exception 'los fisioterapeutas no pueden vincularse con un código';
  end if;

  normalized := upper(trim(coalesce(p_code, '')));
  if length(normalized) < 6 then
    raise exception 'código no válido';
  end if;

  select p.id, p.display_name, p.clinic_name
  into target
  from public.profiles p
  where p.account_type = 'physio'
    and p.invite_code = normalized
  limit 1;

  if target.id is null then
    raise exception 'código no encontrado';
  end if;

  if target.id = auth.uid() then
    raise exception 'código no válido';
  end if;

  perform set_config('app.linking_physio', '1', true);
  update public.profiles
  set physio_id = target.id
  where id = auth.uid();

  physio_id := target.id;
  physio_name := target.display_name;
  clinic_name := target.clinic_name;
  return next;
end;
$$;

revoke all on function public.patient_link_physio_code(text) from public;
grant execute on function public.patient_link_physio_code(text) to authenticated;
