export const Colors = {
  primary: "#2563EB",
  primaryLight: "#DBEAFE",
  primarySoft: "#EFF6FF",
  primaryDark: "#1E40AF",
  white: "#FFFFFF",
  background: "#F5F8FF",
  surface: "#FFFFFF",
  border: "#E2E8F0",
  borderStrong: "#BFDBFE",
  text: "#0F172A",
  textSecondary: "#64748B",
  textLight: "#94A3B8",
  danger: "#EF4444",
  dangerSoft: "#FEF2F2",
  success: "#10B981",
  successSoft: "#ECFDF5",
  warning: "#F59E0B",
  warningSoft: "#FFFBEB",
  tabBar: "#FFFFFF",
  tabBarBorder: "#F1F5F9",
  tabIconActive: "#2563EB",
  tabIconInactive: "#94A3B8",
};
